# generate_s7.R
# Generate S7 class definitions from parsed SWIG class definitions

# ============================================================================
# Utilities
# ============================================================================

# Convert CamelCase to snake_case
to_snake_case <- function(name) {
  name <- gsub("([a-z])([A-Z])", "\\1_\\2", name)
  tolower(name)
}

# Map SWIG/C return types to R types for documentation
map_r_type <- function(swig_type) {
  swig_type <- trimws(swig_type)
  swig_type <- gsub("\\s*\\*", "*", swig_type)

  mapping <- list(
    "void" = "NULL",
    "int" = "integer",
    "double" = "numeric",
    "bool" = "logical",
    "const char*" = "character",
    "char const*" = "character",
    "char*" = "character",
    "char**" = "character",
    "CPLErr" = "integer",
    "OGRErr" = "integer"
  )

  if (swig_type %in% names(mapping)) {
    return(mapping[[swig_type]])
  }

  # GDAL objects
  if (grepl("Shadow\\*$|HS\\*$", swig_type)) {
    # Extract class name: GDALDatasetShadow* -> GDALDataset
    cls <- sub("Shadow\\*$", "", swig_type)
    cls <- sub("HS\\*$", "", cls)
    return(cls)
  }

  "ANY"
}

# Get cpp11 function name
get_cpp11_func <- function(class_name, method_name) {
  sprintf("GDAL7_%s_%s", tolower(class_name), to_snake_case(method_name))
}

# ============================================================================
# Code generation
# ============================================================================

# Generate file header
generate_s7_header <- function(class_name) {
  sprintf('# Auto-generated by GDAL7 generator - do not edit
# S7 class definition for %s

#\' @importFrom S7 new_class new_property new_generic method class_any class_character class_integer class_double class_logical
NULL

', class_name)
}

# Generate S7 class definition
generate_s7_class <- function(parsed_class) {
  class_name <- parsed_class$public_name
  class_lower <- tolower(class_name)

  # Parent class
  parent <- if (!is.na(parsed_class$parent)) {
    # Map Shadow name to public name
    parent_public <- sub("Shadow$", "", parsed_class$parent)
    parent_public <- sub("^GDAL", "", parent_public)
    sprintf("GDAL%s", parent_public)
  } else {
    "S7::class_any"
  }

  # Start class definition
  lines <- c()
  lines <- c(lines, sprintf('#\' GDAL %s class', class_name))
  lines <- c(lines, '#\'')
  lines <- c(lines, sprintf('#\' @description S7 class wrapping GDAL%s', class_name))
  lines <- c(lines, '#\' @export')
  lines <- c(lines, sprintf('GDAL%s <- S7::new_class(', class_name))
  lines <- c(lines, sprintf('  "GDAL%s",', class_name))
  lines <- c(lines, '  package = "GDAL7",')

  # Handle parent
  if (parent != "S7::class_any") {
    lines <- c(lines, sprintf('  parent = %s,', parent))
  }

  lines <- c(lines, '')
  lines <- c(lines, '  properties = list(')
  lines <- c(lines, '    # Internal pointer - not for direct user access')
  lines <- c(lines, '    .ptr = S7::class_any')

  # Add properties from %immutable (if we had them parsed)
  # For now, just the pointer

  lines <- c(lines, '  ),')
  lines <- c(lines, '')
  lines <- c(lines, '  validator = function(self) {')
  lines <- c(lines, '    if (is.null(self@.ptr)) {')
  lines <- c(lines, sprintf('      "GDAL%s pointer cannot be NULL"', class_name))
  lines <- c(lines, '    }')
  lines <- c(lines, '  }')
  lines <- c(lines, ')')
  lines <- c(lines, '')

  paste(lines, collapse = "\n")
}

# Generate S7 generics
generate_s7_generics <- function(parsed_class) {
  class_name <- parsed_class$public_name

  lines <- c()
  lines <- c(lines, '# -----------------------------------------------------------------------------')
  lines <- c(lines, sprintf('# Generics for GDAL%s', class_name))
  lines <- c(lines, '# -----------------------------------------------------------------------------')
  lines <- c(lines, '')

  # Track generated generics to avoid duplicates
  generated <- character()

  for (method in parsed_class$methods) {
    generic_name <- to_snake_case(method$name)

    # Skip overloads (already generated the generic)
    base_generic <- sub("_[0-9]+$", "", generic_name)
    if (base_generic %in% generated) next
    generated <- c(generated, base_generic)

    # Skip simple getters/setters that should be properties
    # For now, generate all as generics

    r_return <- map_r_type(method$return_type)

    lines <- c(lines, sprintf('#\' %s', method$name))
    lines <- c(lines, '#\'')
    lines <- c(lines, sprintf('#\' @param x A GDAL%s object', class_name))

    # Document other parameters
    for (p in method$params) {
      r_type <- map_r_type(p$type)
      default_str <- if (!is.null(p$default)) sprintf(' (default: %s)', p$default) else ''
      lines <- c(lines, sprintf('#\' @param %s %s%s', p$name, r_type, default_str))
    }

    lines <- c(lines, sprintf('#\' @return %s', r_return))
    lines <- c(lines, '#\' @export')
    lines <- c(lines, sprintf('%s <- S7::new_generic("%s", "x")', base_generic, base_generic))
    lines <- c(lines, '')
  }

  paste(lines, collapse = "\n")
}

# Generate S7 methods
generate_s7_methods <- function(parsed_class) {
  class_name <- parsed_class$public_name
  class_lower <- tolower(class_name)

  lines <- c()
  lines <- c(lines, '# -----------------------------------------------------------------------------')
  lines <- c(lines, sprintf('# Methods for GDAL%s', class_name))
  lines <- c(lines, '# -----------------------------------------------------------------------------')
  lines <- c(lines, '')

  # Track overload counts
  method_counts <- list()

  for (method in parsed_class$methods) {
    base_name <- sub("_[0-9]+$", "", method$name)
    generic_name <- to_snake_case(base_name)

    # Track overloads
    if (is.null(method_counts[[base_name]])) {
      method_counts[[base_name]] <- 1
    } else {
      method_counts[[base_name]] <- method_counts[[base_name]] + 1
    }

    # Use full method name for cpp11 function (includes _2 suffix for overloads)
    cpp_func <- get_cpp11_func(class_name, method$name)

    # For overloaded methods, create separate R functions with different names
    # (R doesn't support true overloading)
    r_func_name <- if (method_counts[[base_name]] > 1) {
      sprintf("%s_%d", generic_name, method_counts[[base_name]])
    } else {
      generic_name
    }

    # Build R parameter list (excluding 'x' which is the object)
    r_params <- c("x")
    call_args <- c("x@.ptr")

    for (p in method$params) {
      param_name <- p$name
      r_params <- c(r_params, param_name)

      # Add type coercion if needed
      if (grepl("int", p$type)) {
        call_args <- c(call_args, sprintf("as.integer(%s)", param_name))
      } else if (grepl("double", p$type)) {
        call_args <- c(call_args, sprintf("as.double(%s)", param_name))
      } else {
        call_args <- c(call_args, param_name)
      }
    }

    r_params_str <- paste(r_params, collapse = ", ")
    call_args_str <- paste(call_args, collapse = ", ")

    # For overloads after the first, also create the generic
    if (method_counts[[base_name]] > 1) {
      lines <- c(lines, sprintf('#\' @export'))
      lines <- c(lines, sprintf('%s <- S7::new_generic("%s", "x")', r_func_name, r_func_name))
      lines <- c(lines, '')
    }

    # Generate method
    lines <- c(lines, sprintf('S7::method(%s, GDAL%s) <- function(%s) {',
                              r_func_name,
                              class_name,
                              r_params_str))

    # Handle return type
    r_return <- map_r_type(method$return_type)

    if (method$return_type == "void") {
      lines <- c(lines, sprintf('  .Call(%s, %s)', cpp_func, call_args_str))
      lines <- c(lines, '  invisible(x)')
    } else if (grepl("Shadow\\*$|HS\\*$", method$return_type)) {
      # Returns a GDAL object - wrap in S7 class
      return_class <- map_r_type(method$return_type)
      lines <- c(lines, sprintf('  ptr <- .Call(%s, %s)', cpp_func, call_args_str))
      lines <- c(lines, sprintf('  if (is.null(ptr)) return(NULL)'))
      lines <- c(lines, sprintf('  %s(.ptr = ptr)', return_class))
    } else {
      lines <- c(lines, sprintf('  .Call(%s, %s)', cpp_func, call_args_str))
    }

    lines <- c(lines, '}')
    lines <- c(lines, '')
  }

  paste(lines, collapse = "\n")
}

# Generate print method
generate_s7_print <- function(parsed_class) {
  class_name <- parsed_class$public_name

  sprintf('
#\' @export
S7::method(print, GDAL%s) <- function(x, ...) {
  cat("<GDAL%s>\\n")
  desc <- get_description(x)
  if (nzchar(desc)) {
    cat("  Description:", desc, "\\n")
  }
  invisible(x)
}
', class_name, class_name)
}

# Generate complete S7 file for a class
generate_s7_file <- function(parsed_class, output_path = NULL) {
  code <- paste(
    generate_s7_header(parsed_class$public_name),
    generate_s7_class(parsed_class),
    generate_s7_generics(parsed_class),
    generate_s7_methods(parsed_class),
    generate_s7_print(parsed_class),
    sep = "\n"
  )

  if (!is.null(output_path)) {
    writeLines(code, output_path)
    message(sprintf("Generated %s", output_path))
  }

  invisible(code)
}

# ============================================================================
# Test
# ============================================================================

if (interactive() || !exists("SOURCED_S7_GEN")) {
  #source("parse_swig.R", local = TRUE)
  SOURCED <- TRUE

  result <- parse_swig_file(file.path(swig_dir, "MajorObject.i"), debug = FALSE)
  cls <- result$classes[[1]]

  code <- generate_s7_file(cls)
  cat(code)
}
