# data-raw/generate_constants.R
#
# Emit GDAL's %constant directives, and the capability table that says which
# generated bindings the GDAL in use is new enough for.
#
# GDAL declares its enumerators in gdalconst.i and nowhere else the generator
# reads, so without this a data type reaches R as a bare integer with nothing
# in the package to interpret it against.

# Headers the constants live in, beyond what gdal7.h already pulls in.
CONSTANT_HEADERS <- c("cpl_minixml.h", "gdalwarper.h", "ogr_core.h")

# Constants the generator leaves alone. GDAL's own algorithm header is not in
# every build's include path, and these are the only constants that need it.
CONSTANT_SKIP_PREFIXES <- c("GAAT_", "GADV_")

constant_guard <- function(since, baseline) {
  if (is.null(since) || is.na(since)) return(NA_character_)
  if (package_version(since) <= package_version(baseline)) NA_character_ else since
}

# One row of a static table. A table plus a loop is a fraction of the compiled
# size of a few hundred push_back pairs, and reads better besides.
emit_constant <- function(const, since, baseline) {
  line <- sprintf('    {"%s", %s},', const$name, const$value)
  guard <- constant_guard(since, baseline)
  if (is.na(guard)) return(line)
  paste(sprintf("#if GDAL_VERSION_NUM >= %s", compute_version_macro(guard)),
        line, "#endif", sep = "\n")
}

generate_constants_file <- function(model, output_path,
                                    symbol_versions = read_symbol_versions()) {
  baseline <- guard_baseline(symbol_versions)

  ints <- character()
  strings <- character()
  skipped <- character()

  for (const in model$constants) {
    if (any(startsWith(const$name, CONSTANT_SKIP_PREFIXES))) {
      next
    }

    # A value in quotes is a literal, so there is no symbol to date.
    literal <- grepl('^"', const$value)
    since <- if (literal) NA_character_ else symbol_versions[[const$value]]

    if (!literal && is.null(since)) {
      skipped <- c(skipped, sprintf("//   %-44s %s is in no release the symbol table covers",
                                    const$name, const$value))
      next
    }

    if (identical(const$kind, "string")) {
      strings <- c(strings, emit_constant(const, since, baseline))
    } else {
      ints <- c(ints, emit_constant(const, since, baseline))
    }
  }

  includes <- paste(sprintf("#include <%s>", CONSTANT_HEADERS), collapse = "\n")

  footer <- if (length(skipped) == 0) "" else paste0(
    "\n// Not emitted, because the GDAL releases the symbol table covers do not\n",
    "// declare them. Re-run data-raw/refresh_symbol_versions.R against a newer\n",
    "// GDAL to pick them up.\n",
    paste(skipped, collapse = "\n"), "\n"
  )

  code <- sprintf('// Auto-generated by GDAL7 generator - do not edit
#include "gdal7.h"

%s

using namespace cpp11;

// -----------------------------------------------------------------------------
// GDAL constants
//
// Each constant carries the GDAL release it first appeared in, so one source
// tree serves a range of GDAL versions: a constant newer than the GDAL in use
// is not in the table rather than breaking the build.
// -----------------------------------------------------------------------------

namespace {

struct IntConstant {
    const char* name;
    int value;
};

struct StringConstant {
    const char* name;
    const char* value;
};

const IntConstant kIntConstants[] = {
%s
};

const StringConstant kStringConstants[] = {
%s
};

}  // namespace

[[cpp11::register]]
integers GDAL7_integer_constants() {
    const R_xlen_t n = static_cast<R_xlen_t>(sizeof(kIntConstants) / sizeof(kIntConstants[0]));
    writable::integers values(n);
    writable::strings names(n);
    for (R_xlen_t i = 0; i < n; ++i) {
        values[i] = kIntConstants[i].value;
        names[i] = kIntConstants[i].name;
    }
    values.attr("names") = names;
    return values;
}

[[cpp11::register]]
strings GDAL7_string_constants() {
    const R_xlen_t n = static_cast<R_xlen_t>(sizeof(kStringConstants) / sizeof(kStringConstants[0]));
    writable::strings values(n);
    writable::strings names(n);
    for (R_xlen_t i = 0; i < n; ++i) {
        values[i] = kStringConstants[i].value;
        names[i] = kStringConstants[i].name;
    }
    values.attr("names") = names;
    return values;
}
%s', includes, paste(ints, collapse = "\n"), paste(strings, collapse = "\n"), footer)

  writeLines(code, output_path)
  message(sprintf("Generated %s (%d integer, %d string constants)",
                  output_path, length(ints), length(strings)))
  invisible(list(int = length(ints), string = length(strings)))
}

# The bindings that carry a version guard, and the release each one needs. What
# the guard decides at compile time, this reports at run time.
generate_capabilities_file <- function(capabilities, output_path) {
  if (length(capabilities) == 0) {
    entries <- "    // No generated binding needs a GDAL newer than the baseline."
  } else {
    entries <- paste(vapply(capabilities, function(cap) {
      sprintf('    names.push_back("%s");
    since.push_back("%s");
#if GDAL_VERSION_NUM >= %s
    available.push_back(TRUE);
#else
    available.push_back(FALSE);
#endif',
              cap$name, cap$since, compute_version_macro(cap$since))
    }, character(1)), collapse = "\n\n")
  }

  code <- sprintf('// Auto-generated by GDAL7 generator - do not edit
#include "gdal7.h"

using namespace cpp11;

// -----------------------------------------------------------------------------
// Capabilities
//
// A binding whose GDAL function is newer than the GDAL in use still exists and
// still dispatches; calling it raises an error naming the release it needs.
// This is how to ask before calling.
// -----------------------------------------------------------------------------

[[cpp11::register]]
list GDAL7_capabilities() {
    writable::strings names;
    writable::strings since;
    writable::logicals available;

%s

    return writable::list({
        "binding"_nm = names,
        "gdal"_nm = since,
        "available"_nm = available
    });
}

[[cpp11::register]]
strings GDAL7_gdal_version() {
    return writable::strings({
        r_string(GDALVersionInfo("RELEASE_NAME")),
        r_string(GDALVersionInfo("RELEASE_DATE")),
        r_string(GDALVersionInfo("--version"))
    });
}
', entries)

  writeLines(code, output_path)
  message(sprintf("Generated %s (%d guarded bindings)", output_path, length(capabilities)))
  invisible(length(capabilities))
}
