// inst/include/gdal7.h
// Manual file - NOT generated by orchestrate.R
//
// Object lifetimes and error reporting for the GDAL C API.
//
// Every GDAL object reaches R as an external pointer holding a gdal7::Handle.
// The Handle carries the raw GDAL handle, the kind of object it is, and a
// shared_ptr to the Owner record of whatever must be freed for it to stay
// valid. A band borrows the Owner of its dataset, a group borrows the Owner of
// its dataset and adds its own, and so on up the chain. Two things follow:
//
//   * A child keeps its parent alive. Dropping the last reference to a dataset
//     in R does not close it while a band taken from it is still reachable.
//   * Closing a dataset explicitly marks the whole chain dead, so touching a
//     band afterwards raises an R error instead of reading freed memory.
//
// The external pointer's tag records the kind, so passing a band where a
// dataset is expected is rejected rather than reinterpret_cast into a crash.

#ifndef GDAL7_H
#define GDAL7_H

#include <cstring>
#include <memory>
#include <string>
#include <utility>
#include <vector>

#include <cpp11.hpp>

#include <cpl_conv.h>
#include <cpl_error.h>
#include <cpl_string.h>
#include <gdal.h>

namespace gdal7 {

// ---------------------------------------------------------------------------
// Object kinds
// ---------------------------------------------------------------------------

enum class Kind { Dataset, Band, Driver, Group, MDArray, SpatialRef };

inline const char* kind_name(Kind kind) {
    switch (kind) {
        case Kind::Dataset: return "GDALDataset";
        case Kind::Band: return "GDALRasterBand";
        case Kind::Driver: return "GDALDriver";
        case Kind::Group: return "GDALGroup";
        case Kind::MDArray: return "GDALMDArray";
        case Kind::SpatialRef: return "OGRSpatialReference";
    }
    return "GDAL object";
}

// The external pointer tag. R symbols are never collected, so caching one in a
// static is safe, and comparing tags is a pointer comparison.
inline SEXP kind_tag(Kind kind) {
    switch (kind) {
        case Kind::Dataset: { static SEXP s = Rf_install("GDAL7_dataset"); return s; }
        case Kind::Band: { static SEXP s = Rf_install("GDAL7_band"); return s; }
        case Kind::Driver: { static SEXP s = Rf_install("GDAL7_driver"); return s; }
        case Kind::Group: { static SEXP s = Rf_install("GDAL7_group"); return s; }
        case Kind::MDArray: { static SEXP s = Rf_install("GDAL7_mdarray"); return s; }
        case Kind::SpatialRef: { static SEXP s = Rf_install("GDAL7_spatialref"); return s; }
    }
    static SEXP other = Rf_install("GDAL7_object");
    return other;
}

// Whether GDAL7 has to free an object of this kind, or whether it is borrowed
// from something else that does. Drivers belong to GDAL's driver manager and
// outlive everything, so they are neither owned nor tied to a parent.
inline bool kind_is_owned(Kind kind) {
    return kind == Kind::Dataset || kind == Kind::Group || kind == Kind::MDArray;
}

// ---------------------------------------------------------------------------
// Ownership records
// ---------------------------------------------------------------------------

// One record per GDAL object that GDAL7 must free. `parent` is the record of
// the object this one was derived from, which is what makes a dataset outlive
// the groups and arrays taken out of it.
struct Owner {
    void* handle;
    Kind kind;
    std::shared_ptr<Owner> parent;

    Owner(void* h, Kind k, std::shared_ptr<Owner> p)
        : handle(h), kind(k), parent(std::move(p)) {}

    Owner(const Owner&) = delete;
    Owner& operator=(const Owner&) = delete;

    ~Owner() { release(); }

    // Free the object. Safe to call twice; the second call does nothing.
    // Reached from an R finalizer as well as from an explicit close, so it
    // must never touch the R API.
    void release() {
        void* h = handle;
        if (h == nullptr) {
            return;
        }
        handle = nullptr;
        switch (kind) {
            case Kind::Dataset: GDALClose(static_cast<GDALDatasetH>(h)); break;
            case Kind::Group: GDALGroupRelease(static_cast<GDALGroupH>(h)); break;
            case Kind::MDArray: GDALMDArrayRelease(static_cast<GDALMDArrayH>(h)); break;
            default: break;
        }
    }

    // The first record in this chain that has been closed, or null when the
    // whole chain is still open.
    const Owner* dead_ancestor() const {
        for (const Owner* o = this; o != nullptr; o = o->parent.get()) {
            if (o->handle == nullptr) {
                return o;
            }
        }
        return nullptr;
    }
};

// What an external pointer actually points at.
struct Handle {
    void* ptr;
    Kind kind;
    std::shared_ptr<Owner> owner;  // null for objects GDAL itself keeps forever

    Handle(void* p, Kind k, std::shared_ptr<Owner> o)
        : ptr(p), kind(k), owner(std::move(o)) {}
};

inline void finalize_handle(SEXP xp) {
    Handle* h = static_cast<Handle*>(R_ExternalPtrAddr(xp));
    if (h == nullptr) {
        return;
    }
    R_ClearExternalPtr(xp);
    // Dropping the last reference to the Owner is what frees the GDAL object.
    delete h;
}

// ---------------------------------------------------------------------------
// Making handles
// ---------------------------------------------------------------------------

// Wrap a GDAL handle for R. `parent` is the external pointer of the object it
// came from, or R_NilValue. It is stored in the protection slot as well as
// being followed for its Owner, so the R object graph mirrors the C++ one.
inline SEXP wrap(void* ptr, Kind kind, SEXP parent = R_NilValue) {
    if (ptr == nullptr) {
        return R_NilValue;
    }

    std::shared_ptr<Owner> parent_owner;
    if (parent != R_NilValue && TYPEOF(parent) == EXTPTRSXP) {
        Handle* p = static_cast<Handle*>(R_ExternalPtrAddr(parent));
        if (p != nullptr) {
            parent_owner = p->owner;
        }
    }

    std::shared_ptr<Owner> owner =
        kind_is_owned(kind) ? std::make_shared<Owner>(ptr, kind, parent_owner)
                            : parent_owner;

    std::unique_ptr<Handle> handle(new Handle(ptr, kind, std::move(owner)));

    SEXP xp = PROTECT(cpp11::safe[R_MakeExternalPtr](nullptr, kind_tag(kind), parent));
    // Register an on-exit finalizer too, so datasets opened for update are
    // flushed when R quits rather than left half-written.
    cpp11::safe[R_RegisterCFinalizerEx](xp, finalize_handle, static_cast<Rboolean>(1));
    R_SetExternalPtrAddr(xp, handle.release());
    UNPROTECT(1);
    return xp;
}

// ---------------------------------------------------------------------------
// Reading handles back
// ---------------------------------------------------------------------------

// Whether an external pointer is one of ours at all.
inline bool is_handle(SEXP xp) {
    if (TYPEOF(xp) != EXTPTRSXP) {
        return false;
    }
    SEXP tag = R_ExternalPtrTag(xp);
    const Kind kinds[] = {Kind::Dataset, Kind::Band, Kind::Driver,
                          Kind::Group, Kind::MDArray, Kind::SpatialRef};
    for (Kind k : kinds) {
        if (tag == kind_tag(k)) {
            return true;
        }
    }
    return false;
}

// Raise an R error when the object, or anything it was derived from, is gone.
inline void check_alive(const Handle* h, Kind kind) {
    if (h == nullptr || h->ptr == nullptr) {
        cpp11::stop("This %s has been closed", kind_name(kind));
    }

    if (!h->owner) {
        return;
    }

    const Owner* dead = h->owner->dead_ancestor();
    if (dead == nullptr) {
        return;
    }
    if (dead == h->owner.get() && dead->kind == kind) {
        cpp11::stop("This %s has been closed", kind_name(kind));
    }
    cpp11::stop("This %s cannot be used: the %s it belongs to has been closed",
                kind_name(kind), kind_name(dead->kind));
}

inline Handle* checked_handle(SEXP xp, Kind kind) {
    if (TYPEOF(xp) != EXTPTRSXP || R_ExternalPtrTag(xp) != kind_tag(kind)) {
        cpp11::stop("Expected a %s object", kind_name(kind));
    }
    Handle* h = static_cast<Handle*>(R_ExternalPtrAddr(xp));
    check_alive(h, kind);
    return h;
}

// The GDALMajorObject side of the API is shared by datasets, bands and
// drivers. Groups and arrays are not major objects in the C API and spatial
// references are not GDAL objects at all, so they are turned away here rather
// than cast into one and crashed on.
inline GDALMajorObjectH major_object(SEXP xp) {
    if (!is_handle(xp)) {
        cpp11::stop("Expected a GDAL object");
    }
    Handle* h = static_cast<Handle*>(R_ExternalPtrAddr(xp));
    if (h == nullptr) {
        cpp11::stop("This GDAL object has been closed");
    }
    if (h->kind != Kind::Dataset && h->kind != Kind::Band && h->kind != Kind::Driver) {
        cpp11::stop("A %s does not carry GDAL metadata", kind_name(h->kind));
    }
    check_alive(h, h->kind);
    return static_cast<GDALMajorObjectH>(h->ptr);
}

// The GDAL handle behind an external pointer, or an R error explaining why
// there isn't one.
template <typename T>
inline T get(SEXP xp, Kind kind) {
    return static_cast<T>(checked_handle(xp, kind)->ptr);
}

// Close an object on request rather than waiting for garbage collection.
// Anything derived from it stops working at once, with an R error.
inline void close(SEXP xp, Kind kind) {
    if (TYPEOF(xp) != EXTPTRSXP || R_ExternalPtrTag(xp) != kind_tag(kind)) {
        cpp11::stop("Expected a %s object", kind_name(kind));
    }

    Handle* h = static_cast<Handle*>(R_ExternalPtrAddr(xp));
    if (h == nullptr) {
        return;
    }

    // Only release through the record that actually owns this handle. Closing
    // a borrowed view, a band say, just retires the view.
    if (h->owner && h->owner->handle == h->ptr) {
        h->owner->release();
    }
    h->ptr = nullptr;
}

// ---------------------------------------------------------------------------
// Errors and warnings
// ---------------------------------------------------------------------------

// Collects what GDAL says during one call so it can be reported as an R
// condition rather than written to stderr. Push one of these before a call
// that can fail, then either stop() on failure or flush() on success.
class ErrorScope {
 public:
    ErrorScope() : popped_(false) {
        CPLErrorReset();
        CPLPushErrorHandlerEx(&ErrorScope::collect, this);
    }

    ErrorScope(const ErrorScope&) = delete;
    ErrorScope& operator=(const ErrorScope&) = delete;

    // Popping here covers the path where a cpp11 exception unwinds the stack.
    // No R condition is raised from a destructor: raising one can longjmp.
    ~ErrorScope() { pop(); }

    // Report a failed call as an R error, quoting what GDAL said about it.
    [[noreturn]] void stop(const std::string& what) {
        pop();
        const std::string detail = joined(CE_Failure);
        if (detail.empty()) {
            cpp11::stop("%s", what.c_str());
        }
        cpp11::stop("%s: %s", what.c_str(), detail.c_str());
    }

    // Re-raise anything GDAL complained about during a call that nonetheless
    // succeeded. Call this once the result has been checked.
    void flush() {
        pop();
        std::vector<Note> notes;
        notes.swap(notes_);
        for (const Note& note : notes) {
            if (note.level == CE_Warning || note.level == CE_Failure) {
                cpp11::warning("GDAL: %s", note.message.c_str());
            }
        }
    }

    bool failed() const {
        for (const Note& note : notes_) {
            if (note.level == CE_Failure) {
                return true;
            }
        }
        return false;
    }

 private:
    struct Note {
        CPLErr level;
        std::string message;
    };

    // GDAL keeps the user data given to CPLPushErrorHandlerEx on its own
    // handler stack, so the scope this message belongs to is fetched from
    // there rather than from a global.
    static void CPL_STDCALL collect(CPLErr level, CPLErrorNum, const char* message) {
        ErrorScope* self = static_cast<ErrorScope*>(CPLGetErrorHandlerUserData());
        if (self == nullptr || level == CE_Debug || level == CE_None) {
            return;
        }
        Note note;
        note.level = level;
        note.message = message == nullptr ? std::string() : std::string(message);
        self->notes_.push_back(note);
    }

    void pop() {
        if (!popped_) {
            popped_ = true;
            CPLPopErrorHandler();
        }
    }

    std::string joined(CPLErr level) const {
        std::string out;
        for (const Note& note : notes_) {
            if (note.level != level) {
                continue;
            }
            if (!out.empty()) {
                out += "; ";
            }
            out += note.message;
        }
        return out;
    }

    std::vector<Note> notes_;
    bool popped_;
};

// ---------------------------------------------------------------------------
// String helpers
// ---------------------------------------------------------------------------

// GDAL uses a null pointer for "not set" and "" for "set to the empty string".
// Keeping the two apart on the R side is the difference between a metadata
// item that is absent and one that is present and blank.
// A binding whose C function is newer than the GDAL this was built against.
// The binding still exists, so registration and dispatch are unaffected; it is
// the call that is not there, and saying so beats failing to link.
[[noreturn]] inline void unavailable(const char* what, const char* needed) {
    cpp11::stop("%s() needs GDAL %s or newer; GDAL7 was built against %s",
                what, needed, GDALVersionInfo("RELEASE_NAME"));
}

inline cpp11::strings chr(const char* value) {
    cpp11::writable::strings out(static_cast<R_xlen_t>(1));
    if (value == nullptr) {
        out[0] = NA_STRING;
    } else {
        out[0] = cpp11::r_string(value);
    }
    return out;
}

// A string list built from an R character vector. CPLStringList frees itself,
// which the hand-rolled CSLAddString loops it replaces did not do when the
// conversion in the middle threw.
inline CPLStringList to_csl(cpp11::strings values) {
    CPLStringList out;
    for (R_xlen_t i = 0; i < values.size(); i++) {
        out.AddString(static_cast<std::string>(cpp11::r_string(values[i])).c_str());
    }
    return out;
}

// A string list built from a named R list, as KEY=VALUE.
inline CPLStringList to_csl(cpp11::list values) {
    CPLStringList out;
    if (values.size() == 0) {
        return out;
    }

    SEXP names_sexp = Rf_getAttrib(values, R_NamesSymbol);
    if (names_sexp == R_NilValue) {
        cpp11::stop("Metadata must be a named list");
    }
    cpp11::strings names(names_sexp);

    for (R_xlen_t i = 0; i < values.size(); i++) {
        const std::string key = static_cast<std::string>(cpp11::r_string(names[i]));
        const std::string value = cpp11::as_cpp<std::string>(values[i]);
        out.AddNameValue(key.c_str(), value.c_str());
    }
    return out;
}

// A GDAL string list as an R character vector. The list itself is not freed;
// GDAL hands out both borrowed and owned lists and the caller knows which.
inline cpp11::strings from_csl(CSLConstList list) {
    const int count = list == nullptr ? 0 : CSLCount(list);
    cpp11::writable::strings out(static_cast<R_xlen_t>(count));
    for (int i = 0; i < count; i++) {
        out[i] = cpp11::r_string(list[i]);
    }
    return out;
}

// A KEY=VALUE string list as a named R character vector. Entries without an
// "=" keep their whole text as the value and get an empty name, which is what
// GDAL's own dictionary view of metadata does.
inline cpp11::strings named_from_csl(CSLConstList list) {
    const int count = list == nullptr ? 0 : CSLCount(list);
    cpp11::writable::strings out(static_cast<R_xlen_t>(count));
    cpp11::writable::strings names(static_cast<R_xlen_t>(count));

    for (int i = 0; i < count; i++) {
        const char* entry = list[i];
        const char* split = strchr(entry, '=');
        if (split == nullptr) {
            names[i] = cpp11::r_string("");
            out[i] = cpp11::r_string(entry);
        } else {
            names[i] = cpp11::r_string(std::string(entry, split - entry));
            out[i] = cpp11::r_string(split + 1);
        }
    }

    out.names() = names;
    return out;
}

}  // namespace gdal7

#endif  // GDAL7_H
