// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// GDAL7_dataset.cpp
SEXP GDAL7_dataset_get_driver(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_driver(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_driver(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
SEXP GDAL7_dataset_get_raster_band(SEXP xp, int nBand);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_raster_band(SEXP xp, SEXP nBand) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_raster_band(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(nBand)));
  END_CPP11
}
// GDAL7_dataset.cpp
std::string GDAL7_dataset_get_projection(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_projection(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_projection(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
std::string GDAL7_dataset_get_projection_ref(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_projection_ref(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_projection_ref(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
SEXP GDAL7_dataset_get_spatial_ref(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_spatial_ref(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_spatial_ref(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_get_gcpcount(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_gcpcount(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_gcpcount(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
std::string GDAL7_dataset_get_gcpprojection(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_gcpprojection(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_gcpprojection(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_flush_cache(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_flush_cache(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_flush_cache(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
cpp11::strings GDAL7_dataset_get_file_list(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_file_list(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_file_list(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_get_layer_count(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_layer_count(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_layer_count(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_majorobject.cpp
std::string GDAL7_majorobject_get_description(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_description(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_description(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_majorobject.cpp
void GDAL7_majorobject_set_description(SEXP xp, std::string pszNewDesc);
extern "C" SEXP _GDAL7_GDAL7_majorobject_set_description(SEXP xp, SEXP pszNewDesc) {
  BEGIN_CPP11
    GDAL7_majorobject_set_description(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszNewDesc));
    return R_NilValue;
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_metadata_domain_list(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_metadata_domain_list(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_metadata_domain_list(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_metadata_dict(SEXP xp, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_metadata_dict(SEXP xp, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_metadata_dict(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_metadata_list(SEXP xp, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_metadata_list(SEXP xp, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_metadata_list(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
int GDAL7_majorobject_set_metadata(SEXP xp, cpp11::list papszMetadata, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_set_metadata(SEXP xp, SEXP papszMetadata, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_set_metadata(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(papszMetadata), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
int GDAL7_majorobject_set_metadata_2(SEXP xp, std::string pszMetadataString, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_set_metadata_2(SEXP xp, SEXP pszMetadataString, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_set_metadata_2(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszMetadataString), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
std::string GDAL7_majorobject_get_metadata_item(SEXP xp, std::string pszName, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_metadata_item(SEXP xp, SEXP pszName, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_metadata_item(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszName), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
int GDAL7_majorobject_set_metadata_item(SEXP xp, std::string pszName, std::string pszValue, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_set_metadata_item(SEXP xp, SEXP pszName, SEXP pszValue, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_set_metadata_item(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszName), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszValue), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP GDAL7_dataset_flush_cache(SEXP);
extern SEXP GDAL7_dataset_get_driver(SEXP);
extern SEXP GDAL7_dataset_get_file_list(SEXP);
extern SEXP GDAL7_dataset_get_gcpcount(SEXP);
extern SEXP GDAL7_dataset_get_gcpprojection(SEXP);
extern SEXP GDAL7_dataset_get_layer_count(SEXP);
extern SEXP GDAL7_dataset_get_projection(SEXP);
extern SEXP GDAL7_dataset_get_projection_ref(SEXP);
extern SEXP GDAL7_dataset_get_raster_band(SEXP, SEXP);
extern SEXP GDAL7_dataset_get_spatial_ref(SEXP);
extern SEXP GDAL7_majorobject_get_description(SEXP);
extern SEXP GDAL7_majorobject_get_metadata_dict(SEXP, SEXP);
extern SEXP GDAL7_majorobject_get_metadata_domain_list(SEXP);
extern SEXP GDAL7_majorobject_get_metadata_item(SEXP, SEXP, SEXP);
extern SEXP GDAL7_majorobject_get_metadata_list(SEXP, SEXP);
extern SEXP GDAL7_majorobject_set_description(SEXP, SEXP);
extern SEXP GDAL7_majorobject_set_metadata(SEXP, SEXP, SEXP);
extern SEXP GDAL7_majorobject_set_metadata_item(SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"GDAL7_dataset_flush_cache",                         (DL_FUNC) &GDAL7_dataset_flush_cache,                         1},
    {"GDAL7_dataset_get_driver",                          (DL_FUNC) &GDAL7_dataset_get_driver,                          1},
    {"GDAL7_dataset_get_file_list",                       (DL_FUNC) &GDAL7_dataset_get_file_list,                       1},
    {"GDAL7_dataset_get_gcpcount",                        (DL_FUNC) &GDAL7_dataset_get_gcpcount,                        1},
    {"GDAL7_dataset_get_gcpprojection",                   (DL_FUNC) &GDAL7_dataset_get_gcpprojection,                   1},
    {"GDAL7_dataset_get_layer_count",                     (DL_FUNC) &GDAL7_dataset_get_layer_count,                     1},
    {"GDAL7_dataset_get_projection",                      (DL_FUNC) &GDAL7_dataset_get_projection,                      1},
    {"GDAL7_dataset_get_projection_ref",                  (DL_FUNC) &GDAL7_dataset_get_projection_ref,                  1},
    {"GDAL7_dataset_get_raster_band",                     (DL_FUNC) &GDAL7_dataset_get_raster_band,                     2},
    {"GDAL7_dataset_get_spatial_ref",                     (DL_FUNC) &GDAL7_dataset_get_spatial_ref,                     1},
    {"GDAL7_majorobject_get_description",                 (DL_FUNC) &GDAL7_majorobject_get_description,                 1},
    {"GDAL7_majorobject_get_metadata_dict",               (DL_FUNC) &GDAL7_majorobject_get_metadata_dict,               2},
    {"GDAL7_majorobject_get_metadata_domain_list",        (DL_FUNC) &GDAL7_majorobject_get_metadata_domain_list,        1},
    {"GDAL7_majorobject_get_metadata_item",               (DL_FUNC) &GDAL7_majorobject_get_metadata_item,               3},
    {"GDAL7_majorobject_get_metadata_list",               (DL_FUNC) &GDAL7_majorobject_get_metadata_list,               2},
    {"GDAL7_majorobject_set_description",                 (DL_FUNC) &GDAL7_majorobject_set_description,                 2},
    {"GDAL7_majorobject_set_metadata",                    (DL_FUNC) &GDAL7_majorobject_set_metadata,                    3},
    {"GDAL7_majorobject_set_metadata_item",               (DL_FUNC) &GDAL7_majorobject_set_metadata_item,               4},
    {"_GDAL7_GDAL7_dataset_flush_cache",                  (DL_FUNC) &_GDAL7_GDAL7_dataset_flush_cache,                  1},
    {"_GDAL7_GDAL7_dataset_get_driver",                   (DL_FUNC) &_GDAL7_GDAL7_dataset_get_driver,                   1},
    {"_GDAL7_GDAL7_dataset_get_file_list",                (DL_FUNC) &_GDAL7_GDAL7_dataset_get_file_list,                1},
    {"_GDAL7_GDAL7_dataset_get_gcpcount",                 (DL_FUNC) &_GDAL7_GDAL7_dataset_get_gcpcount,                 1},
    {"_GDAL7_GDAL7_dataset_get_gcpprojection",            (DL_FUNC) &_GDAL7_GDAL7_dataset_get_gcpprojection,            1},
    {"_GDAL7_GDAL7_dataset_get_layer_count",              (DL_FUNC) &_GDAL7_GDAL7_dataset_get_layer_count,              1},
    {"_GDAL7_GDAL7_dataset_get_projection",               (DL_FUNC) &_GDAL7_GDAL7_dataset_get_projection,               1},
    {"_GDAL7_GDAL7_dataset_get_projection_ref",           (DL_FUNC) &_GDAL7_GDAL7_dataset_get_projection_ref,           1},
    {"_GDAL7_GDAL7_dataset_get_raster_band",              (DL_FUNC) &_GDAL7_GDAL7_dataset_get_raster_band,              2},
    {"_GDAL7_GDAL7_dataset_get_spatial_ref",              (DL_FUNC) &_GDAL7_GDAL7_dataset_get_spatial_ref,              1},
    {"_GDAL7_GDAL7_majorobject_get_description",          (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_description,          1},
    {"_GDAL7_GDAL7_majorobject_get_metadata_dict",        (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_metadata_dict,        2},
    {"_GDAL7_GDAL7_majorobject_get_metadata_domain_list", (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_metadata_domain_list, 1},
    {"_GDAL7_GDAL7_majorobject_get_metadata_item",        (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_metadata_item,        3},
    {"_GDAL7_GDAL7_majorobject_get_metadata_list",        (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_metadata_list,        2},
    {"_GDAL7_GDAL7_majorobject_set_description",          (DL_FUNC) &_GDAL7_GDAL7_majorobject_set_description,          2},
    {"_GDAL7_GDAL7_majorobject_set_metadata",             (DL_FUNC) &_GDAL7_GDAL7_majorobject_set_metadata,             3},
    {"_GDAL7_GDAL7_majorobject_set_metadata_2",           (DL_FUNC) &_GDAL7_GDAL7_majorobject_set_metadata_2,           3},
    {"_GDAL7_GDAL7_majorobject_set_metadata_item",        (DL_FUNC) &_GDAL7_GDAL7_majorobject_set_metadata_item,        4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_GDAL7(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
