// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// GDAL7_capabilities.cpp
list GDAL7_capabilities();
extern "C" SEXP _GDAL7_GDAL7_capabilities() {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_capabilities());
  END_CPP11
}
// GDAL7_capabilities.cpp
strings GDAL7_gdal_version();
extern "C" SEXP _GDAL7_GDAL7_gdal_version() {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_gdal_version());
  END_CPP11
}
// GDAL7_constants.cpp
integers GDAL7_integer_constants();
extern "C" SEXP _GDAL7_GDAL7_integer_constants() {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_integer_constants());
  END_CPP11
}
// GDAL7_constants.cpp
strings GDAL7_string_constants();
extern "C" SEXP _GDAL7_GDAL7_string_constants() {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_string_constants());
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_raster_xsize(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_raster_xsize(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_raster_xsize(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_raster_ysize(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_raster_ysize(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_raster_ysize(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_raster_count(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_raster_count(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_raster_count(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
void GDAL7_dataset_mark_suppress_on_close(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_mark_suppress_on_close(SEXP xp) {
  BEGIN_CPP11
    GDAL7_dataset_mark_suppress_on_close(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp));
    return R_NilValue;
  END_CPP11
}
// GDAL7_dataset.cpp
bool GDAL7_dataset_get_close_reports_progress(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_close_reports_progress(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_close_reports_progress(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
bool GDAL7_dataset_is_thread_safe(SEXP xp, int nScopeFlags);
extern "C" SEXP _GDAL7_GDAL7_dataset_is_thread_safe(SEXP xp, SEXP nScopeFlags) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_is_thread_safe(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(nScopeFlags)));
  END_CPP11
}
// GDAL7_dataset.cpp
SEXP GDAL7_dataset_get_thread_safe_dataset(SEXP xp, int nScopeFlags);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_thread_safe_dataset(SEXP xp, SEXP nScopeFlags) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_thread_safe_dataset(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(nScopeFlags)));
  END_CPP11
}
// GDAL7_dataset.cpp
cpp11::strings GDAL7_dataset_get_projection(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_projection(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_projection(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
cpp11::strings GDAL7_dataset_get_projection_ref(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_projection_ref(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_projection_ref(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_set_projection(SEXP xp, std::string prj);
extern "C" SEXP _GDAL7_GDAL7_dataset_set_projection(SEXP xp, SEXP prj) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_set_projection(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(prj)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_get_gcpcount(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_gcpcount(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_gcpcount(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
cpp11::strings GDAL7_dataset_get_gcpprojection(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_gcpprojection(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_gcpprojection(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_flush_cache(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_flush_cache(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_flush_cache(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_add_band(SEXP xp, int datatype, cpp11::strings options);
extern "C" SEXP _GDAL7_GDAL7_dataset_add_band(SEXP xp, SEXP datatype, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_add_band(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(datatype), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(options)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_create_mask_band(SEXP xp, int nFlags);
extern "C" SEXP _GDAL7_GDAL7_dataset_create_mask_band(SEXP xp, SEXP nFlags) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_create_mask_band(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(nFlags)));
  END_CPP11
}
// GDAL7_dataset.cpp
cpp11::strings GDAL7_dataset_get_file_list(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_file_list(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_file_list(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
void GDAL7_dataset_reset_reading(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_reset_reading(SEXP xp) {
  BEGIN_CPP11
    GDAL7_dataset_reset_reading(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp));
    return R_NilValue;
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_get_layer_count(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_layer_count(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_layer_count(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_abort_sql(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_abort_sql(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_abort_sql(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_start_transaction(SEXP xp, int force);
extern "C" SEXP _GDAL7_GDAL7_dataset_start_transaction(SEXP xp, SEXP force) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_start_transaction(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(force)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_commit_transaction(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_commit_transaction(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_commit_transaction(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_rollback_transaction(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_rollback_transaction(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_rollback_transaction(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
void GDAL7_dataset_clear_statistics(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_clear_statistics(SEXP xp) {
  BEGIN_CPP11
    GDAL7_dataset_clear_statistics(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp));
    return R_NilValue;
  END_CPP11
}
// GDAL7_dataset.cpp
cpp11::strings GDAL7_dataset_get_field_domain_names(SEXP xp, cpp11::strings options);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_field_domain_names(SEXP xp, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_field_domain_names(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(options)));
  END_CPP11
}
// GDAL7_dataset.cpp
bool GDAL7_dataset_delete_field_domain(SEXP xp, std::string name);
extern "C" SEXP _GDAL7_GDAL7_dataset_delete_field_domain(SEXP xp, SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_delete_field_domain(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(name)));
  END_CPP11
}
// GDAL7_dataset.cpp
cpp11::strings GDAL7_dataset_get_relationship_names(SEXP xp, cpp11::strings options);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_relationship_names(SEXP xp, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_relationship_names(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(options)));
  END_CPP11
}
// GDAL7_dataset.cpp
bool GDAL7_dataset_delete_relationship(SEXP xp, std::string name);
extern "C" SEXP _GDAL7_GDAL7_dataset_delete_relationship(SEXP xp, SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_delete_relationship(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(name)));
  END_CPP11
}
// GDAL7_dataset.cpp
SEXP GDAL7_dataset_as_mdarray(SEXP xp, cpp11::strings options);
extern "C" SEXP _GDAL7_GDAL7_dataset_as_mdarray(SEXP xp, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_as_mdarray(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(options)));
  END_CPP11
}
// GDAL7_driver.cpp
cpp11::strings GDAL7_driver_get_short_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_driver_get_short_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_get_short_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_driver.cpp
cpp11::strings GDAL7_driver_get_long_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_driver_get_long_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_get_long_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_driver.cpp
cpp11::strings GDAL7_driver_get_help_topic(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_driver_get_help_topic(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_get_help_topic(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_driver.cpp
bool GDAL7_driver_has_open_option(SEXP xp, std::string option_name);
extern "C" SEXP _GDAL7_GDAL7_driver_has_open_option(SEXP xp, SEXP option_name) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_has_open_option(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(option_name)));
  END_CPP11
}
// GDAL7_driver.cpp
SEXP GDAL7_dataset_get_driver_ptr(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_driver_ptr(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_driver_ptr(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_driver.cpp
int GDAL7_get_driver_count();
extern "C" SEXP _GDAL7_GDAL7_get_driver_count() {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_get_driver_count());
  END_CPP11
}
// GDAL7_driver.cpp
SEXP GDAL7_get_driver_by_name(std::string name);
extern "C" SEXP _GDAL7_GDAL7_get_driver_by_name(SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_get_driver_by_name(cpp11::as_cpp<cpp11::decay_t<std::string>>(name)));
  END_CPP11
}
// GDAL7_driver.cpp
SEXP GDAL7_get_driver(int index);
extern "C" SEXP _GDAL7_GDAL7_get_driver(SEXP index) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_get_driver(cpp11::as_cpp<cpp11::decay_t<int>>(index)));
  END_CPP11
}
// GDAL7_driver.cpp
bool GDAL7_driver_test_capability(SEXP xp, std::string capability);
extern "C" SEXP _GDAL7_GDAL7_driver_test_capability(SEXP xp, SEXP capability) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_test_capability(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(capability)));
  END_CPP11
}
// GDAL7_driver.cpp
cpp11::strings GDAL7_driver_get_creation_options(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_driver_get_creation_options(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_get_creation_options(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_driver.cpp
cpp11::strings GDAL7_driver_get_metadata_item(SEXP xp, std::string name, std::string domain);
extern "C" SEXP _GDAL7_GDAL7_driver_get_metadata_item(SEXP xp, SEXP name, SEXP domain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_get_metadata_item(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(name), cpp11::as_cpp<cpp11::decay_t<std::string>>(domain)));
  END_CPP11
}
// GDAL7_info.cpp
SEXP GDAL7_dataset_get_band(SEXP xp, int nBand);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_band(SEXP xp, SEXP nBand) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_band(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(nBand)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_band_get_xsize(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_xsize(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_xsize(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_band_get_ysize(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_ysize(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_ysize(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_band_get_band_number(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_band_number(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_band_number(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_band_get_data_type(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_data_type(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_data_type(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
cpp11::strings GDAL7_band_get_data_type_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_data_type_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_data_type_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
cpp11::integers GDAL7_band_get_block_size(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_block_size(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_block_size(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
SEXP GDAL7_band_get_nodata_value(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_nodata_value(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_nodata_value(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
cpp11::strings GDAL7_band_get_description(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_description(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_description(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_band_get_color_interpretation(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_color_interpretation(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_color_interpretation(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
cpp11::strings GDAL7_band_get_color_interpretation_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_color_interpretation_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_color_interpretation_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
SEXP GDAL7_band_get_scale(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_scale(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_scale(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
SEXP GDAL7_band_get_offset(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_offset(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_offset(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
cpp11::strings GDAL7_band_get_unit_type(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_unit_type(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_unit_type(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_description(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_description(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_description(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_majorobject.cpp
void GDAL7_majorobject_set_description(SEXP xp, std::string pszNewDesc);
extern "C" SEXP _GDAL7_GDAL7_majorobject_set_description(SEXP xp, SEXP pszNewDesc) {
  BEGIN_CPP11
    GDAL7_majorobject_set_description(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszNewDesc));
    return R_NilValue;
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_metadata_domain_list(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_metadata_domain_list(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_metadata_domain_list(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_metadata_dict(SEXP xp, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_metadata_dict(SEXP xp, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_metadata_dict(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_metadata_list(SEXP xp, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_metadata_list(SEXP xp, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_metadata_list(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
int GDAL7_majorobject_set_metadata(SEXP xp, cpp11::list papszMetadata, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_set_metadata(SEXP xp, SEXP papszMetadata, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_set_metadata(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(papszMetadata), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
int GDAL7_majorobject_set_metadata_2(SEXP xp, std::string pszMetadataString, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_set_metadata_2(SEXP xp, SEXP pszMetadataString, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_set_metadata_2(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszMetadataString), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_metadata_item(SEXP xp, std::string pszName, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_metadata_item(SEXP xp, SEXP pszName, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_metadata_item(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszName), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
int GDAL7_majorobject_set_metadata_item(SEXP xp, std::string pszName, std::string pszValue, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_set_metadata_item(SEXP xp, SEXP pszName, SEXP pszValue, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_set_metadata_item(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszName), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszValue), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_dataset_get_root_group(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_root_group(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_root_group(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_group_get_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_group_get_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_get_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_group_get_full_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_group_get_full_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_get_full_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_group_get_mdarray_names(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_group_get_mdarray_names(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_get_mdarray_names(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_group_open_mdarray(SEXP xp, std::string name);
extern "C" SEXP _GDAL7_GDAL7_group_open_mdarray(SEXP xp, SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_open_mdarray(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(name)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_group_get_group_names(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_group_get_group_names(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_get_group_names(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_group_open_group(SEXP xp, std::string name);
extern "C" SEXP _GDAL7_GDAL7_group_open_group(SEXP xp, SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_open_group(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(name)));
  END_CPP11
}
// GDAL7_multidim.cpp
void GDAL7_group_release(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_group_release(SEXP xp) {
  BEGIN_CPP11
    GDAL7_group_release(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp));
    return R_NilValue;
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_mdarray_get_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_mdarray_get_full_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_full_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_full_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
int GDAL7_mdarray_get_dimension_count(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_dimension_count(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_dimension_count(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::list GDAL7_mdarray_get_dimensions(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_dimensions(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_dimensions(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::list GDAL7_mdarray_get_dimension_variables(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_dimension_variables(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_dimension_variables(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::list GDAL7_mdarray_get_coordinate_variables(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_coordinate_variables(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_coordinate_variables(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_mdarray_get_data_type_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_data_type_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_data_type_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_mdarray_get_unit(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_unit(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_unit(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_mdarray_get_nodata_value(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_nodata_value(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_nodata_value(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
void GDAL7_mdarray_release(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_release(SEXP xp) {
  BEGIN_CPP11
    GDAL7_mdarray_release(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp));
    return R_NilValue;
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::list GDAL7_mdarray_get_attributes(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_attributes(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_attributes(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::list GDAL7_group_get_attributes(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_group_get_attributes(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_get_attributes(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_mdarray_get_scale(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_scale(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_scale(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_mdarray_get_offset(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_offset(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_offset(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_mdarray_crs(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_crs(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_crs(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::doubles GDAL7_mdarray_read(SEXP xp, cpp11::doubles start, cpp11::doubles count, cpp11::doubles step);
extern "C" SEXP _GDAL7_GDAL7_mdarray_read(SEXP xp, SEXP start, SEXP count, SEXP step) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_read(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(start), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(count), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(step)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_mdarray_get_view(SEXP xp, std::string expr);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_view(SEXP xp, SEXP expr) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_view(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(expr)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_mdarray_as_classic_dataset(SEXP xp, double x_dim, double y_dim);
extern "C" SEXP _GDAL7_GDAL7_mdarray_as_classic_dataset(SEXP xp, SEXP x_dim, SEXP y_dim) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_as_classic_dataset(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<double>>(x_dim), cpp11::as_cpp<cpp11::decay_t<double>>(y_dim)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_group_open_mdarray_from_fullname(SEXP xp, std::string name);
extern "C" SEXP _GDAL7_GDAL7_group_open_mdarray_from_fullname(SEXP xp, SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_open_mdarray_from_fullname(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(name)));
  END_CPP11
}
// GDAL7_open.cpp
void GDAL7_init();
extern "C" SEXP _GDAL7_GDAL7_init() {
  BEGIN_CPP11
    GDAL7_init();
    return R_NilValue;
  END_CPP11
}
// GDAL7_open.cpp
SEXP GDAL7_gdal_open(std::string path, bool update, bool multidim);
extern "C" SEXP _GDAL7_GDAL7_gdal_open(SEXP path, SEXP update, SEXP multidim) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_gdal_open(cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<bool>>(update), cpp11::as_cpp<cpp11::decay_t<bool>>(multidim)));
  END_CPP11
}
// GDAL7_open.cpp
void GDAL7_close(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_close(SEXP xp) {
  BEGIN_CPP11
    GDAL7_close(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp));
    return R_NilValue;
  END_CPP11
}
// GDAL7_open.cpp
void GDAL7_emit_gdal_message(std::string level, std::string message);
extern "C" SEXP _GDAL7_GDAL7_emit_gdal_message(SEXP level, SEXP message) {
  BEGIN_CPP11
    GDAL7_emit_gdal_message(cpp11::as_cpp<cpp11::decay_t<std::string>>(level), cpp11::as_cpp<cpp11::decay_t<std::string>>(message));
    return R_NilValue;
  END_CPP11
}
// GDAL7_rasterio.cpp
SEXP GDAL7_dataset_get_geotransform(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_geotransform(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_geotransform(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_rasterio.cpp
void GDAL7_dataset_set_geotransform(SEXP xp, cpp11::doubles gt);
extern "C" SEXP _GDAL7_GDAL7_dataset_set_geotransform(SEXP xp, SEXP gt) {
  BEGIN_CPP11
    GDAL7_dataset_set_geotransform(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(gt));
    return R_NilValue;
  END_CPP11
}
// GDAL7_rasterio.cpp
cpp11::list GDAL7_apply_geotransform(cpp11::doubles gt, cpp11::doubles pixel, cpp11::doubles line);
extern "C" SEXP _GDAL7_GDAL7_apply_geotransform(SEXP gt, SEXP pixel, SEXP line) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_apply_geotransform(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(gt), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(pixel), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(line)));
  END_CPP11
}
// GDAL7_rasterio.cpp
SEXP GDAL7_inv_geotransform(cpp11::doubles gt);
extern "C" SEXP _GDAL7_GDAL7_inv_geotransform(SEXP gt) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_inv_geotransform(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(gt)));
  END_CPP11
}
// GDAL7_rasterio.cpp
int GDAL7_band_get_overview_count(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_overview_count(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_overview_count(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_rasterio.cpp
SEXP GDAL7_band_get_overview(SEXP xp, int index);
extern "C" SEXP _GDAL7_GDAL7_band_get_overview(SEXP xp, SEXP index) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_overview(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(index)));
  END_CPP11
}
// GDAL7_rasterio.cpp
cpp11::list GDAL7_band_get_overview_sizes(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_overview_sizes(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_overview_sizes(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_rasterio.cpp
cpp11::doubles GDAL7_band_read(SEXP xp, cpp11::doubles window, cpp11::integers out_size, std::string resample);
extern "C" SEXP _GDAL7_GDAL7_band_read(SEXP xp, SEXP window, SEXP out_size, SEXP resample) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_read(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(window), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(out_size), cpp11::as_cpp<cpp11::decay_t<std::string>>(resample)));
  END_CPP11
}
// GDAL7_rasterio.cpp
cpp11::list GDAL7_dataset_read(SEXP xp, cpp11::integers bands, cpp11::doubles window, cpp11::integers out_size, std::string resample);
extern "C" SEXP _GDAL7_GDAL7_dataset_read(SEXP xp, SEXP bands, SEXP window, SEXP out_size, SEXP resample) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_read(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(bands), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(window), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(out_size), cpp11::as_cpp<cpp11::decay_t<std::string>>(resample)));
  END_CPP11
}
// GDAL7_summary.cpp
cpp11::integers GDAL7_data_types();
extern "C" SEXP _GDAL7_GDAL7_data_types() {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_data_types());
  END_CPP11
}
// GDAL7_summary.cpp
cpp11::integers GDAL7_color_interpretations();
extern "C" SEXP _GDAL7_GDAL7_color_interpretations() {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_color_interpretations());
  END_CPP11
}
// GDAL7_summary.cpp
cpp11::list GDAL7_dataset_summary(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_summary(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_summary(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_vector.cpp
strings GDAL7_dataset_layer_names(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_layer_names(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_layer_names(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_vector.cpp
SEXP GDAL7_dataset_layer(SEXP xp, int index);
extern "C" SEXP _GDAL7_GDAL7_dataset_layer(SEXP xp, SEXP index) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_layer(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(index)));
  END_CPP11
}
// GDAL7_vector.cpp
SEXP GDAL7_dataset_layer_by_name(SEXP xp, std::string name);
extern "C" SEXP _GDAL7_GDAL7_dataset_layer_by_name(SEXP xp, SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_layer_by_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(name)));
  END_CPP11
}
// GDAL7_vector.cpp
SEXP GDAL7_dataset_execute_sql(SEXP xp, std::string sql, strings dialect);
extern "C" SEXP _GDAL7_GDAL7_dataset_execute_sql(SEXP xp, SEXP sql, SEXP dialect) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_execute_sql(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(sql), cpp11::as_cpp<cpp11::decay_t<strings>>(dialect)));
  END_CPP11
}
// GDAL7_vector.cpp
strings GDAL7_layer_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_layer_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_layer_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_vector.cpp
double GDAL7_layer_feature_count(SEXP xp, bool force);
extern "C" SEXP _GDAL7_GDAL7_layer_feature_count(SEXP xp, SEXP force) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_layer_feature_count(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<bool>>(force)));
  END_CPP11
}
// GDAL7_vector.cpp
strings GDAL7_layer_geometry_type(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_layer_geometry_type(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_layer_geometry_type(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_vector.cpp
strings GDAL7_layer_crs(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_layer_crs(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_layer_crs(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_vector.cpp
bool GDAL7_layer_test_capability(SEXP xp, std::string capability);
extern "C" SEXP _GDAL7_GDAL7_layer_test_capability(SEXP xp, SEXP capability) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_layer_test_capability(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(capability)));
  END_CPP11
}
// GDAL7_vector.cpp
doubles GDAL7_layer_extent(SEXP xp, bool force);
extern "C" SEXP _GDAL7_GDAL7_layer_extent(SEXP xp, SEXP force) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_layer_extent(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<bool>>(force)));
  END_CPP11
}
// GDAL7_vector.cpp
void GDAL7_layer_set_attribute_filter(SEXP xp, strings where);
extern "C" SEXP _GDAL7_GDAL7_layer_set_attribute_filter(SEXP xp, SEXP where) {
  BEGIN_CPP11
    GDAL7_layer_set_attribute_filter(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<strings>>(where));
    return R_NilValue;
  END_CPP11
}
// GDAL7_vector.cpp
void GDAL7_layer_set_spatial_filter(SEXP xp, doubles bbox);
extern "C" SEXP _GDAL7_GDAL7_layer_set_spatial_filter(SEXP xp, SEXP bbox) {
  BEGIN_CPP11
    GDAL7_layer_set_spatial_filter(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<doubles>>(bbox));
    return R_NilValue;
  END_CPP11
}
// GDAL7_vector.cpp
void GDAL7_layer_reset_reading(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_layer_reset_reading(SEXP xp) {
  BEGIN_CPP11
    GDAL7_layer_reset_reading(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp));
    return R_NilValue;
  END_CPP11
}
// GDAL7_vector.cpp
SEXP GDAL7_layer_arrow_stream(SEXP xp, strings options);
extern "C" SEXP _GDAL7_GDAL7_layer_arrow_stream(SEXP xp, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_layer_arrow_stream(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<strings>>(options)));
  END_CPP11
}
// GDAL7_vector.cpp
void GDAL7_release_arrow_stream(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_release_arrow_stream(SEXP xp) {
  BEGIN_CPP11
    GDAL7_release_arrow_stream(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp));
    return R_NilValue;
  END_CPP11
}
// GDAL7_vector.cpp
SEXP GDAL7_dataset_create_layer(SEXP xp, std::string name, strings crs, std::string geometry_type, strings options);
extern "C" SEXP _GDAL7_GDAL7_dataset_create_layer(SEXP xp, SEXP name, SEXP crs, SEXP geometry_type, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_create_layer(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(name), cpp11::as_cpp<cpp11::decay_t<strings>>(crs), cpp11::as_cpp<cpp11::decay_t<std::string>>(geometry_type), cpp11::as_cpp<cpp11::decay_t<strings>>(options)));
  END_CPP11
}
// GDAL7_vector.cpp
void GDAL7_layer_create_fields(SEXP xp, SEXP schema, strings skip, strings options);
extern "C" SEXP _GDAL7_GDAL7_layer_create_fields(SEXP xp, SEXP schema, SEXP skip, SEXP options) {
  BEGIN_CPP11
    GDAL7_layer_create_fields(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(schema), cpp11::as_cpp<cpp11::decay_t<strings>>(skip), cpp11::as_cpp<cpp11::decay_t<strings>>(options));
    return R_NilValue;
  END_CPP11
}
// GDAL7_vector.cpp
void GDAL7_layer_write_arrow_batch(SEXP xp, SEXP schema, SEXP array, strings options);
extern "C" SEXP _GDAL7_GDAL7_layer_write_arrow_batch(SEXP xp, SEXP schema, SEXP array, SEXP options) {
  BEGIN_CPP11
    GDAL7_layer_write_arrow_batch(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(schema), cpp11::as_cpp<cpp11::decay_t<SEXP>>(array), cpp11::as_cpp<cpp11::decay_t<strings>>(options));
    return R_NilValue;
  END_CPP11
}
// GDAL7_vector.cpp
SEXP GDAL7_create_vector_dataset(std::string driver_name, std::string path, strings options);
extern "C" SEXP _GDAL7_GDAL7_create_vector_dataset(SEXP driver_name, SEXP path, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_create_vector_dataset(cpp11::as_cpp<cpp11::decay_t<std::string>>(driver_name), cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<strings>>(options)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_GDAL7_GDAL7_apply_geotransform",                   (DL_FUNC) &_GDAL7_GDAL7_apply_geotransform,                   3},
    {"_GDAL7_GDAL7_band_get_band_number",                 (DL_FUNC) &_GDAL7_GDAL7_band_get_band_number,                 1},
    {"_GDAL7_GDAL7_band_get_block_size",                  (DL_FUNC) &_GDAL7_GDAL7_band_get_block_size,                  1},
    {"_GDAL7_GDAL7_band_get_color_interpretation",        (DL_FUNC) &_GDAL7_GDAL7_band_get_color_interpretation,        1},
    {"_GDAL7_GDAL7_band_get_color_interpretation_name",   (DL_FUNC) &_GDAL7_GDAL7_band_get_color_interpretation_name,   1},
    {"_GDAL7_GDAL7_band_get_data_type",                   (DL_FUNC) &_GDAL7_GDAL7_band_get_data_type,                   1},
    {"_GDAL7_GDAL7_band_get_data_type_name",              (DL_FUNC) &_GDAL7_GDAL7_band_get_data_type_name,              1},
    {"_GDAL7_GDAL7_band_get_description",                 (DL_FUNC) &_GDAL7_GDAL7_band_get_description,                 1},
    {"_GDAL7_GDAL7_band_get_nodata_value",                (DL_FUNC) &_GDAL7_GDAL7_band_get_nodata_value,                1},
    {"_GDAL7_GDAL7_band_get_offset",                      (DL_FUNC) &_GDAL7_GDAL7_band_get_offset,                      1},
    {"_GDAL7_GDAL7_band_get_overview",                    (DL_FUNC) &_GDAL7_GDAL7_band_get_overview,                    2},
    {"_GDAL7_GDAL7_band_get_overview_count",              (DL_FUNC) &_GDAL7_GDAL7_band_get_overview_count,              1},
    {"_GDAL7_GDAL7_band_get_overview_sizes",              (DL_FUNC) &_GDAL7_GDAL7_band_get_overview_sizes,              1},
    {"_GDAL7_GDAL7_band_get_scale",                       (DL_FUNC) &_GDAL7_GDAL7_band_get_scale,                       1},
    {"_GDAL7_GDAL7_band_get_unit_type",                   (DL_FUNC) &_GDAL7_GDAL7_band_get_unit_type,                   1},
    {"_GDAL7_GDAL7_band_get_xsize",                       (DL_FUNC) &_GDAL7_GDAL7_band_get_xsize,                       1},
    {"_GDAL7_GDAL7_band_get_ysize",                       (DL_FUNC) &_GDAL7_GDAL7_band_get_ysize,                       1},
    {"_GDAL7_GDAL7_band_read",                            (DL_FUNC) &_GDAL7_GDAL7_band_read,                            4},
    {"_GDAL7_GDAL7_capabilities",                         (DL_FUNC) &_GDAL7_GDAL7_capabilities,                         0},
    {"_GDAL7_GDAL7_close",                                (DL_FUNC) &_GDAL7_GDAL7_close,                                1},
    {"_GDAL7_GDAL7_color_interpretations",                (DL_FUNC) &_GDAL7_GDAL7_color_interpretations,                0},
    {"_GDAL7_GDAL7_create_vector_dataset",                (DL_FUNC) &_GDAL7_GDAL7_create_vector_dataset,                3},
    {"_GDAL7_GDAL7_data_types",                           (DL_FUNC) &_GDAL7_GDAL7_data_types,                           0},
    {"_GDAL7_GDAL7_dataset_abort_sql",                    (DL_FUNC) &_GDAL7_GDAL7_dataset_abort_sql,                    1},
    {"_GDAL7_GDAL7_dataset_add_band",                     (DL_FUNC) &_GDAL7_GDAL7_dataset_add_band,                     3},
    {"_GDAL7_GDAL7_dataset_as_mdarray",                   (DL_FUNC) &_GDAL7_GDAL7_dataset_as_mdarray,                   2},
    {"_GDAL7_GDAL7_dataset_clear_statistics",             (DL_FUNC) &_GDAL7_GDAL7_dataset_clear_statistics,             1},
    {"_GDAL7_GDAL7_dataset_commit_transaction",           (DL_FUNC) &_GDAL7_GDAL7_dataset_commit_transaction,           1},
    {"_GDAL7_GDAL7_dataset_create_layer",                 (DL_FUNC) &_GDAL7_GDAL7_dataset_create_layer,                 5},
    {"_GDAL7_GDAL7_dataset_create_mask_band",             (DL_FUNC) &_GDAL7_GDAL7_dataset_create_mask_band,             2},
    {"_GDAL7_GDAL7_dataset_delete_field_domain",          (DL_FUNC) &_GDAL7_GDAL7_dataset_delete_field_domain,          2},
    {"_GDAL7_GDAL7_dataset_delete_relationship",          (DL_FUNC) &_GDAL7_GDAL7_dataset_delete_relationship,          2},
    {"_GDAL7_GDAL7_dataset_execute_sql",                  (DL_FUNC) &_GDAL7_GDAL7_dataset_execute_sql,                  3},
    {"_GDAL7_GDAL7_dataset_flush_cache",                  (DL_FUNC) &_GDAL7_GDAL7_dataset_flush_cache,                  1},
    {"_GDAL7_GDAL7_dataset_get_band",                     (DL_FUNC) &_GDAL7_GDAL7_dataset_get_band,                     2},
    {"_GDAL7_GDAL7_dataset_get_close_reports_progress",   (DL_FUNC) &_GDAL7_GDAL7_dataset_get_close_reports_progress,   1},
    {"_GDAL7_GDAL7_dataset_get_driver_ptr",               (DL_FUNC) &_GDAL7_GDAL7_dataset_get_driver_ptr,               1},
    {"_GDAL7_GDAL7_dataset_get_field_domain_names",       (DL_FUNC) &_GDAL7_GDAL7_dataset_get_field_domain_names,       2},
    {"_GDAL7_GDAL7_dataset_get_file_list",                (DL_FUNC) &_GDAL7_GDAL7_dataset_get_file_list,                1},
    {"_GDAL7_GDAL7_dataset_get_gcpcount",                 (DL_FUNC) &_GDAL7_GDAL7_dataset_get_gcpcount,                 1},
    {"_GDAL7_GDAL7_dataset_get_gcpprojection",            (DL_FUNC) &_GDAL7_GDAL7_dataset_get_gcpprojection,            1},
    {"_GDAL7_GDAL7_dataset_get_geotransform",             (DL_FUNC) &_GDAL7_GDAL7_dataset_get_geotransform,             1},
    {"_GDAL7_GDAL7_dataset_get_layer_count",              (DL_FUNC) &_GDAL7_GDAL7_dataset_get_layer_count,              1},
    {"_GDAL7_GDAL7_dataset_get_projection",               (DL_FUNC) &_GDAL7_GDAL7_dataset_get_projection,               1},
    {"_GDAL7_GDAL7_dataset_get_projection_ref",           (DL_FUNC) &_GDAL7_GDAL7_dataset_get_projection_ref,           1},
    {"_GDAL7_GDAL7_dataset_get_relationship_names",       (DL_FUNC) &_GDAL7_GDAL7_dataset_get_relationship_names,       2},
    {"_GDAL7_GDAL7_dataset_get_root_group",               (DL_FUNC) &_GDAL7_GDAL7_dataset_get_root_group,               1},
    {"_GDAL7_GDAL7_dataset_get_thread_safe_dataset",      (DL_FUNC) &_GDAL7_GDAL7_dataset_get_thread_safe_dataset,      2},
    {"_GDAL7_GDAL7_dataset_is_thread_safe",               (DL_FUNC) &_GDAL7_GDAL7_dataset_is_thread_safe,               2},
    {"_GDAL7_GDAL7_dataset_layer",                        (DL_FUNC) &_GDAL7_GDAL7_dataset_layer,                        2},
    {"_GDAL7_GDAL7_dataset_layer_by_name",                (DL_FUNC) &_GDAL7_GDAL7_dataset_layer_by_name,                2},
    {"_GDAL7_GDAL7_dataset_layer_names",                  (DL_FUNC) &_GDAL7_GDAL7_dataset_layer_names,                  1},
    {"_GDAL7_GDAL7_dataset_mark_suppress_on_close",       (DL_FUNC) &_GDAL7_GDAL7_dataset_mark_suppress_on_close,       1},
    {"_GDAL7_GDAL7_dataset_raster_count",                 (DL_FUNC) &_GDAL7_GDAL7_dataset_raster_count,                 1},
    {"_GDAL7_GDAL7_dataset_raster_xsize",                 (DL_FUNC) &_GDAL7_GDAL7_dataset_raster_xsize,                 1},
    {"_GDAL7_GDAL7_dataset_raster_ysize",                 (DL_FUNC) &_GDAL7_GDAL7_dataset_raster_ysize,                 1},
    {"_GDAL7_GDAL7_dataset_read",                         (DL_FUNC) &_GDAL7_GDAL7_dataset_read,                         5},
    {"_GDAL7_GDAL7_dataset_reset_reading",                (DL_FUNC) &_GDAL7_GDAL7_dataset_reset_reading,                1},
    {"_GDAL7_GDAL7_dataset_rollback_transaction",         (DL_FUNC) &_GDAL7_GDAL7_dataset_rollback_transaction,         1},
    {"_GDAL7_GDAL7_dataset_set_geotransform",             (DL_FUNC) &_GDAL7_GDAL7_dataset_set_geotransform,             2},
    {"_GDAL7_GDAL7_dataset_set_projection",               (DL_FUNC) &_GDAL7_GDAL7_dataset_set_projection,               2},
    {"_GDAL7_GDAL7_dataset_start_transaction",            (DL_FUNC) &_GDAL7_GDAL7_dataset_start_transaction,            2},
    {"_GDAL7_GDAL7_dataset_summary",                      (DL_FUNC) &_GDAL7_GDAL7_dataset_summary,                      1},
    {"_GDAL7_GDAL7_driver_get_creation_options",          (DL_FUNC) &_GDAL7_GDAL7_driver_get_creation_options,          1},
    {"_GDAL7_GDAL7_driver_get_help_topic",                (DL_FUNC) &_GDAL7_GDAL7_driver_get_help_topic,                1},
    {"_GDAL7_GDAL7_driver_get_long_name",                 (DL_FUNC) &_GDAL7_GDAL7_driver_get_long_name,                 1},
    {"_GDAL7_GDAL7_driver_get_metadata_item",             (DL_FUNC) &_GDAL7_GDAL7_driver_get_metadata_item,             3},
    {"_GDAL7_GDAL7_driver_get_short_name",                (DL_FUNC) &_GDAL7_GDAL7_driver_get_short_name,                1},
    {"_GDAL7_GDAL7_driver_has_open_option",               (DL_FUNC) &_GDAL7_GDAL7_driver_has_open_option,               2},
    {"_GDAL7_GDAL7_driver_test_capability",               (DL_FUNC) &_GDAL7_GDAL7_driver_test_capability,               2},
    {"_GDAL7_GDAL7_emit_gdal_message",                    (DL_FUNC) &_GDAL7_GDAL7_emit_gdal_message,                    2},
    {"_GDAL7_GDAL7_gdal_open",                            (DL_FUNC) &_GDAL7_GDAL7_gdal_open,                            3},
    {"_GDAL7_GDAL7_gdal_version",                         (DL_FUNC) &_GDAL7_GDAL7_gdal_version,                         0},
    {"_GDAL7_GDAL7_get_driver",                           (DL_FUNC) &_GDAL7_GDAL7_get_driver,                           1},
    {"_GDAL7_GDAL7_get_driver_by_name",                   (DL_FUNC) &_GDAL7_GDAL7_get_driver_by_name,                   1},
    {"_GDAL7_GDAL7_get_driver_count",                     (DL_FUNC) &_GDAL7_GDAL7_get_driver_count,                     0},
    {"_GDAL7_GDAL7_group_get_attributes",                 (DL_FUNC) &_GDAL7_GDAL7_group_get_attributes,                 1},
    {"_GDAL7_GDAL7_group_get_full_name",                  (DL_FUNC) &_GDAL7_GDAL7_group_get_full_name,                  1},
    {"_GDAL7_GDAL7_group_get_group_names",                (DL_FUNC) &_GDAL7_GDAL7_group_get_group_names,                1},
    {"_GDAL7_GDAL7_group_get_mdarray_names",              (DL_FUNC) &_GDAL7_GDAL7_group_get_mdarray_names,              1},
    {"_GDAL7_GDAL7_group_get_name",                       (DL_FUNC) &_GDAL7_GDAL7_group_get_name,                       1},
    {"_GDAL7_GDAL7_group_open_group",                     (DL_FUNC) &_GDAL7_GDAL7_group_open_group,                     2},
    {"_GDAL7_GDAL7_group_open_mdarray",                   (DL_FUNC) &_GDAL7_GDAL7_group_open_mdarray,                   2},
    {"_GDAL7_GDAL7_group_open_mdarray_from_fullname",     (DL_FUNC) &_GDAL7_GDAL7_group_open_mdarray_from_fullname,     2},
    {"_GDAL7_GDAL7_group_release",                        (DL_FUNC) &_GDAL7_GDAL7_group_release,                        1},
    {"_GDAL7_GDAL7_init",                                 (DL_FUNC) &_GDAL7_GDAL7_init,                                 0},
    {"_GDAL7_GDAL7_integer_constants",                    (DL_FUNC) &_GDAL7_GDAL7_integer_constants,                    0},
    {"_GDAL7_GDAL7_inv_geotransform",                     (DL_FUNC) &_GDAL7_GDAL7_inv_geotransform,                     1},
    {"_GDAL7_GDAL7_layer_arrow_stream",                   (DL_FUNC) &_GDAL7_GDAL7_layer_arrow_stream,                   2},
    {"_GDAL7_GDAL7_layer_create_fields",                  (DL_FUNC) &_GDAL7_GDAL7_layer_create_fields,                  4},
    {"_GDAL7_GDAL7_layer_crs",                            (DL_FUNC) &_GDAL7_GDAL7_layer_crs,                            1},
    {"_GDAL7_GDAL7_layer_extent",                         (DL_FUNC) &_GDAL7_GDAL7_layer_extent,                         2},
    {"_GDAL7_GDAL7_layer_feature_count",                  (DL_FUNC) &_GDAL7_GDAL7_layer_feature_count,                  2},
    {"_GDAL7_GDAL7_layer_geometry_type",                  (DL_FUNC) &_GDAL7_GDAL7_layer_geometry_type,                  1},
    {"_GDAL7_GDAL7_layer_name",                           (DL_FUNC) &_GDAL7_GDAL7_layer_name,                           1},
    {"_GDAL7_GDAL7_layer_reset_reading",                  (DL_FUNC) &_GDAL7_GDAL7_layer_reset_reading,                  1},
    {"_GDAL7_GDAL7_layer_set_attribute_filter",           (DL_FUNC) &_GDAL7_GDAL7_layer_set_attribute_filter,           2},
    {"_GDAL7_GDAL7_layer_set_spatial_filter",             (DL_FUNC) &_GDAL7_GDAL7_layer_set_spatial_filter,             2},
    {"_GDAL7_GDAL7_layer_test_capability",                (DL_FUNC) &_GDAL7_GDAL7_layer_test_capability,                2},
    {"_GDAL7_GDAL7_layer_write_arrow_batch",              (DL_FUNC) &_GDAL7_GDAL7_layer_write_arrow_batch,              4},
    {"_GDAL7_GDAL7_majorobject_get_description",          (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_description,          1},
    {"_GDAL7_GDAL7_majorobject_get_metadata_dict",        (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_metadata_dict,        2},
    {"_GDAL7_GDAL7_majorobject_get_metadata_domain_list", (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_metadata_domain_list, 1},
    {"_GDAL7_GDAL7_majorobject_get_metadata_item",        (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_metadata_item,        3},
    {"_GDAL7_GDAL7_majorobject_get_metadata_list",        (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_metadata_list,        2},
    {"_GDAL7_GDAL7_majorobject_set_description",          (DL_FUNC) &_GDAL7_GDAL7_majorobject_set_description,          2},
    {"_GDAL7_GDAL7_majorobject_set_metadata",             (DL_FUNC) &_GDAL7_GDAL7_majorobject_set_metadata,             3},
    {"_GDAL7_GDAL7_majorobject_set_metadata_2",           (DL_FUNC) &_GDAL7_GDAL7_majorobject_set_metadata_2,           3},
    {"_GDAL7_GDAL7_majorobject_set_metadata_item",        (DL_FUNC) &_GDAL7_GDAL7_majorobject_set_metadata_item,        4},
    {"_GDAL7_GDAL7_mdarray_as_classic_dataset",           (DL_FUNC) &_GDAL7_GDAL7_mdarray_as_classic_dataset,           3},
    {"_GDAL7_GDAL7_mdarray_crs",                          (DL_FUNC) &_GDAL7_GDAL7_mdarray_crs,                          1},
    {"_GDAL7_GDAL7_mdarray_get_attributes",               (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_attributes,               1},
    {"_GDAL7_GDAL7_mdarray_get_coordinate_variables",     (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_coordinate_variables,     1},
    {"_GDAL7_GDAL7_mdarray_get_data_type_name",           (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_data_type_name,           1},
    {"_GDAL7_GDAL7_mdarray_get_dimension_count",          (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_dimension_count,          1},
    {"_GDAL7_GDAL7_mdarray_get_dimension_variables",      (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_dimension_variables,      1},
    {"_GDAL7_GDAL7_mdarray_get_dimensions",               (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_dimensions,               1},
    {"_GDAL7_GDAL7_mdarray_get_full_name",                (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_full_name,                1},
    {"_GDAL7_GDAL7_mdarray_get_name",                     (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_name,                     1},
    {"_GDAL7_GDAL7_mdarray_get_nodata_value",             (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_nodata_value,             1},
    {"_GDAL7_GDAL7_mdarray_get_offset",                   (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_offset,                   1},
    {"_GDAL7_GDAL7_mdarray_get_scale",                    (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_scale,                    1},
    {"_GDAL7_GDAL7_mdarray_get_unit",                     (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_unit,                     1},
    {"_GDAL7_GDAL7_mdarray_get_view",                     (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_view,                     2},
    {"_GDAL7_GDAL7_mdarray_read",                         (DL_FUNC) &_GDAL7_GDAL7_mdarray_read,                         4},
    {"_GDAL7_GDAL7_mdarray_release",                      (DL_FUNC) &_GDAL7_GDAL7_mdarray_release,                      1},
    {"_GDAL7_GDAL7_release_arrow_stream",                 (DL_FUNC) &_GDAL7_GDAL7_release_arrow_stream,                 1},
    {"_GDAL7_GDAL7_string_constants",                     (DL_FUNC) &_GDAL7_GDAL7_string_constants,                     0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_GDAL7(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
