// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// GDAL7_dataset.cpp
SEXP GDAL7_dataset_get_driver(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_driver(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_driver(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
SEXP GDAL7_dataset_get_raster_band(SEXP xp, int nBand);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_raster_band(SEXP xp, SEXP nBand) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_raster_band(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(nBand)));
  END_CPP11
}
// GDAL7_dataset.cpp
cpp11::strings GDAL7_dataset_get_projection(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_projection(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_projection(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
cpp11::strings GDAL7_dataset_get_projection_ref(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_projection_ref(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_projection_ref(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
SEXP GDAL7_dataset_get_spatial_ref(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_spatial_ref(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_spatial_ref(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_get_gcpcount(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_gcpcount(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_gcpcount(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
cpp11::strings GDAL7_dataset_get_gcpprojection(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_gcpprojection(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_gcpprojection(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_flush_cache(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_flush_cache(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_flush_cache(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
cpp11::strings GDAL7_dataset_get_file_list(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_file_list(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_file_list(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_dataset.cpp
int GDAL7_dataset_get_layer_count(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_layer_count(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_layer_count(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_driver.cpp
cpp11::strings GDAL7_driver_get_short_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_driver_get_short_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_get_short_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_driver.cpp
cpp11::strings GDAL7_driver_get_long_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_driver_get_long_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_get_long_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_driver.cpp
cpp11::strings GDAL7_driver_get_help_topic(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_driver_get_help_topic(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_get_help_topic(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_driver.cpp
bool GDAL7_driver_has_open_option(SEXP xp, std::string option_name);
extern "C" SEXP _GDAL7_GDAL7_driver_has_open_option(SEXP xp, SEXP option_name) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_has_open_option(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(option_name)));
  END_CPP11
}
// GDAL7_driver.cpp
SEXP GDAL7_dataset_get_driver_ptr(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_driver_ptr(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_driver_ptr(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_driver.cpp
int GDAL7_get_driver_count();
extern "C" SEXP _GDAL7_GDAL7_get_driver_count() {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_get_driver_count());
  END_CPP11
}
// GDAL7_driver.cpp
SEXP GDAL7_get_driver_by_name(std::string name);
extern "C" SEXP _GDAL7_GDAL7_get_driver_by_name(SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_get_driver_by_name(cpp11::as_cpp<cpp11::decay_t<std::string>>(name)));
  END_CPP11
}
// GDAL7_driver.cpp
SEXP GDAL7_get_driver(int index);
extern "C" SEXP _GDAL7_GDAL7_get_driver(SEXP index) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_get_driver(cpp11::as_cpp<cpp11::decay_t<int>>(index)));
  END_CPP11
}
// GDAL7_driver.cpp
bool GDAL7_driver_test_capability(SEXP xp, std::string capability);
extern "C" SEXP _GDAL7_GDAL7_driver_test_capability(SEXP xp, SEXP capability) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_test_capability(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(capability)));
  END_CPP11
}
// GDAL7_driver.cpp
cpp11::strings GDAL7_driver_get_creation_options(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_driver_get_creation_options(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_get_creation_options(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_driver.cpp
cpp11::strings GDAL7_driver_get_metadata_item(SEXP xp, std::string name, std::string domain);
extern "C" SEXP _GDAL7_GDAL7_driver_get_metadata_item(SEXP xp, SEXP name, SEXP domain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_driver_get_metadata_item(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(name), cpp11::as_cpp<cpp11::decay_t<std::string>>(domain)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_dataset_get_raster_xsize(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_raster_xsize(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_raster_xsize(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_dataset_get_raster_ysize(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_raster_ysize(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_raster_ysize(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_dataset_get_raster_count(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_raster_count(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_raster_count(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
SEXP GDAL7_dataset_get_band(SEXP xp, int nBand);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_band(SEXP xp, SEXP nBand) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_band(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<int>>(nBand)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_band_get_xsize(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_xsize(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_xsize(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_band_get_ysize(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_ysize(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_ysize(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_band_get_band_number(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_band_number(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_band_number(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_band_get_data_type(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_data_type(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_data_type(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
cpp11::strings GDAL7_band_get_data_type_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_data_type_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_data_type_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
cpp11::integers GDAL7_band_get_block_size(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_block_size(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_block_size(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
SEXP GDAL7_band_get_nodata_value(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_nodata_value(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_nodata_value(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
cpp11::strings GDAL7_band_get_description(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_description(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_description(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
int GDAL7_band_get_color_interpretation(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_color_interpretation(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_color_interpretation(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
cpp11::strings GDAL7_band_get_color_interpretation_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_color_interpretation_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_color_interpretation_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
SEXP GDAL7_band_get_scale(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_scale(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_scale(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
SEXP GDAL7_band_get_offset(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_offset(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_offset(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_info.cpp
cpp11::strings GDAL7_band_get_unit_type(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_band_get_unit_type(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_band_get_unit_type(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_description(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_description(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_description(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_majorobject.cpp
void GDAL7_majorobject_set_description(SEXP xp, std::string pszNewDesc);
extern "C" SEXP _GDAL7_GDAL7_majorobject_set_description(SEXP xp, SEXP pszNewDesc) {
  BEGIN_CPP11
    GDAL7_majorobject_set_description(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszNewDesc));
    return R_NilValue;
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_metadata_domain_list(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_metadata_domain_list(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_metadata_domain_list(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_metadata_dict(SEXP xp, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_metadata_dict(SEXP xp, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_metadata_dict(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_metadata_list(SEXP xp, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_metadata_list(SEXP xp, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_metadata_list(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
int GDAL7_majorobject_set_metadata(SEXP xp, cpp11::list papszMetadata, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_set_metadata(SEXP xp, SEXP papszMetadata, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_set_metadata(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(papszMetadata), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
int GDAL7_majorobject_set_metadata_2(SEXP xp, std::string pszMetadataString, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_set_metadata_2(SEXP xp, SEXP pszMetadataString, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_set_metadata_2(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszMetadataString), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
cpp11::strings GDAL7_majorobject_get_metadata_item(SEXP xp, std::string pszName, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_get_metadata_item(SEXP xp, SEXP pszName, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_get_metadata_item(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszName), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_majorobject.cpp
int GDAL7_majorobject_set_metadata_item(SEXP xp, std::string pszName, std::string pszValue, std::string pszDomain);
extern "C" SEXP _GDAL7_GDAL7_majorobject_set_metadata_item(SEXP xp, SEXP pszName, SEXP pszValue, SEXP pszDomain) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_majorobject_set_metadata_item(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszName), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszValue), cpp11::as_cpp<cpp11::decay_t<std::string>>(pszDomain)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_dataset_get_root_group(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_dataset_get_root_group(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_dataset_get_root_group(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_group_get_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_group_get_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_get_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_group_get_full_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_group_get_full_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_get_full_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_group_get_mdarray_names(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_group_get_mdarray_names(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_get_mdarray_names(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_group_open_mdarray(SEXP xp, std::string name);
extern "C" SEXP _GDAL7_GDAL7_group_open_mdarray(SEXP xp, SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_open_mdarray(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(name)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_group_get_group_names(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_group_get_group_names(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_get_group_names(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_group_open_group(SEXP xp, std::string name);
extern "C" SEXP _GDAL7_GDAL7_group_open_group(SEXP xp, SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_group_open_group(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp), cpp11::as_cpp<cpp11::decay_t<std::string>>(name)));
  END_CPP11
}
// GDAL7_multidim.cpp
void GDAL7_group_release(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_group_release(SEXP xp) {
  BEGIN_CPP11
    GDAL7_group_release(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp));
    return R_NilValue;
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_mdarray_get_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_mdarray_get_full_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_full_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_full_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
int GDAL7_mdarray_get_dimension_count(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_dimension_count(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_dimension_count(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::list GDAL7_mdarray_get_dimensions(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_dimensions(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_dimensions(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_mdarray_get_data_type_name(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_data_type_name(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_data_type_name(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
cpp11::strings GDAL7_mdarray_get_unit(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_unit(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_unit(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
SEXP GDAL7_mdarray_get_nodata_value(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_get_nodata_value(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_mdarray_get_nodata_value(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}
// GDAL7_multidim.cpp
void GDAL7_mdarray_release(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_mdarray_release(SEXP xp) {
  BEGIN_CPP11
    GDAL7_mdarray_release(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp));
    return R_NilValue;
  END_CPP11
}
// GDAL7_open.cpp
void GDAL7_init();
extern "C" SEXP _GDAL7_GDAL7_init() {
  BEGIN_CPP11
    GDAL7_init();
    return R_NilValue;
  END_CPP11
}
// GDAL7_open.cpp
SEXP GDAL7_gdal_open(std::string path, bool update, bool multidim);
extern "C" SEXP _GDAL7_GDAL7_gdal_open(SEXP path, SEXP update, SEXP multidim) {
  BEGIN_CPP11
    return cpp11::as_sexp(GDAL7_gdal_open(cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<bool>>(update), cpp11::as_cpp<cpp11::decay_t<bool>>(multidim)));
  END_CPP11
}
// GDAL7_open.cpp
void GDAL7_close(SEXP xp);
extern "C" SEXP _GDAL7_GDAL7_close(SEXP xp) {
  BEGIN_CPP11
    GDAL7_close(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp));
    return R_NilValue;
  END_CPP11
}
// GDAL7_open.cpp
void GDAL7_emit_gdal_message(std::string level, std::string message);
extern "C" SEXP _GDAL7_GDAL7_emit_gdal_message(SEXP level, SEXP message) {
  BEGIN_CPP11
    GDAL7_emit_gdal_message(cpp11::as_cpp<cpp11::decay_t<std::string>>(level), cpp11::as_cpp<cpp11::decay_t<std::string>>(message));
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_GDAL7_GDAL7_band_get_band_number",                 (DL_FUNC) &_GDAL7_GDAL7_band_get_band_number,                 1},
    {"_GDAL7_GDAL7_band_get_block_size",                  (DL_FUNC) &_GDAL7_GDAL7_band_get_block_size,                  1},
    {"_GDAL7_GDAL7_band_get_color_interpretation",        (DL_FUNC) &_GDAL7_GDAL7_band_get_color_interpretation,        1},
    {"_GDAL7_GDAL7_band_get_color_interpretation_name",   (DL_FUNC) &_GDAL7_GDAL7_band_get_color_interpretation_name,   1},
    {"_GDAL7_GDAL7_band_get_data_type",                   (DL_FUNC) &_GDAL7_GDAL7_band_get_data_type,                   1},
    {"_GDAL7_GDAL7_band_get_data_type_name",              (DL_FUNC) &_GDAL7_GDAL7_band_get_data_type_name,              1},
    {"_GDAL7_GDAL7_band_get_description",                 (DL_FUNC) &_GDAL7_GDAL7_band_get_description,                 1},
    {"_GDAL7_GDAL7_band_get_nodata_value",                (DL_FUNC) &_GDAL7_GDAL7_band_get_nodata_value,                1},
    {"_GDAL7_GDAL7_band_get_offset",                      (DL_FUNC) &_GDAL7_GDAL7_band_get_offset,                      1},
    {"_GDAL7_GDAL7_band_get_scale",                       (DL_FUNC) &_GDAL7_GDAL7_band_get_scale,                       1},
    {"_GDAL7_GDAL7_band_get_unit_type",                   (DL_FUNC) &_GDAL7_GDAL7_band_get_unit_type,                   1},
    {"_GDAL7_GDAL7_band_get_xsize",                       (DL_FUNC) &_GDAL7_GDAL7_band_get_xsize,                       1},
    {"_GDAL7_GDAL7_band_get_ysize",                       (DL_FUNC) &_GDAL7_GDAL7_band_get_ysize,                       1},
    {"_GDAL7_GDAL7_close",                                (DL_FUNC) &_GDAL7_GDAL7_close,                                1},
    {"_GDAL7_GDAL7_dataset_flush_cache",                  (DL_FUNC) &_GDAL7_GDAL7_dataset_flush_cache,                  1},
    {"_GDAL7_GDAL7_dataset_get_band",                     (DL_FUNC) &_GDAL7_GDAL7_dataset_get_band,                     2},
    {"_GDAL7_GDAL7_dataset_get_driver",                   (DL_FUNC) &_GDAL7_GDAL7_dataset_get_driver,                   1},
    {"_GDAL7_GDAL7_dataset_get_driver_ptr",               (DL_FUNC) &_GDAL7_GDAL7_dataset_get_driver_ptr,               1},
    {"_GDAL7_GDAL7_dataset_get_file_list",                (DL_FUNC) &_GDAL7_GDAL7_dataset_get_file_list,                1},
    {"_GDAL7_GDAL7_dataset_get_gcpcount",                 (DL_FUNC) &_GDAL7_GDAL7_dataset_get_gcpcount,                 1},
    {"_GDAL7_GDAL7_dataset_get_gcpprojection",            (DL_FUNC) &_GDAL7_GDAL7_dataset_get_gcpprojection,            1},
    {"_GDAL7_GDAL7_dataset_get_layer_count",              (DL_FUNC) &_GDAL7_GDAL7_dataset_get_layer_count,              1},
    {"_GDAL7_GDAL7_dataset_get_projection",               (DL_FUNC) &_GDAL7_GDAL7_dataset_get_projection,               1},
    {"_GDAL7_GDAL7_dataset_get_projection_ref",           (DL_FUNC) &_GDAL7_GDAL7_dataset_get_projection_ref,           1},
    {"_GDAL7_GDAL7_dataset_get_raster_band",              (DL_FUNC) &_GDAL7_GDAL7_dataset_get_raster_band,              2},
    {"_GDAL7_GDAL7_dataset_get_raster_count",             (DL_FUNC) &_GDAL7_GDAL7_dataset_get_raster_count,             1},
    {"_GDAL7_GDAL7_dataset_get_raster_xsize",             (DL_FUNC) &_GDAL7_GDAL7_dataset_get_raster_xsize,             1},
    {"_GDAL7_GDAL7_dataset_get_raster_ysize",             (DL_FUNC) &_GDAL7_GDAL7_dataset_get_raster_ysize,             1},
    {"_GDAL7_GDAL7_dataset_get_root_group",               (DL_FUNC) &_GDAL7_GDAL7_dataset_get_root_group,               1},
    {"_GDAL7_GDAL7_dataset_get_spatial_ref",              (DL_FUNC) &_GDAL7_GDAL7_dataset_get_spatial_ref,              1},
    {"_GDAL7_GDAL7_driver_get_creation_options",          (DL_FUNC) &_GDAL7_GDAL7_driver_get_creation_options,          1},
    {"_GDAL7_GDAL7_driver_get_help_topic",                (DL_FUNC) &_GDAL7_GDAL7_driver_get_help_topic,                1},
    {"_GDAL7_GDAL7_driver_get_long_name",                 (DL_FUNC) &_GDAL7_GDAL7_driver_get_long_name,                 1},
    {"_GDAL7_GDAL7_driver_get_metadata_item",             (DL_FUNC) &_GDAL7_GDAL7_driver_get_metadata_item,             3},
    {"_GDAL7_GDAL7_driver_get_short_name",                (DL_FUNC) &_GDAL7_GDAL7_driver_get_short_name,                1},
    {"_GDAL7_GDAL7_driver_has_open_option",               (DL_FUNC) &_GDAL7_GDAL7_driver_has_open_option,               2},
    {"_GDAL7_GDAL7_driver_test_capability",               (DL_FUNC) &_GDAL7_GDAL7_driver_test_capability,               2},
    {"_GDAL7_GDAL7_emit_gdal_message",                    (DL_FUNC) &_GDAL7_GDAL7_emit_gdal_message,                    2},
    {"_GDAL7_GDAL7_gdal_open",                            (DL_FUNC) &_GDAL7_GDAL7_gdal_open,                            3},
    {"_GDAL7_GDAL7_get_driver",                           (DL_FUNC) &_GDAL7_GDAL7_get_driver,                           1},
    {"_GDAL7_GDAL7_get_driver_by_name",                   (DL_FUNC) &_GDAL7_GDAL7_get_driver_by_name,                   1},
    {"_GDAL7_GDAL7_get_driver_count",                     (DL_FUNC) &_GDAL7_GDAL7_get_driver_count,                     0},
    {"_GDAL7_GDAL7_group_get_full_name",                  (DL_FUNC) &_GDAL7_GDAL7_group_get_full_name,                  1},
    {"_GDAL7_GDAL7_group_get_group_names",                (DL_FUNC) &_GDAL7_GDAL7_group_get_group_names,                1},
    {"_GDAL7_GDAL7_group_get_mdarray_names",              (DL_FUNC) &_GDAL7_GDAL7_group_get_mdarray_names,              1},
    {"_GDAL7_GDAL7_group_get_name",                       (DL_FUNC) &_GDAL7_GDAL7_group_get_name,                       1},
    {"_GDAL7_GDAL7_group_open_group",                     (DL_FUNC) &_GDAL7_GDAL7_group_open_group,                     2},
    {"_GDAL7_GDAL7_group_open_mdarray",                   (DL_FUNC) &_GDAL7_GDAL7_group_open_mdarray,                   2},
    {"_GDAL7_GDAL7_group_release",                        (DL_FUNC) &_GDAL7_GDAL7_group_release,                        1},
    {"_GDAL7_GDAL7_init",                                 (DL_FUNC) &_GDAL7_GDAL7_init,                                 0},
    {"_GDAL7_GDAL7_majorobject_get_description",          (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_description,          1},
    {"_GDAL7_GDAL7_majorobject_get_metadata_dict",        (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_metadata_dict,        2},
    {"_GDAL7_GDAL7_majorobject_get_metadata_domain_list", (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_metadata_domain_list, 1},
    {"_GDAL7_GDAL7_majorobject_get_metadata_item",        (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_metadata_item,        3},
    {"_GDAL7_GDAL7_majorobject_get_metadata_list",        (DL_FUNC) &_GDAL7_GDAL7_majorobject_get_metadata_list,        2},
    {"_GDAL7_GDAL7_majorobject_set_description",          (DL_FUNC) &_GDAL7_GDAL7_majorobject_set_description,          2},
    {"_GDAL7_GDAL7_majorobject_set_metadata",             (DL_FUNC) &_GDAL7_GDAL7_majorobject_set_metadata,             3},
    {"_GDAL7_GDAL7_majorobject_set_metadata_2",           (DL_FUNC) &_GDAL7_GDAL7_majorobject_set_metadata_2,           3},
    {"_GDAL7_GDAL7_majorobject_set_metadata_item",        (DL_FUNC) &_GDAL7_GDAL7_majorobject_set_metadata_item,        4},
    {"_GDAL7_GDAL7_mdarray_get_data_type_name",           (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_data_type_name,           1},
    {"_GDAL7_GDAL7_mdarray_get_dimension_count",          (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_dimension_count,          1},
    {"_GDAL7_GDAL7_mdarray_get_dimensions",               (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_dimensions,               1},
    {"_GDAL7_GDAL7_mdarray_get_full_name",                (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_full_name,                1},
    {"_GDAL7_GDAL7_mdarray_get_name",                     (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_name,                     1},
    {"_GDAL7_GDAL7_mdarray_get_nodata_value",             (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_nodata_value,             1},
    {"_GDAL7_GDAL7_mdarray_get_unit",                     (DL_FUNC) &_GDAL7_GDAL7_mdarray_get_unit,                     1},
    {"_GDAL7_GDAL7_mdarray_release",                      (DL_FUNC) &_GDAL7_GDAL7_mdarray_release,                      1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_GDAL7(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
