// src/GDAL7_vsi.cpp
// Manual file - NOT generated by orchestrate.R
// GDAL's virtual file systems, and the configuration options that steer them.

#include <string>
#include <vector>

#include "gdal7.h"

namespace {

// VSI reports failure by return value and leaves the reason in errno, which
// means nothing to an R user. GDAL's own message, when there is one, says
// more; the path is added because VSI's often does not carry it.
[[noreturn]] void vsi_failed(gdal7::ErrorScope& err, const std::string& what,
                             const std::string& path) {
    err.stop(what + " " + path);
}

}  // namespace

// ============================================================================
// Reading the file system
// ============================================================================

// Every VSI path works here, not only files on disk: /vsimem/, /vsizip/,
// /vsicurl/ and the cloud prefixes all answer the same calls. A directory
// listing over /vsicurl/ is one request rather than a download.
[[cpp11::register]]
SEXP GDAL7_vsi_list(std::string path, int limit) {
    gdal7::ErrorScope err;
    char** entries = VSIReadDirEx(path.c_str(), limit);
    err.flush();

    if (entries == nullptr) {
        // Not an error: a path with nothing in it and a path that is not a
        // directory both answer this way, and the caller can tell which.
        return R_NilValue;
    }

    cpp11::strings out = gdal7::from_csl(entries);
    CSLDestroy(entries);
    return out;
}

[[cpp11::register]]
SEXP GDAL7_vsi_stat(std::string path) {
    VSIStatBufL info;

    gdal7::ErrorScope err;
    // Asking for the size and the nature of the file, but not the owner: over
    // a network file system the last of those is an extra request.
    const int status = VSIStatExL(path.c_str(), &info,
                                  VSI_STAT_EXISTS_FLAG | VSI_STAT_NATURE_FLAG |
                                      VSI_STAT_SIZE_FLAG);
    err.discard();

    if (status != 0) {
        return R_NilValue;
    }

    cpp11::writable::list out;
    out.push_back(cpp11::named_arg("size") = static_cast<double>(info.st_size));
    out.push_back(cpp11::named_arg("is_directory") =
                      VSI_ISDIR(info.st_mode) ? true : false);
    out.push_back(cpp11::named_arg("modified") =
                      static_cast<double>(info.st_mtime));
    return out;
}

[[cpp11::register]]
bool GDAL7_vsi_exists(std::string path) {
    VSIStatBufL info;
    gdal7::ErrorScope err;
    const bool found =
        VSIStatExL(path.c_str(), &info, VSI_STAT_EXISTS_FLAG) == 0;
    err.discard();
    return found;
}

// ============================================================================
// Changing the file system
// ============================================================================

[[cpp11::register]]
void GDAL7_vsi_unlink(std::string path) {
    gdal7::ErrorScope err;
    if (VSIUnlink(path.c_str()) != 0) {
        vsi_failed(err, "Could not delete", path);
    }
    err.flush();
}

[[cpp11::register]]
void GDAL7_vsi_mkdir(std::string path, int mode) {
    gdal7::ErrorScope err;
    if (VSIMkdir(path.c_str(), mode) != 0) {
        vsi_failed(err, "Could not create the directory", path);
    }
    err.flush();
}

[[cpp11::register]]
void GDAL7_vsi_rmdir(std::string path) {
    gdal7::ErrorScope err;
    if (VSIRmdir(path.c_str()) != 0) {
        vsi_failed(err, "Could not remove the directory", path);
    }
    err.flush();
}

[[cpp11::register]]
void GDAL7_vsi_rename(std::string from, std::string to) {
    gdal7::ErrorScope err;
    if (VSIRename(from.c_str(), to.c_str()) != 0) {
        vsi_failed(err, "Could not rename to", to);
    }
    err.flush();
}

[[cpp11::register]]
void GDAL7_vsi_copy(std::string from, std::string to) {
    gdal7::ErrorScope err;
    if (VSICopyFile(from.c_str(), to.c_str(), nullptr, static_cast<vsi_l_offset>(-1),
                    nullptr, nullptr, nullptr) != 0) {
        vsi_failed(err, "Could not copy to", to);
    }
    err.flush();
}

// ============================================================================
// Bytes in and out
// ============================================================================

// A whole VSI file as a raw vector. With /vsimem/ this is how a dataset built
// in memory leaves GDAL without ever being written to disk.
[[cpp11::register]]
SEXP GDAL7_vsi_read_file(std::string path) {
    gdal7::ErrorScope err;

    VSILFILE* file = VSIFOpenL(path.c_str(), "rb");
    if (file == nullptr) {
        vsi_failed(err, "Could not open", path);
    }

    VSIFSeekL(file, 0, SEEK_END);
    const vsi_l_offset size = VSIFTellL(file);
    VSIFSeekL(file, 0, SEEK_SET);

    // R vectors are indexed by R_xlen_t, so a file larger than that cannot be
    // one raw vector however much memory there is.
    if (size > static_cast<vsi_l_offset>(R_XLEN_T_MAX)) {
        VSIFCloseL(file);
        cpp11::stop("%s is too large to read into one vector", path.c_str());
    }

    SEXP out = PROTECT(Rf_allocVector(RAWSXP, static_cast<R_xlen_t>(size)));
    const size_t read =
        size == 0 ? 0 : VSIFReadL(RAW(out), 1, static_cast<size_t>(size), file);
    VSIFCloseL(file);

    if (read != static_cast<size_t>(size)) {
        UNPROTECT(1);
        vsi_failed(err, "Could not read all of", path);
    }

    err.flush();
    UNPROTECT(1);
    return out;
}

[[cpp11::register]]
void GDAL7_vsi_write_file(std::string path, SEXP bytes) {
    if (TYPEOF(bytes) != RAWSXP) {
        cpp11::stop("`bytes` must be a raw vector");
    }

    gdal7::ErrorScope err;
    VSILFILE* file = VSIFOpenL(path.c_str(), "wb");
    if (file == nullptr) {
        vsi_failed(err, "Could not open for writing", path);
    }

    const size_t size = static_cast<size_t>(Rf_xlength(bytes));
    const size_t written = size == 0 ? 0 : VSIFWriteL(RAW(bytes), 1, size, file);
    const int closed = VSIFCloseL(file);

    if (written != size || closed != 0) {
        vsi_failed(err, "Could not write all of", path);
    }
    err.flush();
}

// ============================================================================
// Configuration options
// ============================================================================

// GDAL reads its configuration from these at the moment it needs them, so
// setting one changes how the next call behaves. They are how caching,
// credentials and per-driver behaviour are steered.
[[cpp11::register]]
SEXP GDAL7_get_config_option(std::string name) {
    const char* value = CPLGetConfigOption(name.c_str(), nullptr);
    if (value == nullptr) {
        return R_NilValue;
    }
    return gdal7::chr(value);
}

[[cpp11::register]]
void GDAL7_set_config_option(std::string name, SEXP value) {
    // NULL unsets, which is not the same as setting an empty string: an unset
    // option falls back to GDAL's default, an empty one does not.
    if (value == R_NilValue) {
        CPLSetConfigOption(name.c_str(), nullptr);
        return;
    }
    const std::string text = cpp11::as_cpp<std::string>(value);
    CPLSetConfigOption(name.c_str(), text.c_str());
}

// What is set right now, so a scoped change can put it all back.
[[cpp11::register]]
cpp11::strings GDAL7_config_options() {
    char** options = CPLGetConfigOptions();
    cpp11::strings out = gdal7::named_from_csl(options);
    CSLDestroy(options);
    return out;
}
