// src/GDAL7_info.cpp
// Manual file - NOT generated by orchestrate.R
// Provides raster info methods (dimensions, bands, data types)

#include "gdal7.h"

namespace {

inline GDALDatasetH dataset(SEXP xp) {
    return gdal7::get<GDALDatasetH>(xp, gdal7::Kind::Dataset);
}

inline GDALRasterBandH band(SEXP xp) {
    return gdal7::get<GDALRasterBandH>(xp, gdal7::Kind::Band);
}

}  // namespace

// ============================================================================
// Dataset dimension properties (not captured by SWIG parser as they're %immutable)
// ============================================================================

[[cpp11::register]]
int GDAL7_dataset_get_raster_xsize(SEXP xp) {
    return GDALGetRasterXSize(dataset(xp));
}

[[cpp11::register]]
int GDAL7_dataset_get_raster_ysize(SEXP xp) {
    return GDALGetRasterYSize(dataset(xp));
}

[[cpp11::register]]
int GDAL7_dataset_get_raster_count(SEXP xp) {
    return GDALGetRasterCount(dataset(xp));
}

// ============================================================================
// Raster Band methods
// ============================================================================

[[cpp11::register]]
SEXP GDAL7_dataset_get_band(SEXP xp, int nBand) {
    GDALDatasetH h = dataset(xp);

    gdal7::ErrorScope err;
    GDALRasterBandH b = GDALGetRasterBand(h, nBand);
    if (!b) {
        err.stop("Invalid band number: " + std::to_string(nBand));
    }
    err.flush();

    // A band belongs to its dataset: passing the dataset as the parent is what
    // keeps that dataset open for as long as the band is reachable from R.
    return gdal7::wrap(b, gdal7::Kind::Band, xp);
}

[[cpp11::register]]
int GDAL7_band_get_xsize(SEXP xp) {
    return GDALGetRasterBandXSize(band(xp));
}

[[cpp11::register]]
int GDAL7_band_get_ysize(SEXP xp) {
    return GDALGetRasterBandYSize(band(xp));
}

[[cpp11::register]]
int GDAL7_band_get_band_number(SEXP xp) {
    return GDALGetBandNumber(band(xp));
}

[[cpp11::register]]
int GDAL7_band_get_data_type(SEXP xp) {
    return static_cast<int>(GDALGetRasterDataType(band(xp)));
}

[[cpp11::register]]
cpp11::strings GDAL7_band_get_data_type_name(SEXP xp) {
    return gdal7::chr(GDALGetDataTypeName(GDALGetRasterDataType(band(xp))));
}

[[cpp11::register]]
cpp11::integers GDAL7_band_get_block_size(SEXP xp) {
    int nBlockXSize = 0;
    int nBlockYSize = 0;
    GDALGetBlockSize(band(xp), &nBlockXSize, &nBlockYSize);

    cpp11::writable::integers result(2);
    result[0] = nBlockXSize;
    result[1] = nBlockYSize;
    result.names() = {"x", "y"};
    return result;
}

[[cpp11::register]]
SEXP GDAL7_band_get_nodata_value(SEXP xp) {
    int hasNoData = 0;
    double nodata = GDALGetRasterNoDataValue(band(xp), &hasNoData);

    if (!hasNoData) {
        return R_NilValue;
    }
    return cpp11::as_sexp(nodata);
}

[[cpp11::register]]
cpp11::strings GDAL7_band_get_description(SEXP xp) {
    return gdal7::chr(GDALGetDescription(static_cast<GDALMajorObjectH>(band(xp))));
}

[[cpp11::register]]
int GDAL7_band_get_color_interpretation(SEXP xp) {
    return static_cast<int>(GDALGetRasterColorInterpretation(band(xp)));
}

[[cpp11::register]]
cpp11::strings GDAL7_band_get_color_interpretation_name(SEXP xp) {
    GDALColorInterp ci = GDALGetRasterColorInterpretation(band(xp));
    return gdal7::chr(GDALGetColorInterpretationName(ci));
}

[[cpp11::register]]
SEXP GDAL7_band_get_scale(SEXP xp) {
    int hasScale = 0;
    double scale = GDALGetRasterScale(band(xp), &hasScale);

    if (!hasScale) {
        return R_NilValue;
    }
    return cpp11::as_sexp(scale);
}

[[cpp11::register]]
SEXP GDAL7_band_get_offset(SEXP xp) {
    int hasOffset = 0;
    double offset = GDALGetRasterOffset(band(xp), &hasOffset);

    if (!hasOffset) {
        return R_NilValue;
    }
    return cpp11::as_sexp(offset);
}

[[cpp11::register]]
cpp11::strings GDAL7_band_get_unit_type(SEXP xp) {
    return gdal7::chr(GDALGetRasterUnitType(band(xp)));
}
