// src/GDAL7_open.cpp
// Manual file - NOT generated by orchestrate.R
// Provides gdal_open() to create Dataset objects

#include "gdal7.h"

// ============================================================================
// GDAL initialization - call once at package load
// ============================================================================

[[cpp11::register]]
void GDAL7_init() {
    GDALAllRegister();
}

[[cpp11::register]]
SEXP GDAL7_gdal_open(std::string path, bool update, bool multidim) {
    unsigned int flags = update ? GDAL_OF_UPDATE : GDAL_OF_READONLY;
    flags |= GDAL_OF_VERBOSE_ERROR;

    if (multidim) {
        flags |= GDAL_OF_MULTIDIM_RASTER;
    }

    gdal7::ErrorScope err;
    GDALDatasetH h = GDALOpenEx(path.c_str(), flags, nullptr, nullptr, nullptr);
    if (!h) {
        // GDAL names the file in its own message, so the path is only added
        // back when GDAL had nothing to say.
        err.stop(err.failed() ? std::string("Failed to open dataset")
                              : "Failed to open " + path);
    }

    // The dataset is wrapped before the warnings are raised, so that a warning
    // turned into an error by options(warn = 2) still leaves R holding
    // something that will close the dataset.
    SEXP xp = PROTECT(gdal7::wrap(h, gdal7::Kind::Dataset));
    err.flush();
    UNPROTECT(1);
    return xp;
}

[[cpp11::register]]
void GDAL7_close(SEXP xp) {
    gdal7::close(xp, gdal7::Kind::Dataset);
}

// ============================================================================
// Test hook
// ============================================================================

// Raise a GDAL message inside an error scope. GDAL only complains when a
// driver has something to complain about, which no shipped fixture reliably
// provokes, so this is how the route from CPLError to an R condition is
// tested. Not exported.
[[cpp11::register]]
void GDAL7_emit_gdal_message(std::string level, std::string message) {
    gdal7::ErrorScope err;

    if (level == "failure") {
        CPLError(CE_Failure, CPLE_AppDefined, "%s", message.c_str());
        err.stop("GDAL call failed");
    }

    CPLError(CE_Warning, CPLE_AppDefined, "%s", message.c_str());
    err.flush();
}
