// src/GDAL7_driver.cpp
// Manual file - NOT generated by orchestrate.R
// Provides GDALDriver class methods

#include <cpp11.hpp>
#include <gdal.h>

// ============================================================================
// Driver info methods
// ============================================================================

[[cpp11::register]]
std::string GDAL7_driver_get_short_name(SEXP xp) {
    GDALDriverH* ptr = reinterpret_cast<GDALDriverH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid driver handle");
    }
    const char* name = GDALGetDriverShortName(*ptr);
    return name ? std::string(name) : std::string("");
}

[[cpp11::register]]
std::string GDAL7_driver_get_long_name(SEXP xp) {
    GDALDriverH* ptr = reinterpret_cast<GDALDriverH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid driver handle");
    }
    const char* name = GDALGetDriverLongName(*ptr);
    return name ? std::string(name) : std::string("");
}

[[cpp11::register]]
std::string GDAL7_driver_get_help_topic(SEXP xp) {
    GDALDriverH* ptr = reinterpret_cast<GDALDriverH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid driver handle");
    }
    const char* topic = GDALGetDriverHelpTopic(*ptr);
    return topic ? std::string(topic) : std::string("");
}

[[cpp11::register]]
bool GDAL7_driver_has_open_option(SEXP xp, std::string option_name) {
    GDALDriverH* ptr = reinterpret_cast<GDALDriverH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid driver handle");
    }
    return GDALDriverHasOpenOption(*ptr, option_name.c_str());
}

// ============================================================================
// Dataset get_driver returns external pointer - need to wrap properly
// ============================================================================

[[cpp11::register]]
SEXP GDAL7_dataset_get_driver_ptr(SEXP xp) {
    GDALDatasetH* ptr = reinterpret_cast<GDALDatasetH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid dataset handle");
    }
    
    GDALDriverH drv = GDALGetDatasetDriver(*ptr);
    if (!drv) {
        return R_NilValue;
    }
    
    // Note: Driver is owned by GDAL, not by us. Don't set a finalizer.
    return cpp11::external_pointer<GDALDriverH>(new GDALDriverH(drv));
}

// ============================================================================
// Top-level driver functions
// ============================================================================

[[cpp11::register]]
int GDAL7_get_driver_count() {
    return GDALGetDriverCount();
}

[[cpp11::register]]
SEXP GDAL7_get_driver_by_name(std::string name) {
    GDALDriverH drv = GDALGetDriverByName(name.c_str());
    if (!drv) {
        return R_NilValue;
    }
    return cpp11::external_pointer<GDALDriverH>(new GDALDriverH(drv));
}

[[cpp11::register]]
SEXP GDAL7_get_driver(int index) {
    GDALDriverH drv = GDALGetDriver(index);
    if (!drv) {
        return R_NilValue;
    }
    return cpp11::external_pointer<GDALDriverH>(new GDALDriverH(drv));
}

// ============================================================================
// Driver capabilities - check metadata for DCAP_* flags
// ============================================================================

[[cpp11::register]]
bool GDAL7_driver_test_capability(SEXP xp, std::string capability) {
    GDALDriverH* ptr = reinterpret_cast<GDALDriverH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid driver handle");
    }
    
    // Check in driver metadata for DCAP_* entries
    const char* value = GDALGetMetadataItem(*ptr, capability.c_str(), NULL);
    if (value && EQUAL(value, "YES")) {
        return true;
    }
    return false;
}

[[cpp11::register]]
cpp11::strings GDAL7_driver_get_creation_options(SEXP xp) {
    GDALDriverH* ptr = reinterpret_cast<GDALDriverH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid driver handle");
    }
    
    const char* xml = GDALGetDriverCreationOptionList(*ptr);
    if (!xml) {
        return cpp11::writable::strings();
    }
    
    cpp11::writable::strings result(1);
    result[0] = std::string(xml);
    return result;
}

// ============================================================================
// Get driver metadata item (inherits from MajorObject but need driver handle)
// ============================================================================

[[cpp11::register]]
std::string GDAL7_driver_get_metadata_item(SEXP xp, std::string name, std::string domain) {
    GDALDriverH* ptr = reinterpret_cast<GDALDriverH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid driver handle");
    }
    
    const char* value = GDALGetMetadataItem(*ptr, name.c_str(), 
                                             domain.empty() ? NULL : domain.c_str());
    return value ? std::string(value) : std::string("");
}
