// Auto-generated by GDAL7 generator - do not edit
#include <cpp11.hpp>
#include "gdal.h"
#include "cpl_string.h"

using namespace cpp11;

// -----------------------------------------------------------------------------
// MajorObject bindings
// -----------------------------------------------------------------------------

// Helper to extract and validate pointer
inline GDALMajorObjectH get_majorobject_handle(SEXP xp) {
    external_pointer<GDALMajorObjectH> ptr(xp);
    if (!ptr || !*ptr) {
        stop("Invalid MajorObject pointer (NULL or already closed)");
    }
    return *ptr;
}

// Helper to convert R named character vector to char** (KEY=VALUE format)
inline char** strings_to_csl(cpp11::strings strs) {
    char** result = NULL;
    for (auto s : strs) {
        result = CSLAddString(result, std::string(s).c_str());
    }
    return result;
}

// Helper to convert R named list to char** (KEY=VALUE format)
inline char** list_to_csl(cpp11::list lst) {
    char** result = NULL;
    cpp11::strings names = lst.names();
    for (int i = 0; i < lst.size(); i++) {
        std::string key = std::string(names[i]);
        std::string val = cpp11::as_cpp<std::string>(lst[i]);
        std::string kv = key + "=" + val;
        result = CSLAddString(result, kv.c_str());
    }
    return result;
}

[[cpp11::register]]
std::string GDAL7_majorobject_get_description(SEXP xp) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    const char* result = GDALGetDescription(h);
    return result ? std::string(result) : std::string("");
}

[[cpp11::register]]
void GDAL7_majorobject_set_description(SEXP xp, std::string pszNewDesc) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    GDALSetDescription(h, pszNewDesc.c_str());
}

[[cpp11::register]]
cpp11::strings GDAL7_majorobject_get_metadata_domain_list(SEXP xp) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    char** result = GDALGetMetadataDomainList(h);
    writable::strings out;
    if (result) {
        for (int i = 0; result[i] != NULL; i++) {
            out.push_back(result[i]);
        }
        CSLDestroy(result);
    }
    return out;
}

[[cpp11::register]]
cpp11::strings GDAL7_majorobject_get_metadata_dict(SEXP xp, std::string pszDomain) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    CSLConstList result = GDALGetMetadata(h, pszDomain.c_str());
    writable::strings out;
    if (result) {
        for (int i = 0; result[i] != NULL; i++) {
            out.push_back(result[i]);
        }
        // Borrowed reference - do not free
    }
    return out;
}

[[cpp11::register]]
cpp11::strings GDAL7_majorobject_get_metadata_list(SEXP xp, std::string pszDomain) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    CSLConstList result = GDALGetMetadata(h, pszDomain.c_str());
    writable::strings out;
    if (result) {
        for (int i = 0; result[i] != NULL; i++) {
            out.push_back(result[i]);
        }
        // Borrowed reference - do not free
    }
    return out;
}

[[cpp11::register]]
int GDAL7_majorobject_set_metadata(SEXP xp, cpp11::list papszMetadata, std::string pszDomain) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    char** csl = list_to_csl(papszMetadata);
    CPLErr err = GDALSetMetadata(h, csl, pszDomain.c_str());
    CSLDestroy(csl);
    if (err != CE_None) {
        stop("SetMetadata failed: %s", CPLGetLastErrorMsg());
    }
    return static_cast<int>(err);
}

[[cpp11::register]]
int GDAL7_majorobject_set_metadata_2(SEXP xp, std::string pszMetadataString, std::string pszDomain) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    char** csl = CSLAddString(NULL, pszMetadataString.c_str());
    CPLErr err = GDALSetMetadata(h, csl, pszDomain.c_str());
    CSLDestroy(csl);
    if (err != CE_None) {
        stop("SetMetadata failed: %s", CPLGetLastErrorMsg());
    }
    return static_cast<int>(err);
}

[[cpp11::register]]
std::string GDAL7_majorobject_get_metadata_item(SEXP xp, std::string pszName, std::string pszDomain) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    const char* result = GDALGetMetadataItem(h, pszName.c_str(), pszDomain.c_str());
    return result ? std::string(result) : std::string("");
}

[[cpp11::register]]
int GDAL7_majorobject_set_metadata_item(SEXP xp, std::string pszName, std::string pszValue, std::string pszDomain) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    CPLErr err = GDALSetMetadataItem(h, pszName.c_str(), pszValue.c_str(), pszDomain.c_str());
    if (err != CE_None) {
        stop("SetMetadataItem failed: %s", CPLGetLastErrorMsg());
    }
    return static_cast<int>(err);
}

