// src/GDAL7_rasterio.cpp
// Manual file - NOT generated by orchestrate.R
// Geotransforms, overviews and windowed reads.

#include <algorithm>
#include <cmath>
#include <cstring>
#include <limits>
#include <string>
#include <vector>

#include "gdal7.h"

namespace {

inline GDALDatasetH dataset(SEXP xp) {
    return gdal7::get<GDALDatasetH>(xp, gdal7::Kind::Dataset);
}

inline GDALRasterBandH band(SEXP xp) {
    return gdal7::get<GDALRasterBandH>(xp, gdal7::Kind::Band);
}

// A geotransform is always the same six numbers, so it is worth insisting on
// that rather than letting a short vector reach GDAL.
void copy_geotransform(cpp11::doubles gt, double out[6]) {
    if (gt.size() != 6) {
        cpp11::stop("A geotransform is 6 numbers, got %d", static_cast<int>(gt.size()));
    }
    for (int i = 0; i < 6; i++) {
        out[i] = gt[i];
    }
}

GDALRIOResampleAlg resample_from_name(const std::string& name) {
    if (EQUAL(name.c_str(), "nearest")) return GRIORA_NearestNeighbour;
    if (EQUAL(name.c_str(), "bilinear")) return GRIORA_Bilinear;
    if (EQUAL(name.c_str(), "cubic")) return GRIORA_Cubic;
    if (EQUAL(name.c_str(), "cubicspline")) return GRIORA_CubicSpline;
    if (EQUAL(name.c_str(), "lanczos")) return GRIORA_Lanczos;
    if (EQUAL(name.c_str(), "average")) return GRIORA_Average;
    if (EQUAL(name.c_str(), "mode")) return GRIORA_Mode;
    if (EQUAL(name.c_str(), "gauss")) return GRIORA_Gauss;
    if (EQUAL(name.c_str(), "rms")) return GRIORA_RMS;

    cpp11::stop("Unknown resampling algorithm '%s'. One of: nearest, bilinear, "
                "cubic, cubicspline, lanczos, average, mode, gauss, rms",
                name.c_str());
}


// The integer window GDAL is given has to cover the floating point one, which
// is what the floating point fields then refine. Read and write set this up
// the same way, so it is written once.
struct Window {
    int off_x, off_y, size_x, size_y;
    int out_x, out_y;
    GDALRasterIOExtraArg extra;
};

Window make_window(cpp11::doubles window, cpp11::integers out_size,
                   const std::string& resample) {
    if (window.size() != 4) {
        cpp11::stop("`window` is 4 numbers: xoff, yoff, xsize, ysize");
    }
    if (out_size.size() != 2) {
        cpp11::stop("`out_size` is 2 numbers: the output width and height");
    }

    const double off_x = window[0];
    const double off_y = window[1];
    const double size_x = window[2];
    const double size_y = window[3];

    if (!(size_x > 0) || !(size_y > 0)) {
        cpp11::stop("The window must have a positive width and height");
    }

    Window out;
    out.out_x = out_size[0];
    out.out_y = out_size[1];
    if (out.out_x <= 0 || out.out_y <= 0) {
        cpp11::stop("`out_size` must be positive");
    }

    out.off_x = static_cast<int>(std::floor(off_x));
    out.off_y = static_cast<int>(std::floor(off_y));
    out.size_x = static_cast<int>(std::ceil(off_x + size_x)) - out.off_x;
    out.size_y = static_cast<int>(std::ceil(off_y + size_y)) - out.off_y;

    INIT_RASTERIO_EXTRA_ARG(out.extra);
    out.extra.eResampleAlg = resample_from_name(resample);
    out.extra.bFloatingPointWindowValidity = TRUE;
    out.extra.dfXOff = off_x;
    out.extra.dfYOff = off_y;
    out.extra.dfXSize = size_x;
    out.extra.dfYSize = size_y;
    return out;
}

// The bands of a dataset, checked against what it has.
std::vector<int> band_list(GDALDatasetH h, cpp11::integers bands) {
    if (bands.size() < 1) {
        cpp11::stop("At least one band is needed");
    }
    const int count = GDALGetRasterCount(h);
    std::vector<int> out(static_cast<size_t>(bands.size()));
    for (R_xlen_t i = 0; i < bands.size(); i++) {
        const int b = bands[i];
        if (b < 1 || b > count) {
            cpp11::stop("Band %d is out of range; this dataset has %d", b, count);
        }
        out[static_cast<size_t>(i)] = b;
    }
    return out;
}

}  // namespace

// ============================================================================
// Geotransform
// ============================================================================

[[cpp11::register]]
SEXP GDAL7_dataset_get_geotransform(SEXP xp) {
    GDALDatasetH h = dataset(xp);

    double gt[6];
    gdal7::ErrorScope err;
    if (GDALGetGeoTransform(h, gt) != CE_None) {
        // GDAL fills the identity and reports failure when a dataset carries no
        // geotransform. NULL says that plainly; the identity would not.
        err.flush();
        return R_NilValue;
    }
    err.flush();

    cpp11::writable::doubles out(6);
    for (int i = 0; i < 6; i++) {
        out[i] = gt[i];
    }
    out.names() = {"origin_x", "pixel_width", "row_rotation",
                   "origin_y", "column_rotation", "pixel_height"};
    return out;
}

[[cpp11::register]]
void GDAL7_dataset_set_geotransform(SEXP xp, cpp11::doubles gt) {
    GDALDatasetH h = dataset(xp);

    double values[6];
    copy_geotransform(gt, values);

    gdal7::ErrorScope err;
    if (GDALSetGeoTransform(h, values) != CE_None) {
        err.stop("Could not set the geotransform");
    }
    err.flush();
}

// Pixel/line to georeferenced, for whole vectors at a time rather than one
// point per call.
[[cpp11::register]]
cpp11::list GDAL7_apply_geotransform(cpp11::doubles gt, cpp11::doubles pixel,
                                     cpp11::doubles line) {
    double values[6];
    copy_geotransform(gt, values);

    if (pixel.size() != line.size()) {
        cpp11::stop("`pixel` and `line` must be the same length");
    }

    const R_xlen_t n = pixel.size();
    cpp11::writable::doubles x(n);
    cpp11::writable::doubles y(n);

    for (R_xlen_t i = 0; i < n; i++) {
        double gx = NA_REAL;
        double gy = NA_REAL;
        if (!ISNA(pixel[i]) && !ISNA(line[i])) {
            GDALApplyGeoTransform(values, pixel[i], line[i], &gx, &gy);
        }
        x[i] = gx;
        y[i] = gy;
    }

    cpp11::writable::list out;
    out.push_back(cpp11::named_arg("x") = x);
    out.push_back(cpp11::named_arg("y") = y);
    return out;
}

[[cpp11::register]]
SEXP GDAL7_inv_geotransform(cpp11::doubles gt) {
    double values[6];
    copy_geotransform(gt, values);

    double inverse[6];
    if (!GDALInvGeoTransform(values, inverse)) {
        // A geotransform with a zero determinant cannot be inverted, which is
        // an answer rather than an error.
        return R_NilValue;
    }

    cpp11::writable::doubles out(6);
    for (int i = 0; i < 6; i++) {
        out[i] = inverse[i];
    }
    return out;
}

// ============================================================================
// Overviews
// ============================================================================

[[cpp11::register]]
int GDAL7_band_get_overview_count(SEXP xp) {
    return GDALGetOverviewCount(band(xp));
}

[[cpp11::register]]
SEXP GDAL7_band_get_overview(SEXP xp, int index) {
    GDALRasterBandH h = band(xp);

    const int count = GDALGetOverviewCount(h);
    if (index < 0 || index >= count) {
        cpp11::stop("Overview %d is out of range; this band has %d", index, count);
    }

    GDALRasterBandH ov = GDALGetOverview(h, index);
    if (!ov) {
        cpp11::stop("Could not open overview %d", index);
    }

    // An overview belongs to the same dataset as the band it came from, and
    // passing the band as the parent carries that dataset's record across.
    return gdal7::wrap(ov, gdal7::Kind::Band, xp);
}

// The size of each overview level, which is what decides which level a read at
// a given output size will actually touch.
[[cpp11::register]]
cpp11::list GDAL7_band_get_overview_sizes(SEXP xp) {
    GDALRasterBandH h = band(xp);

    const int count = GDALGetOverviewCount(h);
    cpp11::writable::integers xs(count);
    cpp11::writable::integers ys(count);

    for (int i = 0; i < count; i++) {
        GDALRasterBandH ov = GDALGetOverview(h, i);
        xs[i] = ov ? GDALGetRasterBandXSize(ov) : NA_INTEGER;
        ys[i] = ov ? GDALGetRasterBandYSize(ov) : NA_INTEGER;
    }

    cpp11::writable::list out;
    out.push_back(cpp11::named_arg("xsize") = xs);
    out.push_back(cpp11::named_arg("ysize") = ys);
    return out;
}

// ============================================================================
// Windowed reads
// ============================================================================

// The R vector a read fills, and the GDAL buffer type that fills it. Reading
// straight into the R type is the point: a Byte band read as raw is one eighth
// the memory of the same band read as double, which is the difference between
// a workable RGB image in memory and an unworkable one.
struct ReadType {
    GDALDataType gdal;
    SEXPTYPE sexp;
};

ReadType read_type(const std::string& type) {
    if (type == "double") {
        return {GDT_Float64, REALSXP};
    }
    if (type == "integer") {
        return {GDT_Int32, INTSXP};
    }
    if (type == "raw") {
        return {GDT_Byte, RAWSXP};
    }
    cpp11::stop("`type` is one of \"double\", \"integer\" or \"raw\"");
}

// Whether a band's values can survive the trip into that R type. GDAL would
// clamp silently, so this refuses instead: a read that quietly turns 40000
// into 255 is worse than one that will not run.
void check_read_type(GDALRasterBandH h, const ReadType& rt, int band_number) {
    if (rt.sexp == REALSXP) {
        return;
    }

    const GDALDataType band_type = GDALGetRasterDataType(h);
    const bool fits_raw = band_type == GDT_Byte;
    const bool fits_integer = fits_raw || band_type == GDT_Int8 ||
                              band_type == GDT_Int16 || band_type == GDT_UInt16 ||
                              band_type == GDT_Int32;

    if ((rt.sexp == RAWSXP && fits_raw) || (rt.sexp == INTSXP && fits_integer)) {
        return;
    }

    cpp11::stop("Band %d holds %s, which does not fit R's %s; read it as \"double\"",
                band_number, GDALGetDataTypeName(band_type),
                rt.sexp == RAWSXP ? "raw" : "integer");
}

// The start of a vector's data, whichever of the three types it is.
void* vector_data(SEXP x) {
    switch (TYPEOF(x)) {
        case REALSXP:
            return REAL(x);
        case INTSXP:
            return INTEGER(x);
        case RAWSXP:
            return RAW(x);
        default:
            cpp11::stop("Unsupported buffer type");  // # nocov
    }
}

// Read a window of a band at a chosen output size.
//
// This is GDALRasterIOEx rather than plain RasterIO: the window may be
// fractional, the output size is independent of it, and the resampling is
// chosen by the caller. Those three together are what let a huge raster over
// /vsicurl/ be read at a useful size without fetching all of it, because GDAL
// picks an overview level to satisfy the output size.
[[cpp11::register]]
SEXP GDAL7_band_read(SEXP xp, cpp11::doubles window, cpp11::integers out_size,
                     std::string resample, std::string type) {
    GDALRasterBandH h = band(xp);
    Window w = make_window(window, out_size, resample);

    const ReadType rt = read_type(type);
    check_read_type(h, rt, GDALGetBandNumber(h));

    // "double" holds any band type, which is why it is the default. Int64
    // beyond 2^53 is the one case where it still loses precision.
    cpp11::sexp out(Rf_allocVector(
        rt.sexp, static_cast<R_xlen_t>(w.out_x) * w.out_y));

    gdal7::ErrorScope err;
    const CPLErr status = GDALRasterIOEx(
        h, GF_Read, w.off_x, w.off_y, w.size_x, w.size_y,
        vector_data(out), w.out_x, w.out_y, rt.gdal, 0, 0, &w.extra);

    if (status != CE_None) {
        err.stop("Could not read the raster window");
    }
    err.flush();

    return out;
}

// Read the same window from several bands in one call. Band by band this is
// one round trip each and, over a network, one set of range requests each;
// GDAL issues them together when it is asked for the bands at once.
[[cpp11::register]]
cpp11::list GDAL7_dataset_read(SEXP xp, cpp11::integers bands, cpp11::doubles window,
                               cpp11::integers out_size, std::string resample,
                               std::string type) {
    GDALDatasetH h = dataset(xp);
    Window w = make_window(window, out_size, resample);
    const std::vector<int> bands_to_read = band_list(h, bands);

    // Every band has to survive the requested type, not just the first one:
    // a Byte band beside a Float32 band would otherwise read as raw and clamp.
    const ReadType rt = read_type(type);
    for (int b : bands_to_read) {
        check_read_type(GDALGetRasterBand(h, b), rt, b);
    }

    // One buffer, band sequential, split into a vector per band afterwards.
    const size_t per_band = static_cast<size_t>(w.out_x) * static_cast<size_t>(w.out_y);
    const size_t item = static_cast<size_t>(GDALGetDataTypeSizeBytes(rt.gdal));
    std::vector<unsigned char> buffer(per_band * bands_to_read.size() * item);

    gdal7::ErrorScope err;
    const CPLErr status = GDALDatasetRasterIOEx(
        h, GF_Read, w.off_x, w.off_y, w.size_x, w.size_y,
        buffer.data(), w.out_x, w.out_y, rt.gdal,
        static_cast<int>(bands_to_read.size()),
        const_cast<int*>(bands_to_read.data()), 0, 0, 0, &w.extra);

    if (status != CE_None) {
        err.stop("Could not read the raster window");
    }
    err.flush();

    cpp11::writable::list out(static_cast<R_xlen_t>(bands_to_read.size()));
    cpp11::writable::strings names(static_cast<R_xlen_t>(bands_to_read.size()));
    for (size_t i = 0; i < bands_to_read.size(); i++) {
        cpp11::sexp values(Rf_allocVector(rt.sexp, static_cast<R_xlen_t>(per_band)));
        std::memcpy(vector_data(values), buffer.data() + i * per_band * item,
                    per_band * item);
        out[static_cast<R_xlen_t>(i)] = values;
        names[static_cast<R_xlen_t>(i)] =
            cpp11::r_string(std::to_string(bands_to_read[i]));
    }
    out.names() = names;
    return out;
}

// ============================================================================
// Writing
// ============================================================================

// The mirror of the read above, with the same window and the same output size,
// so a window read at one size can be written back at another. Values go in as
// doubles whatever the band holds; GDAL converts, and a value the band's type
// cannot hold is clamped by GDAL rather than silently wrapped.
[[cpp11::register]]
void GDAL7_band_write(SEXP xp, cpp11::doubles values, cpp11::doubles window,
                      cpp11::integers out_size, std::string resample) {
    GDALRasterBandH h = band(xp);
    Window w = make_window(window, out_size, resample);

    const R_xlen_t wanted = static_cast<R_xlen_t>(w.out_x) * w.out_y;
    if (values.size() != wanted) {
        cpp11::stop("%d values for a %d by %d block, which needs %d",
                    static_cast<int>(values.size()), w.out_x, w.out_y,
                    static_cast<int>(wanted));
    }

    gdal7::ErrorScope err;
    const CPLErr status = GDALRasterIOEx(
        h, GF_Write, w.off_x, w.off_y, w.size_x, w.size_y,
        const_cast<double*>(REAL(values)), w.out_x, w.out_y, GDT_Float64,
        0, 0, &w.extra);

    if (status != CE_None) {
        err.stop("Could not write the raster window");
    }
    err.flush();
}

// Several bands in one pass, the same way reading them is one pass. `values`
// is one vector per band, in the order of `bands`.
[[cpp11::register]]
void GDAL7_dataset_write(SEXP xp, cpp11::list values, cpp11::integers bands,
                         cpp11::doubles window, cpp11::integers out_size,
                         std::string resample) {
    GDALDatasetH h = dataset(xp);
    Window w = make_window(window, out_size, resample);
    const std::vector<int> bands_to_write = band_list(h, bands);

    if (values.size() != static_cast<R_xlen_t>(bands_to_write.size())) {
        cpp11::stop("%d blocks of values for %d bands",
                    static_cast<int>(values.size()),
                    static_cast<int>(bands_to_write.size()));
    }

    const size_t per_band = static_cast<size_t>(w.out_x) * static_cast<size_t>(w.out_y);
    std::vector<double> buffer(per_band * bands_to_write.size());

    for (size_t i = 0; i < bands_to_write.size(); i++) {
        cpp11::doubles block(values[static_cast<R_xlen_t>(i)]);
        if (static_cast<size_t>(block.size()) != per_band) {
            cpp11::stop("Band %d was given %d values for a %d by %d block",
                        bands_to_write[i], static_cast<int>(block.size()),
                        w.out_x, w.out_y);
        }
        std::copy(REAL(block), REAL(block) + per_band,
                  buffer.begin() + static_cast<std::ptrdiff_t>(i * per_band));
    }

    gdal7::ErrorScope err;
    const CPLErr status = GDALDatasetRasterIOEx(
        h, GF_Write, w.off_x, w.off_y, w.size_x, w.size_y,
        buffer.data(), w.out_x, w.out_y, GDT_Float64,
        static_cast<int>(bands_to_write.size()),
        const_cast<int*>(bands_to_write.data()), 0, 0, 0, &w.extra);

    if (status != CE_None) {
        err.stop("Could not write the raster window");
    }
    err.flush();
}

// Everything written so far, on disk, without closing the dataset. A dataset
// left open holds its last blocks in memory, so this is what makes a file
// readable by something else while it is still being built.
[[cpp11::register]]
void GDAL7_dataset_flush(SEXP xp) {
    gdal7::ErrorScope err;
    GDALFlushCache(dataset(xp));
    err.flush();
}

// ============================================================================
// Band properties a created dataset needs set
// ============================================================================

[[cpp11::register]]
void GDAL7_band_set_nodata_value(SEXP xp, SEXP value) {
    GDALRasterBandH h = band(xp);

    gdal7::ErrorScope err;
    // NULL takes the nodata value off the band rather than setting it to
    // anything, which is a different thing from setting it to NaN.
    const CPLErr status = value == R_NilValue
                              ? GDALDeleteRasterNoDataValue(h)
                              : GDALSetRasterNoDataValue(h, Rf_asReal(value));
    if (status != CE_None) {
        err.stop("Could not set the nodata value");
    }
    err.flush();
}

[[cpp11::register]]
void GDAL7_band_set_scale(SEXP xp, double value) {
    gdal7::ErrorScope err;
    if (GDALSetRasterScale(band(xp), value) != CE_None) {
        err.stop("Could not set the scale");
    }
    err.flush();
}

[[cpp11::register]]
void GDAL7_band_set_offset(SEXP xp, double value) {
    gdal7::ErrorScope err;
    if (GDALSetRasterOffset(band(xp), value) != CE_None) {
        err.stop("Could not set the offset");
    }
    err.flush();
}

[[cpp11::register]]
void GDAL7_band_set_unit_type(SEXP xp, std::string value) {
    gdal7::ErrorScope err;
    if (GDALSetRasterUnitType(band(xp), value.c_str()) != CE_None) {
        err.stop("Could not set the unit");
    }
    err.flush();
}

[[cpp11::register]]
void GDAL7_band_set_color_interpretation(SEXP xp, std::string name) {
    const GDALColorInterp interp = GDALGetColorInterpretationByName(name.c_str());
    if (interp == GCI_Undefined && !EQUAL(name.c_str(), "Undefined")) {
        cpp11::stop("'%s' is not a colour interpretation. "
                    "gdal_color_interpretations() lists them",
                    name.c_str());
    }

    gdal7::ErrorScope err;
    if (GDALSetRasterColorInterpretation(band(xp), interp) != CE_None) {
        err.stop("Could not set the colour interpretation");
    }
    err.flush();
}

// ============================================================================
// Coordinate reference systems
// ============================================================================

// GDALSetProjection wants WKT, but nobody wants to type WKT. Anything
// OSRSetFromUserInput understands is accepted instead: "EPSG:4326",
// "+proj=laea +lat_0=-90", a PROJJSON document, the contents of a .prj file,
// or WKT itself, which passes through unchanged.
[[cpp11::register]]
void GDAL7_dataset_set_crs(SEXP xp, std::string crs) {
    GDALDatasetH h = dataset(xp);

    gdal7::ErrorScope err;
    OGRSpatialReferenceH srs = OSRNewSpatialReference(nullptr);
    if (OSRSetFromUserInput(srs, crs.c_str()) != OGRERR_NONE) {
        OSRDestroySpatialReference(srs);
        err.stop("Could not read '" + crs + "' as a coordinate reference system");
    }

    const CPLErr status = GDALSetSpatialRef(h, srs);
    OSRDestroySpatialReference(srs);

    if (status != CE_None) {
        err.stop("Could not set the coordinate reference system");
    }
    err.flush();
}

// A dataset's own coordinate reference system, as WKT2. GDALGetProjectionRef
// gives WKT1, which cannot carry what a modern CRS says, so the spatial
// reference is asked for directly and exported the way crs_to_wkt() does.
// A dataset with no CRS gives back NA rather than an empty string, which is
// what GDAL reports and is indistinguishable from a CRS that failed to parse.
[[cpp11::register]]
cpp11::strings GDAL7_dataset_get_crs(SEXP xp) {
    GDALDatasetH h = dataset(xp);

    gdal7::ErrorScope err;
    OGRSpatialReferenceH srs = GDALGetSpatialRef(h);
    if (srs == nullptr) {
        err.flush();
        return cpp11::writable::strings({cpp11::r_string(NA_STRING)});
    }

    CPLStringList options;
    options.AddNameValue("FORMAT", "WKT2");
    options.AddNameValue("MULTILINE", "NO");

    char* wkt = nullptr;
    const OGRErr status = OSRExportToWktEx(srs, &wkt, options.List());
    if (status != OGRERR_NONE || wkt == nullptr) {
        CPLFree(wkt);
        err.stop("Could not write this dataset's coordinate reference system as WKT");
    }

    cpp11::writable::strings out({cpp11::r_string(wkt)});
    CPLFree(wkt);
    err.flush();
    return out;
}

// The same conversion on its own, for checking a CRS string or turning one
// into WKT. WKT2 is asked for by name rather than taken as the default,
// because GDAL's plain export still writes WKT1 for compatibility, and WKT1
// cannot carry what a modern CRS says: the projection above comes back out of
// WKT1 as PROJCS["unknown"].
[[cpp11::register]]
cpp11::strings GDAL7_crs_to_wkt(std::string crs, std::string format,
                                bool multiline) {
    gdal7::ErrorScope err;
    OGRSpatialReferenceH srs = OSRNewSpatialReference(nullptr);
    if (OSRSetFromUserInput(srs, crs.c_str()) != OGRERR_NONE) {
        OSRDestroySpatialReference(srs);
        err.stop("Could not read '" + crs + "' as a coordinate reference system");
    }

    CPLStringList options;
    options.AddNameValue("FORMAT", format.c_str());
    options.AddNameValue("MULTILINE", multiline ? "YES" : "NO");

    char* wkt = nullptr;
    const OGRErr status = OSRExportToWktEx(srs, &wkt, options.List());
    OSRDestroySpatialReference(srs);

    if (status != OGRERR_NONE) {
        CPLFree(wkt);
        err.stop("Could not write this coordinate reference system as " + format);
    }

    cpp11::strings out = gdal7::chr(wkt);
    CPLFree(wkt);
    err.flush();
    return out;
}

// Move an extent from one coordinate reference system to another.
//
// Two samplings, unioned, because neither is enough on its own.
//
// OCTTransformBounds walks the boundary of the box. For a transform that is a
// diffeomorphism over the box that is provably sufficient: an interior
// extremum of the easting would need the first row of the Jacobian to vanish,
// and a non-singular Jacobian has no zero row, so there is nothing inside to
// find. GDAL then patches the places where that assumption fails and it knows
// to look: the pole at the target's central meridian, plus or minus 180 from
// it, and Mercator's latitude limit.
//
// It does not patch the ones it did not enumerate. A box around the antipode
// of an oblique azimuthal equidistant comes back 365 km short in easting; a
// box straddling an orthographic's limb comes back 8 percent short in area.
// Those are singularities in the interior, which is exactly where the boundary
// argument stops applying.
//
// So an interior mesh goes in as well. It is not a replacement: a mesh spends
// almost all its points in the interior and samples the boundary more coarsely
// than the walk does, and on an oblique Mercator box a 65 by 65 mesh comes
// back 2.4 km inside the walk's answer. The union of the two dominates either.
//
// See inst/design/extent-transformation.md for the measurements.
[[cpp11::register]]
cpp11::doubles GDAL7_transform_extent(cpp11::doubles bbox, std::string from,
                                      std::string to, int densify, int mesh) {
    if (bbox.size() != 4) {
        cpp11::stop("`extent` is 4 numbers: xmin, ymin, xmax, ymax");
    }
    if (densify < 0) {
        cpp11::stop("`densify` cannot be negative");
    }
    if (mesh < 0 || mesh > 1000) {
        cpp11::stop("`mesh` is between 0 and 1000");
    }
    if (!(bbox[3] >= bbox[1])) {
        cpp11::stop("`extent` has ymax below ymin");
    }

    gdal7::ErrorScope err;

    OGRSpatialReferenceH src = OSRNewSpatialReference(nullptr);
    if (OSRSetFromUserInput(src, from.c_str()) != OGRERR_NONE) {
        OSRDestroySpatialReference(src);
        err.stop("Could not read '" + from + "' as a coordinate reference system");
    }

    OGRSpatialReferenceH dst = OSRNewSpatialReference(nullptr);
    if (OSRSetFromUserInput(dst, to.c_str()) != OGRERR_NONE) {
        OSRDestroySpatialReference(src);
        OSRDestroySpatialReference(dst);
        err.stop("Could not read '" + to + "' as a coordinate reference system");
    }

    // Without this, a CRS whose authority puts latitude first would read the
    // box in that order, and the caller's c(xmin, ymin, xmax, ymax) would
    // quietly mean something else. Both sides are pinned to x, y.
    OSRSetAxisMappingStrategy(src, OAMS_TRADITIONAL_GIS_ORDER);
    OSRSetAxisMappingStrategy(dst, OAMS_TRADITIONAL_GIS_ORDER);

    // GDAL reads xmax below xmin as a box crossing the antimeridian, and
    // returns the answer in the same wrapped form. That form cannot survive
    // being unioned with anything, because a min and a max over the two
    // samplings would turn the 20 degrees across the dateline into the 340
    // degrees the other way round. Rather than half-support it, a wrapped box
    // is refused and the caller splits it, which is what a caller has to do
    // anyway to turn the answer into raster windows.
    if (!(bbox[2] >= bbox[0])) {
        OSRDestroySpatialReference(src);
        OSRDestroySpatialReference(dst);
        err.stop("`extent` has xmax below xmin. A box crossing the "
                 "antimeridian has to be split into two before it is "
                 "transformed");
    }
    const double x_span = bbox[2] - bbox[0];
    const double y_span = bbox[3] - bbox[1];

    // One transformation object for both samplings: building it is most of
    // the cost of the call, and moving the points is almost none of it.
    OGRCoordinateTransformationH ct = OCTNewCoordinateTransformation(src, dst);
    OSRDestroySpatialReference(src);
    OSRDestroySpatialReference(dst);
    if (ct == nullptr) {
        err.stop("Could not transform from '" + from + "' to '" + to + "'");
    }

    double lo_x = std::numeric_limits<double>::infinity();
    double lo_y = lo_x;
    double hi_x = -lo_x;
    double hi_y = -lo_x;
    bool any = false;

    const auto keep = [&](double x, double y) {
        if (!std::isfinite(x) || !std::isfinite(y)) {
            return;
        }
        lo_x = std::min(lo_x, x);
        hi_x = std::max(hi_x, x);
        lo_y = std::min(lo_y, y);
        hi_y = std::max(hi_y, y);
        any = true;
    };

    // 1. The boundary walk, with GDAL's own special cases inside it. A walk
    //    that fails or comes back infinite is discarded rather than raised,
    //    because the mesh may still have found the box.
    {
        double w[4] = {0, 0, 0, 0};
        CPLErrorStateBackuper quiet(CPLQuietErrorHandler);
        if (OCTTransformBounds(ct, bbox[0], bbox[1], bbox[2], bbox[3], &w[0],
                               &w[1], &w[2], &w[3], densify)) {
            keep(w[0], w[1]);
            keep(w[2], w[3]);
        }
    }

    // 2. The interior mesh.
    size_t outside = 0;
    size_t sampled = 0;
    if (mesh > 0) {
        const int side = mesh + 1;
        const size_t n = static_cast<size_t>(side) * static_cast<size_t>(side);
        std::vector<double> xs(n);
        std::vector<double> ys(n);
        for (int j = 0; j < side; j++) {
            for (int i = 0; i < side; i++) {
                xs[static_cast<size_t>(j) * side + i] =
                    bbox[0] + x_span * i / mesh;
                ys[static_cast<size_t>(j) * side + i] =
                    bbox[1] + y_span * j / mesh;
            }
        }

        std::vector<int> ok(n, 0);
        {
            CPLErrorStateBackuper quiet(CPLQuietErrorHandler);
            OCTTransformEx(ct, static_cast<int>(n), xs.data(), ys.data(),
                           nullptr, ok.data());
        }
        sampled = n;
        for (size_t i = 0; i < n; i++) {
            if (ok[i] && std::isfinite(xs[i]) && std::isfinite(ys[i])) {
                keep(xs[i], ys[i]);
            } else {
                outside++;
            }
        }
    }

    OCTDestroyCoordinateTransformation(ct);

    if (!any) {
        err.stop("No part of this extent exists in '" + to + "'");
    }

    cpp11::writable::doubles out({lo_x, lo_y, hi_x, hi_y});
    out.names() = {"xmin", "ymin", "xmax", "ymax"};
    // How much of the box has no image in the target. Zero is the ordinary
    // case. Anything above it means the extent returned is the envelope of the
    // part that survived, which is narrower than the box asked for, and a
    // caller picking a window from it should say so rather than hide it.
    out.attr("outside") = cpp11::as_sexp(
        sampled == 0 ? 0.0 : static_cast<double>(outside) / static_cast<double>(sampled));
    err.flush();
    return out;
}
