// Auto-generated by GDAL7 generator - do not edit
#include "gdal7.h"

using namespace cpp11;

// -----------------------------------------------------------------------------
// Capabilities
//
// A binding whose GDAL function is newer than the GDAL in use still exists and
// still dispatches; calling it raises an error naming the release it needs.
// This is how to ask before calling.
// -----------------------------------------------------------------------------

[[cpp11::register]]
list GDAL7_capabilities() {
    writable::strings names;
    writable::strings since;
    writable::logicals available;

    names.push_back("dataset_mark_suppress_on_close");
    since.push_back("3.12.0");
#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3, 12, 0)
    available.push_back(TRUE);
#else
    available.push_back(FALSE);
#endif

    names.push_back("dataset_get_close_reports_progress");
    since.push_back("3.13.0");
#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3, 13, 0)
    available.push_back(TRUE);
#else
    available.push_back(FALSE);
#endif

    names.push_back("dataset_as_mdarray");
    since.push_back("3.12.0");
#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3, 12, 0)
    available.push_back(TRUE);
#else
    available.push_back(FALSE);
#endif

    names.push_back("dataset_is_thread_safe");
    since.push_back("3.10.0");
#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3, 10, 0)
    available.push_back(TRUE);
#else
    available.push_back(FALSE);
#endif

    names.push_back("dataset_get_thread_safe_dataset");
    since.push_back("3.10.0");
#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3, 10, 0)
    available.push_back(TRUE);
#else
    available.push_back(FALSE);
#endif

    return writable::list({
        "binding"_nm = names,
        "gdal"_nm = since,
        "available"_nm = available
    });
}

[[cpp11::register]]
strings GDAL7_gdal_version() {
    return writable::strings({
        r_string(GDALVersionInfo("RELEASE_NAME")),
        r_string(GDALVersionInfo("RELEASE_DATE")),
        r_string(GDALVersionInfo("--version"))
    });
}

