// Auto-generated by GDAL7 generator - do not edit
#include "gdal7.h"

using namespace cpp11;

// -----------------------------------------------------------------------------
// MajorObject bindings
// -----------------------------------------------------------------------------

namespace {

// Fetch the handle, checking both that the external pointer is of the right
// kind and that nothing it depends on has been closed.
inline GDALMajorObjectH get_majorobject_handle(SEXP xp) {
    return gdal7::major_object(xp);
}

}  // namespace

[[cpp11::register]]
cpp11::strings GDAL7_majorobject_get_description(SEXP xp) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    return gdal7::chr(GDALGetDescription(h));
}

[[cpp11::register]]
void GDAL7_majorobject_set_description(SEXP xp, std::string pszNewDesc) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    GDALSetDescription(h, pszNewDesc.c_str());
}

[[cpp11::register]]
cpp11::strings GDAL7_majorobject_get_metadata_domain_list(SEXP xp) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    char** result = GDALGetMetadataDomainList(h);
    strings out = gdal7::from_csl(result);
    CSLDestroy(result);
    return out;
}

[[cpp11::register]]
cpp11::strings GDAL7_majorobject_get_metadata_dict(SEXP xp, std::string pszDomain) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    return gdal7::named_from_csl(GDALGetMetadata(h, pszDomain.c_str()));
}

[[cpp11::register]]
cpp11::strings GDAL7_majorobject_get_metadata_list(SEXP xp, std::string pszDomain) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    return gdal7::from_csl(GDALGetMetadata(h, pszDomain.c_str()));
}

[[cpp11::register]]
int GDAL7_majorobject_set_metadata(SEXP xp, cpp11::list papszMetadata, std::string pszDomain) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    gdal7::ErrorScope err;
    CPLStringList csl = gdal7::to_csl(papszMetadata);
    CPLErr status = GDALSetMetadata(h, csl.List(), pszDomain.c_str());
    if (status != CE_None) {
        err.stop("SetMetadata failed");
    }
    err.flush();
    return static_cast<int>(status);
}

[[cpp11::register]]
int GDAL7_majorobject_set_metadata_2(SEXP xp, std::string pszMetadataString, std::string pszDomain) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    gdal7::ErrorScope err;
    CPLStringList csl;
    csl.AddString(pszMetadataString.c_str());
    CPLErr status = GDALSetMetadata(h, csl.List(), pszDomain.c_str());
    if (status != CE_None) {
        err.stop("SetMetadata failed");
    }
    err.flush();
    return static_cast<int>(status);
}

[[cpp11::register]]
cpp11::strings GDAL7_majorobject_get_metadata_item(SEXP xp, std::string pszName, std::string pszDomain) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    return gdal7::chr(GDALGetMetadataItem(h, pszName.c_str(), pszDomain.c_str()));
}

[[cpp11::register]]
int GDAL7_majorobject_set_metadata_item(SEXP xp, std::string pszName, std::string pszValue, std::string pszDomain) {
    GDALMajorObjectH h = get_majorobject_handle(xp);
    gdal7::ErrorScope err;
    CPLErr status = GDALSetMetadataItem(h, pszName.c_str(), pszValue.c_str(), pszDomain.c_str());
    if (status != CE_None) {
        err.stop("SetMetadataItem failed");
    }
    err.flush();
    return static_cast<int>(status);
}

