// src/GDAL7_driver.cpp
// Manual file - NOT generated by orchestrate.R
// Provides GDALDriver class methods

#include <cpl_minixml.h>

#include "gdal7.h"

namespace {

inline GDALDriverH driver(SEXP xp) {
    return gdal7::get<GDALDriverH>(xp, gdal7::Kind::Driver);
}

// A DCAP_ flag. GDAL records a capability as the string "YES" on the driver
// rather than as a bit, and absence means no.
inline Rboolean has(GDALDriverH drv, const char* capability) {
    const char* value = GDALGetMetadataItem(drv, capability, nullptr);
    return (value != nullptr && EQUAL(value, "YES")) ? TRUE : FALSE;
}

}  // namespace

// ============================================================================
// Driver info methods
// ============================================================================

[[cpp11::register]]
cpp11::strings GDAL7_driver_get_short_name(SEXP xp) {
    return gdal7::chr(GDALGetDriverShortName(driver(xp)));
}

[[cpp11::register]]
cpp11::strings GDAL7_driver_get_long_name(SEXP xp) {
    return gdal7::chr(GDALGetDriverLongName(driver(xp)));
}

[[cpp11::register]]
cpp11::strings GDAL7_driver_get_help_topic(SEXP xp) {
    return gdal7::chr(GDALGetDriverHelpTopic(driver(xp)));
}

// Recursively look for <Option name="..."> in a driver option list document.
static bool option_list_has(const CPLXMLNode* node, const char* option_name) {
    for (const CPLXMLNode* n = node; n != nullptr; n = n->psNext) {
        if (n->eType == CXT_Element && EQUAL(n->pszValue, "Option")) {
            const char* name = CPLGetXMLValue(const_cast<CPLXMLNode*>(n), "name", nullptr);
            if (name && EQUAL(name, option_name)) {
                return true;
            }
        }
        if (n->psChild && option_list_has(n->psChild, option_name)) {
            return true;
        }
    }
    return false;
}

// There is no GDALDriverHasOpenOption() in the GDAL C API, so this is answered
// from the driver's own DMD_OPENOPTIONLIST metadata, which every version has.
[[cpp11::register]]
bool GDAL7_driver_has_open_option(SEXP xp, std::string option_name) {
    GDALDriverH h = driver(xp);

    const char* xml = GDALGetMetadataItem(h, GDAL_DMD_OPENOPTIONLIST, nullptr);
    if (!xml || !*xml) {
        return false;
    }

    gdal7::ErrorScope err;
    CPLXMLNode* root = CPLParseXMLString(xml);
    if (!root) {
        // A driver with an unparseable option list is not worth an error;
        // the honest answer is that the option was not found.
        return false;
    }

    const bool found = option_list_has(root, option_name.c_str());
    CPLDestroyXMLNode(root);
    err.flush();
    return found;
}

// ============================================================================
// Dataset get_driver returns external pointer - need to wrap properly
// ============================================================================

[[cpp11::register]]
SEXP GDAL7_dataset_get_driver_ptr(SEXP xp) {
    GDALDatasetH h = gdal7::get<GDALDatasetH>(xp, gdal7::Kind::Dataset);

    // Drivers belong to GDAL's driver manager for the life of the process, so
    // this one is not tied to the dataset it was reached through.
    return gdal7::wrap(GDALGetDatasetDriver(h), gdal7::Kind::Driver);
}

// ============================================================================
// Top-level driver functions
// ============================================================================

[[cpp11::register]]
int GDAL7_get_driver_count() {
    return GDALGetDriverCount();
}

[[cpp11::register]]
SEXP GDAL7_get_driver_by_name(std::string name) {
    return gdal7::wrap(GDALGetDriverByName(name.c_str()), gdal7::Kind::Driver);
}

[[cpp11::register]]
SEXP GDAL7_get_driver(int index) {
    return gdal7::wrap(GDALGetDriver(index), gdal7::Kind::Driver);
}

// ============================================================================
// Driver capabilities - check metadata for DCAP_* flags
// ============================================================================

[[cpp11::register]]
bool GDAL7_driver_test_capability(SEXP xp, std::string capability) {
    // Check in driver metadata for DCAP_* entries
    const char* value = GDALGetMetadataItem(driver(xp), capability.c_str(), nullptr);
    return value != nullptr && EQUAL(value, "YES");
}

// ============================================================================
// Get driver metadata item (inherits from MajorObject but need driver handle)
// ============================================================================

[[cpp11::register]]
cpp11::strings GDAL7_driver_get_metadata_item(SEXP xp, std::string name, std::string domain) {
    const char* value = GDALGetMetadataItem(driver(xp), name.c_str(),
                                            domain.empty() ? nullptr : domain.c_str());
    return gdal7::chr(value);
}

// ============================================================================
// The whole driver table in one call
// ============================================================================

// Reached one accessor at a time this is seven .Call round trips per driver,
// and a build has a couple of hundred of them. The table is small and the
// questions are all answered from metadata GDAL already has in memory, so it
// is one pass here instead.
[[cpp11::register]]
cpp11::list GDAL7_driver_table() {
    const int count = GDALGetDriverCount();

    cpp11::writable::strings short_name(count);
    cpp11::writable::strings long_name(count);
    cpp11::writable::logicals is_raster(count);
    cpp11::writable::logicals is_vector(count);
    cpp11::writable::logicals is_multidim(count);
    cpp11::writable::logicals can_create(count);
    cpp11::writable::logicals can_copy(count);
    cpp11::writable::logicals can_vsi(count);
    cpp11::writable::strings extensions(count);

    for (int i = 0; i < count; i++) {
        GDALDriverH drv = GDALGetDriver(i);
        const R_xlen_t row = static_cast<R_xlen_t>(i);

        short_name[row] = cpp11::r_string(GDALGetDriverShortName(drv));
        long_name[row] = cpp11::r_string(GDALGetDriverLongName(drv));
        is_raster[row] = has(drv, GDAL_DCAP_RASTER);
        is_vector[row] = has(drv, GDAL_DCAP_VECTOR);
        is_multidim[row] = has(drv, GDAL_DCAP_MULTIDIM_RASTER);
        can_create[row] = has(drv, GDAL_DCAP_CREATE);
        can_copy[row] = has(drv, GDAL_DCAP_CREATECOPY);
        can_vsi[row] = has(drv, GDAL_DCAP_VIRTUALIO);

        const char* ext = GDALGetMetadataItem(drv, GDAL_DMD_EXTENSIONS, nullptr);
        extensions[row] =
            ext == nullptr ? cpp11::r_string(NA_STRING) : cpp11::r_string(ext);
    }

    cpp11::writable::list out;
    out.push_back(cpp11::named_arg("short_name") = short_name);
    out.push_back(cpp11::named_arg("long_name") = long_name);
    out.push_back(cpp11::named_arg("raster") = is_raster);
    out.push_back(cpp11::named_arg("vector") = is_vector);
    out.push_back(cpp11::named_arg("multidim") = is_multidim);
    out.push_back(cpp11::named_arg("create") = can_create);
    out.push_back(cpp11::named_arg("copy") = can_copy);
    out.push_back(cpp11::named_arg("vsi") = can_vsi);
    out.push_back(cpp11::named_arg("extensions") = extensions);
    return out;
}
