// src/GDAL7_create.cpp
// Manual file - NOT generated by orchestrate.R
// Making datasets: what a driver will accept, Create, CreateCopy, and the
// thread-safe view of a dataset.

#include <string>
#include <vector>

#include <cpl_minixml.h>

#include "gdal7.h"

namespace {

inline GDALDatasetH dataset(SEXP xp) {
    return gdal7::get<GDALDatasetH>(xp, gdal7::Kind::Dataset);
}

// A driver by name, or an R error. GDAL returns null for a name it does not
// know and for one whose driver this build left out, which are the same thing
// to a caller, so the message says what it can check.
GDALDriverH driver_by_name(const std::string& name) {
    GDALDriverH drv = GDALGetDriverByName(name.c_str());
    if (drv == nullptr) {
        cpp11::stop("This GDAL has no driver called '%s'. gdal_drivers() lists "
                    "the ones it has",
                    name.c_str());
    }
    return drv;
}

bool driver_can(GDALDriverH drv, const char* capability) {
    const char* value = GDALGetMetadataItem(drv, capability, nullptr);
    return value != nullptr && EQUAL(value, "YES");
}

// ---------------------------------------------------------------------------
// Option lists, as data rather than XML
// ---------------------------------------------------------------------------

// GDAL describes what a driver accepts in an XML document it also validates
// against, so it is the authority on both. Reading it here rather than handing
// the string to R means an option list is a data frame that can be filtered
// and searched, and it costs nothing at run time that the string did not.
//
//   <CreationOptionList>
//     <Option name="COMPRESS" type="string-select" default="NONE">
//       <Value>NONE</Value>
//       <Value>LZW</Value>
//     </Option>
//     <Option name="ZLEVEL" type="int" description="..." min="1" max="9"/>
//   </CreationOptionList>
class OptionList {
 public:
    explicit OptionList(const char* xml) : root_(nullptr) {
        if (xml != nullptr && xml[0] != '\0') {
            root_ = CPLParseXMLString(xml);
        }
    }

    OptionList(const OptionList&) = delete;
    OptionList& operator=(const OptionList&) = delete;

    ~OptionList() {
        if (root_ != nullptr) {
            CPLDestroyXMLNode(root_);
        }
    }

    // The option list document has one element, whose children are the
    // options. A driver with nothing to say has no document at all.
    cpp11::list to_data_frame() const {
        std::vector<const CPLXMLNode*> options;
        for (const CPLXMLNode* list = root_; list != nullptr; list = list->psNext) {
            if (list->eType != CXT_Element) {
                continue;
            }
            for (const CPLXMLNode* node = list->psChild; node != nullptr;
                 node = node->psNext) {
                if (node->eType == CXT_Element && EQUAL(node->pszValue, "Option")) {
                    options.push_back(node);
                }
            }
        }

        const R_xlen_t n = static_cast<R_xlen_t>(options.size());
        cpp11::writable::strings name(n);
        cpp11::writable::strings type(n);
        cpp11::writable::strings description(n);
        cpp11::writable::strings default_value(n);
        cpp11::writable::doubles min(n);
        cpp11::writable::doubles max(n);
        cpp11::writable::logicals required(n);
        cpp11::writable::strings scope(n);
        cpp11::writable::list choices(n);

        for (R_xlen_t i = 0; i < n; i++) {
            const CPLXMLNode* node = options[static_cast<size_t>(i)];
            name[i] = str_or_na(node, "name");
            type[i] = str_or_na(node, "type");
            description[i] = str_or_na(node, "description");
            default_value[i] = str_or_na(node, "default");
            min[i] = num_or_na(node, "min");
            max[i] = num_or_na(node, "max");
            scope[i] = str_or_na(node, "scope");

            const char* req = CPLGetXMLValue(const_cast<CPLXMLNode*>(node),
                                             "required", nullptr);
            required[i] = (req != nullptr && CPLTestBool(req)) ? TRUE : FALSE;

            choices[i] = values_of(node);
        }

        cpp11::writable::list out;
        out.push_back(cpp11::named_arg("name") = name);
        out.push_back(cpp11::named_arg("type") = type);
        out.push_back(cpp11::named_arg("description") = description);
        out.push_back(cpp11::named_arg("default") = default_value);
        out.push_back(cpp11::named_arg("min") = min);
        out.push_back(cpp11::named_arg("max") = max);
        out.push_back(cpp11::named_arg("required") = required);
        out.push_back(cpp11::named_arg("scope") = scope);
        out.push_back(cpp11::named_arg("choices") = choices);
        return out;
    }

 private:
    static cpp11::r_string str_or_na(const CPLXMLNode* node, const char* attr) {
        const char* value =
            CPLGetXMLValue(const_cast<CPLXMLNode*>(node), attr, nullptr);
        return value == nullptr ? cpp11::r_string(NA_STRING) : cpp11::r_string(value);
    }

    static double num_or_na(const CPLXMLNode* node, const char* attr) {
        const char* value =
            CPLGetXMLValue(const_cast<CPLXMLNode*>(node), attr, nullptr);
        return value == nullptr ? NA_REAL : CPLAtof(value);
    }

    // An option with a fixed set of values lists them as <Value> children.
    static cpp11::strings values_of(const CPLXMLNode* node) {
        std::vector<std::string> values;
        for (const CPLXMLNode* child = node->psChild; child != nullptr;
             child = child->psNext) {
            if (child->eType != CXT_Element || !EQUAL(child->pszValue, "Value")) {
                continue;
            }
            const CPLXMLNode* text = child->psChild;
            values.push_back(text != nullptr && text->pszValue != nullptr
                                 ? text->pszValue
                                 : "");
        }

        cpp11::writable::strings out(static_cast<R_xlen_t>(values.size()));
        for (size_t i = 0; i < values.size(); i++) {
            out[static_cast<R_xlen_t>(i)] = cpp11::r_string(values[i]);
        }
        return out;
    }

    CPLXMLNode* root_;
};

// GDAL's own check of an option list against the driver's XML. GDAL says what
// is wrong through the error handler, at warning level, and answers false, so
// the two are put back together here into one R error naming the option. A
// typo caught now costs nothing; caught by the driver it has already made a
// file.
void validate_options(GDALDriverH drv, CSLConstList options,
                      const std::string& driver_name) {
    if (options == nullptr || CSLCount(const_cast<char**>(options)) == 0) {
        return;
    }

    gdal7::ErrorScope err;
    const bool ok = GDALValidateCreationOptions(drv, options) != FALSE;
    if (ok) {
        err.flush();
        return;
    }

    const std::string said = err.notes();
    err.discard();
    if (said.empty()) {
        cpp11::stop("The %s driver does not take these creation options",
                    driver_name.c_str());
    }
    cpp11::stop("The %s driver does not take these creation options: %s",
                driver_name.c_str(), said.c_str());
}

GDALDataType type_by_name(const std::string& name) {
    const GDALDataType type = GDALGetDataTypeByName(name.c_str());
    if (type == GDT_Unknown) {
        cpp11::stop("'%s' is not a GDAL data type. gdal_data_types() lists them",
                    name.c_str());
    }
    return type;
}

}  // namespace

// ============================================================================
// What a driver accepts
// ============================================================================

[[cpp11::register]]
cpp11::list GDAL7_driver_option_list(SEXP xp, std::string which) {
    GDALDriverH drv = gdal7::get<GDALDriverH>(xp, gdal7::Kind::Driver);

    const char* item = which == "open" ? GDAL_DMD_OPENOPTIONLIST
                                       : GDAL_DMD_CREATIONOPTIONLIST;
    OptionList options(GDALGetMetadataItem(drv, item, nullptr));
    return options.to_data_frame();
}

// Whether a list of KEY=VALUE options is one this driver would accept, asked
// before anything is created rather than discovered afterwards.
[[cpp11::register]]
bool GDAL7_driver_validate_creation_options(SEXP xp, cpp11::strings options) {
    GDALDriverH drv = gdal7::get<GDALDriverH>(xp, gdal7::Kind::Driver);
    CPLStringList list = gdal7::to_csl(options);

    // Whatever GDAL has to say about the list is the answer, not a condition:
    // this is the function you call to find out.
    CPLPushErrorHandler(CPLQuietErrorHandler);
    const bool ok = GDALValidateCreationOptions(drv, list.List()) != FALSE;
    CPLPopErrorHandler();
    return ok;
}

// ============================================================================
// Creating
// ============================================================================

[[cpp11::register]]
SEXP GDAL7_create(std::string driver_name, std::string dsn, int xsize, int ysize,
                  int bands, std::string type, cpp11::strings options) {
    GDALDriverH drv = driver_by_name(driver_name);
    if (!driver_can(drv, GDAL_DCAP_CREATE)) {
        cpp11::stop("The %s driver cannot create a dataset from nothing. It may "
                    "still be able to copy one: see gdal_create_copy()",
                    driver_name.c_str());
    }

    if (xsize <= 0 || ysize <= 0) {
        cpp11::stop("A raster needs a positive width and height");
    }
    if (bands < 0) {
        cpp11::stop("`bands` cannot be negative");
    }

    const GDALDataType data_type = type_by_name(type);
    CPLStringList list = gdal7::to_csl(options);
    validate_options(drv, list.List(), driver_name);

    gdal7::ErrorScope err;
    GDALDatasetH h = GDALCreate(drv, dsn.c_str(), xsize, ysize, bands, data_type,
                                list.List());
    if (h == nullptr) {
        err.stop("Could not create " + dsn);
    }

    // Wrapped before the warnings are raised, so a warning turned into an
    // error by options(warn = 2) still leaves R holding something that will
    // close the dataset rather than leaking a half-written file.
    SEXP xp = PROTECT(gdal7::wrap(h, gdal7::Kind::Dataset));
    err.flush();
    UNPROTECT(1);
    return xp;
}

[[cpp11::register]]
SEXP GDAL7_create_copy(std::string driver_name, std::string dsn, SEXP src_xp,
                       bool strict, cpp11::strings options, bool progress) {
    GDALDriverH drv = driver_by_name(driver_name);
    if (!driver_can(drv, GDAL_DCAP_CREATECOPY)) {
        cpp11::stop("The %s driver cannot copy a dataset", driver_name.c_str());
    }

    GDALDatasetH src = dataset(src_xp);
    CPLStringList list = gdal7::to_csl(options);
    validate_options(drv, list.List(), driver_name);

    gdal7::Progress state(progress);

    gdal7::ErrorScope err;
    GDALDatasetH h = GDALCreateCopy(drv, dsn.c_str(), src, strict ? TRUE : FALSE,
                                    list.List(), state.func(), state.data());

    if (h == nullptr) {
        if (state.interrupted()) {
            // A cancelled copy leaves whatever it had written behind, and GDAL
            // does not remove it. Saying so is better than a file that looks
            // finished.
            err.flush();
            cpp11::stop("The copy was interrupted; %s may be incomplete",
                        dsn.c_str());
        }
        err.stop("Could not copy to " + dsn);
    }

    SEXP xp = PROTECT(gdal7::wrap(h, gdal7::Kind::Dataset));
    err.flush();
    UNPROTECT(1);
    return xp;
}

[[cpp11::register]]
void GDAL7_driver_delete(std::string driver_name, std::string dsn) {
    GDALDriverH drv = driver_by_name(driver_name);

    gdal7::ErrorScope err;
    if (GDALDeleteDataset(drv, dsn.c_str()) != CE_None) {
        err.stop("Could not delete " + dsn);
    }
    err.flush();
}

// ============================================================================
// Thread-safe datasets
// ============================================================================

// GDAL 3.10 can hand out a view of a dataset that several threads may read at
// once, which is what lets GDAL parallelise internally. The view is a dataset
// in its own right and is closed like one. Taking a view takes a reference on
// the dataset it was taken from, so from then on both are given back rather
// than closed outright, and whichever goes last deletes the dataset.
// Guarded on the release the table records for these two symbols, the same
// way a generated binding is. The package floor is that release, so this only
// matters to a build made against something older on purpose.
[[cpp11::register]]
SEXP GDAL7_dataset_get_thread_safe_dataset(SEXP xp) {
#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3, 10, 0)
    GDALDatasetH h = dataset(xp);

    gdal7::ErrorScope err;
    GDALDatasetH safe = GDALGetThreadSafeDataset(h, GDAL_OF_RASTER, nullptr);
    if (safe == nullptr) {
        err.stop("Could not make a thread-safe view of this dataset");
    }

    // The view is held by reference, not owned: GDAL says to give it back with
    // GDALReleaseDataset, and it may hand back the dataset itself with one
    // more reference taken rather than a new object.
    SEXP out = PROTECT(
        gdal7::wrap(safe, gdal7::Kind::Dataset, xp, /* by_reference = */ true));
    // Taking the view took a reference on this dataset as well, so it is no
    // longer GDAL7's alone to delete: closing it now gives that reference back
    // and leaves the view holding the last one.
    gdal7::share(xp);
    err.flush();
    UNPROTECT(1);
    return out;
#else
    (void)xp;
    gdal7::unavailable("get_thread_safe_dataset", "3.10.0");
#endif
}

[[cpp11::register]]
bool GDAL7_dataset_is_thread_safe(SEXP xp) {
#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3, 10, 0)
    return GDALDatasetIsThreadSafe(dataset(xp), GDAL_OF_RASTER, nullptr) != FALSE;
#else
    (void)xp;
    gdal7::unavailable("is_thread_safe", "3.10.0");
#endif
}
