// src/GDAL7_info.cpp
// Manual file - NOT generated by orchestrate.R
// Provides raster info methods (dimensions, bands, data types)

#include <cpp11.hpp>
#include <gdal.h>

// ============================================================================
// Dataset dimension properties (not captured by SWIG parser as they're %immutable)
// ============================================================================

[[cpp11::register]]
int GDAL7_dataset_get_raster_xsize(SEXP xp) {
    GDALDatasetH* ptr = reinterpret_cast<GDALDatasetH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid dataset handle");
    }
    return GDALGetRasterXSize(*ptr);
}

[[cpp11::register]]
int GDAL7_dataset_get_raster_ysize(SEXP xp) {
    GDALDatasetH* ptr = reinterpret_cast<GDALDatasetH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid dataset handle");
    }
    return GDALGetRasterYSize(*ptr);
}

[[cpp11::register]]
int GDAL7_dataset_get_raster_count(SEXP xp) {
    GDALDatasetH* ptr = reinterpret_cast<GDALDatasetH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid dataset handle");
    }
    return GDALGetRasterCount(*ptr);
}

// ============================================================================
// Raster Band methods
// ============================================================================

[[cpp11::register]]
SEXP GDAL7_dataset_get_band(SEXP xp, int nBand) {
    GDALDatasetH* ptr = reinterpret_cast<GDALDatasetH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid dataset handle");
    }
    
    GDALRasterBandH band = GDALGetRasterBand(*ptr, nBand);
    if (!band) {
        cpp11::stop("Invalid band number: %d", nBand);
    }
    
    // Return as external pointer (GDALRasterBandH is already a pointer type)
    // Note: Band lifetime is tied to Dataset, so no separate destructor needed
    return cpp11::external_pointer<GDALRasterBandH>(new GDALRasterBandH(band));
}

[[cpp11::register]]
int GDAL7_band_get_xsize(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    return GDALGetRasterBandXSize(*ptr);
}

[[cpp11::register]]
int GDAL7_band_get_ysize(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    return GDALGetRasterBandYSize(*ptr);
}

[[cpp11::register]]
int GDAL7_band_get_band_number(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    return GDALGetBandNumber(*ptr);
}

[[cpp11::register]]
int GDAL7_band_get_data_type(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    return static_cast<int>(GDALGetRasterDataType(*ptr));
}

[[cpp11::register]]
std::string GDAL7_band_get_data_type_name(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    GDALDataType dt = GDALGetRasterDataType(*ptr);
    return std::string(GDALGetDataTypeName(dt));
}

[[cpp11::register]]
cpp11::integers GDAL7_band_get_block_size(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    
    int nBlockXSize, nBlockYSize;
    GDALGetBlockSize(*ptr, &nBlockXSize, &nBlockYSize);
    
    cpp11::writable::integers result(2);
    result[0] = nBlockXSize;
    result[1] = nBlockYSize;
    result.names() = {"x", "y"};
    return result;
}

[[cpp11::register]]
SEXP GDAL7_band_get_nodata_value(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    
    int hasNoData;
    double nodata = GDALGetRasterNoDataValue(*ptr, &hasNoData);
    
    if (hasNoData) {
        return cpp11::as_sexp(nodata);
    } else {
        return R_NilValue;  // Return NULL if no nodata value set
    }
}

[[cpp11::register]]
std::string GDAL7_band_get_description(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    const char* desc = GDALGetDescription(reinterpret_cast<GDALMajorObjectH>(*ptr));
    return desc ? std::string(desc) : std::string("");
}

[[cpp11::register]]
int GDAL7_band_get_color_interpretation(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    return static_cast<int>(GDALGetRasterColorInterpretation(*ptr));
}

[[cpp11::register]]
std::string GDAL7_band_get_color_interpretation_name(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    GDALColorInterp ci = GDALGetRasterColorInterpretation(*ptr);
    return std::string(GDALGetColorInterpretationName(ci));
}

[[cpp11::register]]
SEXP GDAL7_band_get_scale(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    
    int hasScale;
    double scale = GDALGetRasterScale(*ptr, &hasScale);
    
    if (hasScale) {
        return cpp11::as_sexp(scale);
    } else {
        return R_NilValue;
    }
}

[[cpp11::register]]
SEXP GDAL7_band_get_offset(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    
    int hasOffset;
    double offset = GDALGetRasterOffset(*ptr, &hasOffset);
    
    if (hasOffset) {
        return cpp11::as_sexp(offset);
    } else {
        return R_NilValue;
    }
}

[[cpp11::register]]
std::string GDAL7_band_get_unit_type(SEXP xp) {
    GDALRasterBandH* ptr = reinterpret_cast<GDALRasterBandH*>(R_ExternalPtrAddr(xp));
    if (!ptr || !*ptr) {
        cpp11::stop("Invalid band handle");
    }
    const char* unit = GDALGetRasterUnitType(*ptr);
    return unit ? std::string(unit) : std::string("");
}
