// src/GDAL7_algorithm.cpp
// Manual file - NOT generated by orchestrate.R
//
// GDAL's own algorithm registry, which is what the `gdal` command line is
// built on. Binding the registry rather than each utility means the CLI's
// capabilities arrive with GDAL rather than with a GDAL7 release.
//
// The whole file is guarded on GDAL 3.11, where the C API first appears. The
// bindings are registered either way, so cpp11 registration and R dispatch do
// not depend on which GDAL this was built against; on an older one the call
// raises an R error naming the release it would need.

#include <string>
#include <vector>

#include "gdal7.h"

#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3, 11, 0)
#define GDAL7_HAVE_ALGORITHMS 1
#include <gdalalgorithm.h>
#else
#define GDAL7_HAVE_ALGORITHMS 0
#endif

namespace {

#if GDAL7_HAVE_ALGORITHMS

// ---------------------------------------------------------------------------
// Handles that free themselves
// ---------------------------------------------------------------------------

// An algorithm is used once: set arguments, run, take the result. Keeping it
// on the C++ stack rather than handing it to R means there is no way to reach
// a half-configured algorithm from R, and no lifetime to explain.
class Algorithm {
 public:
    Algorithm() : handle_(nullptr) {}
    explicit Algorithm(GDALAlgorithmH h) : handle_(h) {}
    ~Algorithm() { reset(nullptr); }

    Algorithm(const Algorithm&) = delete;
    Algorithm& operator=(const Algorithm&) = delete;

    Algorithm(Algorithm&& other) : handle_(other.handle_) { other.handle_ = nullptr; }

    void reset(GDALAlgorithmH h) {
        if (handle_ != nullptr && handle_ != h) {
            GDALAlgorithmRelease(handle_);
        }
        handle_ = h;
    }

    GDALAlgorithmH get() const { return handle_; }
    explicit operator bool() const { return handle_ != nullptr; }

 private:
    GDALAlgorithmH handle_;
};

class Arg {
 public:
    explicit Arg(GDALAlgorithmArgH h) : handle_(h) {}
    ~Arg() { if (handle_ != nullptr) GDALAlgorithmArgRelease(handle_); }

    Arg(const Arg&) = delete;
    Arg& operator=(const Arg&) = delete;

    GDALAlgorithmArgH get() const { return handle_; }
    explicit operator bool() const { return handle_ != nullptr; }

 private:
    GDALAlgorithmArgH handle_;
};

cpp11::strings owned_names(char** names) {
    cpp11::strings out = gdal7::from_csl(names);
    CSLDestroy(names);
    return out;
}

std::string join_path(cpp11::strings path, R_xlen_t upto) {
    std::string out;
    for (R_xlen_t i = 0; i < upto && i < path.size(); i++) {
        if (!out.empty()) {
            out += " ";
        }
        out += static_cast<std::string>(cpp11::r_string(path[i]));
    }
    return out;
}

// ---------------------------------------------------------------------------
// Walking to an algorithm
// ---------------------------------------------------------------------------

// "raster reproject" is the registry's "raster", then its "reproject"
// sub-algorithm. Walking it by hand rather than with
// GDALAlgorithmRegistryInstantiateAlgFromPath keeps this working on GDAL 3.11,
// where that function does not exist yet.
Algorithm instantiate(cpp11::strings path) {
    if (path.size() == 0) {
        cpp11::stop("An algorithm needs a name, such as \"raster reproject\"");
    }

    GDALAlgorithmRegistryH registry = GDALGetGlobalAlgorithmRegistry();
    if (registry == nullptr) {
        cpp11::stop("GDAL has no algorithm registry");
    }

    const std::string first = cpp11::r_string(path[0]);
    Algorithm alg(GDALAlgorithmRegistryInstantiateAlg(registry, first.c_str()));
    if (!alg) {
        cpp11::strings available = owned_names(GDALAlgorithmRegistryGetAlgNames(registry));
        GDALAlgorithmRegistryRelease(registry);
        std::string names;
        for (R_xlen_t i = 0; i < available.size(); i++) {
            if (!names.empty()) {
                names += ", ";
            }
            names += static_cast<std::string>(cpp11::r_string(available[i]));
        }
        cpp11::stop("GDAL has no algorithm called '%s'. One of: %s",
                    first.c_str(), names.c_str());
    }
    GDALAlgorithmRegistryRelease(registry);

    for (R_xlen_t i = 1; i < path.size(); i++) {
        const std::string step = cpp11::r_string(path[i]);
        GDALAlgorithmH sub =
            GDALAlgorithmInstantiateSubAlgorithm(alg.get(), step.c_str());
        if (sub == nullptr) {
            cpp11::strings available =
                owned_names(GDALAlgorithmGetSubAlgorithmNames(alg.get()));
            std::string names;
            for (R_xlen_t j = 0; j < available.size(); j++) {
                if (!names.empty()) {
                    names += ", ";
                }
                names += static_cast<std::string>(cpp11::r_string(available[j]));
            }
            const std::string so_far = join_path(path, i);
            if (names.empty()) {
                cpp11::stop("'%s' has no sub-algorithms, so '%s' means nothing to it",
                            so_far.c_str(), step.c_str());
            }
            cpp11::stop("'%s' has no '%s'. One of: %s",
                        so_far.c_str(), step.c_str(), names.c_str());
        }
        alg.reset(sub);
    }

    return alg;
}

// ---------------------------------------------------------------------------
// Progress and interruption
// ---------------------------------------------------------------------------

void check_interrupt(void*) { R_CheckUserInterrupt(); }

// Whether the user has pressed Ctrl-C, asked without letting R jump out of
// here. A plain R_CheckUserInterrupt() from inside a GDAL callback would
// longjmp straight past every destructor between here and the top level,
// leaking whatever GDAL has open. R_ToplevelExec catches that jump, so the
// answer comes back as a value and the unwinding is ours to do.
bool interrupt_pending() {
    return R_ToplevelExec(check_interrupt, nullptr) == FALSE;
}

struct Progress {
    bool show;
    bool interrupted;
    int printed;
    bool finished;
};

int CPL_STDCALL report_progress(double complete, const char*, void* data) {
    Progress* state = static_cast<Progress*>(data);

    if (interrupt_pending()) {
        state->interrupted = true;
        // Returning false is how a GDAL progress function says stop. The
        // algorithm then fails cleanly and the R error is raised afterwards.
        return FALSE;
    }

    if (state->show) {
        const int width = 40;
        int target = static_cast<int>(complete * width);
        if (target > width) {
            target = width;
        }
        for (; state->printed < target; state->printed++) {
            Rprintf("=");
        }
        // An algorithm made of several steps reports completion once per
        // step, and one bar wants one newline.
        if (complete >= 1.0 && !state->finished) {
            state->finished = true;
            Rprintf("\n");
        }
    }
    return TRUE;
}

// ---------------------------------------------------------------------------
// Setting arguments
// ---------------------------------------------------------------------------

[[noreturn]] void wrong_type(const std::string& name, GDALAlgorithmArgType type,
                             const char* wanted) {
    cpp11::stop("Argument '%s' is %s, so it needs %s", name.c_str(),
                GDALAlgorithmArgTypeName(type), wanted);
}

std::string one_string(SEXP value, const std::string& name,
                       GDALAlgorithmArgType type) {
    if (TYPEOF(value) != STRSXP || Rf_xlength(value) != 1 ||
        STRING_ELT(value, 0) == NA_STRING) {
        wrong_type(name, type, "a single string");
    }
    return static_cast<std::string>(cpp11::r_string(STRING_ELT(value, 0)));
}

double one_number(SEXP value, const std::string& name,
                  GDALAlgorithmArgType type) {
    if (Rf_xlength(value) != 1 || !Rf_isNumeric(value)) {
        wrong_type(name, type, "a single number");
    }
    const double out = Rf_asReal(value);
    if (!R_FINITE(out)) {
        wrong_type(name, type, "a finite number");
    }
    return out;
}

std::vector<double> numbers(SEXP value, const std::string& name,
                            GDALAlgorithmArgType type) {
    if (!Rf_isNumeric(value)) {
        wrong_type(name, type, "numbers");
    }
    cpp11::doubles values(cpp11::as_doubles(value));
    std::vector<double> out;
    out.reserve(static_cast<size_t>(values.size()));
    for (R_xlen_t i = 0; i < values.size(); i++) {
        if (!R_FINITE(values[i])) {
            wrong_type(name, type, "finite numbers");
        }
        out.push_back(values[i]);
    }
    return out;
}

// A dataset argument takes either a GDAL7 dataset, which is handed over as an
// object so nothing is reopened, or a string, which GDAL opens itself.
bool set_dataset(GDALAlgorithmArgH arg, SEXP value, const std::string& name) {
    if (gdal7::is_handle(value)) {
        return GDALAlgorithmArgSetDataset(
            arg, gdal7::get<GDALDatasetH>(value, gdal7::Kind::Dataset));
    }
    const std::string dsn = one_string(value, name, GAAT_DATASET);
    return GDALAlgorithmArgSetAsString(arg, dsn.c_str());
}

void set_argument(GDALAlgorithmArgH arg, SEXP value, const std::string& name) {
    const GDALAlgorithmArgType type = GDALAlgorithmArgGetType(arg);
    bool ok = false;

    switch (type) {
        case GAAT_BOOLEAN: {
            if (Rf_xlength(value) != 1 || TYPEOF(value) != LGLSXP ||
                LOGICAL(value)[0] == NA_LOGICAL) {
                wrong_type(name, type, "TRUE or FALSE");
            }
            ok = GDALAlgorithmArgSetAsBoolean(arg, LOGICAL(value)[0] != 0);
            break;
        }
        case GAAT_STRING: {
            ok = GDALAlgorithmArgSetAsString(arg,
                                             one_string(value, name, type).c_str());
            break;
        }
        case GAAT_INTEGER: {
            const double number = one_number(value, name, type);
            if (number != static_cast<double>(static_cast<int>(number))) {
                wrong_type(name, type, "a whole number");
            }
            ok = GDALAlgorithmArgSetAsInteger(arg, static_cast<int>(number));
            break;
        }
        case GAAT_REAL: {
            ok = GDALAlgorithmArgSetAsDouble(arg, one_number(value, name, type));
            break;
        }
        case GAAT_DATASET: {
            ok = set_dataset(arg, value, name);
            break;
        }
        case GAAT_STRING_LIST: {
            if (TYPEOF(value) != STRSXP) {
                wrong_type(name, type, "strings");
            }
            CPLStringList csl = gdal7::to_csl(cpp11::strings(value));
            ok = GDALAlgorithmArgSetAsStringList(arg, csl.List());
            break;
        }
        case GAAT_INTEGER_LIST: {
            const std::vector<double> values = numbers(value, name, type);
            std::vector<int> whole;
            whole.reserve(values.size());
            for (double number : values) {
                if (number != static_cast<double>(static_cast<int>(number))) {
                    wrong_type(name, type, "whole numbers");
                }
                whole.push_back(static_cast<int>(number));
            }
            ok = GDALAlgorithmArgSetAsIntegerList(arg, whole.size(), whole.data());
            break;
        }
        case GAAT_REAL_LIST: {
            const std::vector<double> values = numbers(value, name, type);
            ok = GDALAlgorithmArgSetAsDoubleList(arg, values.size(), values.data());
            break;
        }
        case GAAT_DATASET_LIST: {
            if (TYPEOF(value) == STRSXP) {
                CPLStringList csl = gdal7::to_csl(cpp11::strings(value));
                ok = GDALAlgorithmArgSetDatasetNames(arg, csl.List());
                break;
            }
            // A single dataset is the common case and reads naturally, so
            // it is accepted where a list is declared.
            if (gdal7::is_handle(value)) {
                GDALDatasetH one =
                    gdal7::get<GDALDatasetH>(value, gdal7::Kind::Dataset);
                ok = GDALAlgorithmArgSetDatasets(arg, 1, &one);
                break;
            }
            if (TYPEOF(value) != VECSXP) {
                wrong_type(name, type, "a dataset, a list of them, or their names");
            }
            cpp11::list items(value);
            std::vector<GDALDatasetH> datasets;
            datasets.reserve(static_cast<size_t>(items.size()));
            for (R_xlen_t i = 0; i < items.size(); i++) {
                SEXP item = items[i];
                if (!gdal7::is_handle(item)) {
                    wrong_type(name, type,
                               "a dataset, a list of them, or their names");
                }
                datasets.push_back(
                    gdal7::get<GDALDatasetH>(item, gdal7::Kind::Dataset));
            }
            ok = GDALAlgorithmArgSetDatasets(arg, datasets.size(), datasets.data());
            break;
        }
    }

    if (!ok) {
        cpp11::stop("GDAL would not accept the value given for '%s'", name.c_str());
    }
}

#endif  // GDAL7_HAVE_ALGORITHMS

}  // namespace

// ============================================================================
// What this build can do
// ============================================================================

// Whether the GDAL this was built against has the algorithm API at all. The R
// side asks before offering anything that depends on it, and the tests skip on
// the answer rather than failing.
[[cpp11::register]]
bool GDAL7_algorithms_available() {
    return GDAL7_HAVE_ALGORITHMS != 0;
}

// ============================================================================
// The registry
// ============================================================================

[[cpp11::register]]
cpp11::strings GDAL7_algorithm_names(cpp11::strings path) {
#if GDAL7_HAVE_ALGORITHMS
    gdal7::ErrorScope err;

    if (path.size() == 0) {
        GDALAlgorithmRegistryH registry = GDALGetGlobalAlgorithmRegistry();
        if (registry == nullptr) {
            err.stop("GDAL has no algorithm registry");
        }
        cpp11::strings out = owned_names(GDALAlgorithmRegistryGetAlgNames(registry));
        GDALAlgorithmRegistryRelease(registry);
        err.flush();
        return out;
    }

    Algorithm alg = instantiate(path);
    cpp11::strings out = owned_names(GDALAlgorithmGetSubAlgorithmNames(alg.get()));
    err.flush();
    return out;
#else
    (void)path;
    gdal7::unavailable("gdal_algorithms", "3.11.0");
#endif
}

[[cpp11::register]]
cpp11::list GDAL7_algorithm_info(cpp11::strings path) {
#if GDAL7_HAVE_ALGORITHMS
    gdal7::ErrorScope err;
    Algorithm alg = instantiate(path);
    GDALAlgorithmH h = alg.get();

    cpp11::strings arg_names = owned_names(GDALAlgorithmGetArgNames(h));
    const R_xlen_t count = arg_names.size();

    cpp11::writable::strings types(count);
    cpp11::writable::strings descriptions(count);
    cpp11::writable::logicals required(count);
    cpp11::writable::logicals positional(count);
    cpp11::writable::logicals is_input(count);
    cpp11::writable::logicals is_output(count);
    cpp11::writable::list choices(count);

    for (R_xlen_t i = 0; i < count; i++) {
        const std::string name = cpp11::r_string(arg_names[i]);
        Arg arg(GDALAlgorithmGetArg(h, name.c_str()));
        if (!arg) {
            // GDAL listed the name, so this cannot normally happen; saying so
            // beats a row of silently empty cells.
            types[i] = NA_STRING;
            descriptions[i] = NA_STRING;
            required[i] = NA_LOGICAL;
            positional[i] = NA_LOGICAL;
            is_input[i] = NA_LOGICAL;
            is_output[i] = NA_LOGICAL;
            choices[i] = cpp11::writable::strings(static_cast<R_xlen_t>(0));
            continue;
        }

        types[i] = cpp11::r_string(
            GDALAlgorithmArgTypeName(GDALAlgorithmArgGetType(arg.get())));
        const char* description = GDALAlgorithmArgGetDescription(arg.get());
        descriptions[i] = cpp11::r_string(description == nullptr ? "" : description);
        required[i] = GDALAlgorithmArgIsRequired(arg.get()) ? TRUE : FALSE;
        positional[i] = GDALAlgorithmArgIsPositional(arg.get()) ? TRUE : FALSE;
        is_input[i] = GDALAlgorithmArgIsInput(arg.get()) ? TRUE : FALSE;
        is_output[i] = GDALAlgorithmArgIsOutput(arg.get()) ? TRUE : FALSE;
        choices[i] = owned_names(GDALAlgorithmArgGetChoices(arg.get()));
    }

    cpp11::writable::list arguments;
    arguments.push_back(cpp11::named_arg("name") = arg_names);
    arguments.push_back(cpp11::named_arg("type") = types);
    arguments.push_back(cpp11::named_arg("description") = descriptions);
    arguments.push_back(cpp11::named_arg("required") = required);
    arguments.push_back(cpp11::named_arg("positional") = positional);
    arguments.push_back(cpp11::named_arg("input") = is_input);
    arguments.push_back(cpp11::named_arg("output") = is_output);
    arguments.push_back(cpp11::named_arg("choices") = choices);

    cpp11::writable::list out;
    out.push_back(cpp11::named_arg("name") = gdal7::chr(GDALAlgorithmGetName(h)));
    out.push_back(cpp11::named_arg("description") =
                      gdal7::chr(GDALAlgorithmGetDescription(h)));
    out.push_back(cpp11::named_arg("long_description") =
                      gdal7::chr(GDALAlgorithmGetLongDescription(h)));
    out.push_back(cpp11::named_arg("url") =
                      gdal7::chr(GDALAlgorithmGetHelpFullURL(h)));
    out.push_back(cpp11::named_arg("sub_algorithms") =
                      owned_names(GDALAlgorithmGetSubAlgorithmNames(h)));
    out.push_back(cpp11::named_arg("arguments") = arguments);

    err.flush();
    return out;
#else
    (void)path;
    gdal7::unavailable("gdal_algorithm_info", "3.11.0");
#endif
}

// ============================================================================
// Running
// ============================================================================

[[cpp11::register]]
SEXP GDAL7_algorithm_run(cpp11::strings path, cpp11::list args, bool progress) {
#if GDAL7_HAVE_ALGORITHMS
    gdal7::ErrorScope err;
    Algorithm alg = instantiate(path);
    GDALAlgorithmH h = alg.get();

    if (args.size() > 0) {
        SEXP names_sexp = Rf_getAttrib(args, R_NamesSymbol);
        if (names_sexp == R_NilValue) {
            cpp11::stop("Every algorithm argument has to be named");
        }
        cpp11::strings names(names_sexp);

        for (R_xlen_t i = 0; i < args.size(); i++) {
            const std::string name = cpp11::r_string(names[i]);
            if (name.empty()) {
                cpp11::stop("Every algorithm argument has to be named");
            }

            Arg arg(GDALAlgorithmGetArg(h, name.c_str()));
            if (!arg) {
                cpp11::strings known = owned_names(GDALAlgorithmGetArgNames(h));
                std::string listed;
                for (R_xlen_t j = 0; j < known.size(); j++) {
                    if (!listed.empty()) {
                        listed += ", ";
                    }
                    listed += static_cast<std::string>(cpp11::r_string(known[j]));
                }
                cpp11::stop("'%s' has no argument called '%s'. One of: %s",
                            join_path(path, path.size()).c_str(), name.c_str(),
                            listed.c_str());
            }
            set_argument(arg.get(), args[i], name);
        }
    }

    Progress state;
    state.show = progress;
    state.interrupted = false;
    state.printed = 0;
    state.finished = false;

    const bool ran = GDALAlgorithmRun(h, report_progress, &state);

    if (state.interrupted) {
        // The condition R would have raised was swallowed to get out of GDAL
        // in one piece, so it is raised here instead, now that everything GDAL
        // had open has been given back.
        cpp11::stop("The algorithm was interrupted");
    }
    if (!ran) {
        err.stop("The algorithm would not run");
    }

    // What the algorithm produced lives in its output argument. Which of the
    // two answers to give depends on whether that output has a name: an
    // algorithm asked for an in-memory result was given an empty one.
    SEXP result = R_NilValue;
    bool found_output = false;
    std::string output_name;

    cpp11::strings arg_names = owned_names(GDALAlgorithmGetArgNames(h));
    for (R_xlen_t i = 0; i < arg_names.size() && !found_output; i++) {
        const std::string name = cpp11::r_string(arg_names[i]);
        Arg arg(GDALAlgorithmGetArg(h, name.c_str()));
        if (!arg || GDALAlgorithmArgGetType(arg.get()) != GAAT_DATASET ||
            !GDALAlgorithmArgIsOutput(arg.get())) {
            continue;
        }
        GDALArgDatasetValueH value = GDALAlgorithmArgGetAsDatasetValue(arg.get());
        if (value == nullptr) {
            continue;
        }

        const char* written_to = GDALArgDatasetValueGetName(value);
        output_name = written_to == nullptr ? "" : written_to;
        found_output = true;

        // Whether the result is a file or lives in memory is not a question of
        // what the output was called: a pipeline's in-memory result is named
        // too. It is a question of whether there is a file behind it.
        GDALDatasetH dataset = GDALArgDatasetValueGetDatasetRef(value);
        if (dataset == nullptr) {
            break;
        }

        char** files = GDALGetFileList(dataset);
        const bool on_disk = files != nullptr && CSLCount(files) > 0;
        CSLDestroy(files);

        if (on_disk) {
            // Holding a reference here would leave Finalize with nothing to
            // flush and the file half written, so the path is the honest
            // answer and GDAL closes the dataset properly.
            break;
        }

        // In memory. The reference is taken before Finalize, which would
        // otherwise drop the last one and delete the dataset.
        result = gdal7::wrap(GDALArgDatasetValueGetDatasetIncreaseRefCount(value),
                             gdal7::Kind::Dataset, R_NilValue,
                             /* by_reference = */ true);
    }

    PROTECT(result);
    const bool finalized = GDALAlgorithmFinalize(h);
    if (!finalized) {
        UNPROTECT(1);
        err.stop("The algorithm ran but could not finish writing its result");
    }
    UNPROTECT(1);

    if (result == R_NilValue && !output_name.empty()) {
        cpp11::strings out = gdal7::chr(output_name.c_str());
        err.flush();
        return out;
    }

    err.flush();
    return result;
#else
    (void)path;
    (void)args;
    (void)progress;
    gdal7::unavailable("gdal_run", "3.11.0");
#endif
}
