// src/GDAL7_multidim.cpp
// Manual file - NOT generated by orchestrate.R
// Provides GDALGroup and multidimensional API methods

#include "gdal7.h"

namespace {

inline GDALGroupH group(SEXP xp) {
    return gdal7::get<GDALGroupH>(xp, gdal7::Kind::Group);
}

inline GDALMDArrayH mdarray(SEXP xp) {
    return gdal7::get<GDALMDArrayH>(xp, gdal7::Kind::MDArray);
}

// Group and array names come back as an owned string list.
cpp11::strings owned_names(char** names) {
    cpp11::strings out = gdal7::from_csl(names);
    CSLDestroy(names);
    return out;
}

}  // namespace

// ============================================================================
// Dataset multidim methods
// ============================================================================

[[cpp11::register]]
SEXP GDAL7_dataset_get_root_group(SEXP xp) {
    GDALDatasetH h = gdal7::get<GDALDatasetH>(xp, gdal7::Kind::Dataset);

    gdal7::ErrorScope err;
    GDALGroupH grp = GDALDatasetGetRootGroup(h);
    if (!grp) {
        // A dataset opened without GDAL_OF_MULTIDIM_RASTER has no root group.
        // That is a question with an answer, not a failure.
        err.flush();
        return R_NilValue;
    }

    // The group carries its own GDALGroupRelease, and names the dataset as its
    // parent so the dataset cannot be closed out from under it.
    SEXP out = PROTECT(gdal7::wrap(grp, gdal7::Kind::Group, xp));
    err.flush();
    UNPROTECT(1);
    return out;
}

// ============================================================================
// Group info methods
// ============================================================================

[[cpp11::register]]
cpp11::strings GDAL7_group_get_name(SEXP xp) {
    return gdal7::chr(GDALGroupGetName(group(xp)));
}

[[cpp11::register]]
cpp11::strings GDAL7_group_get_full_name(SEXP xp) {
    return gdal7::chr(GDALGroupGetFullName(group(xp)));
}

// ============================================================================
// Group navigation - arrays
// ============================================================================

[[cpp11::register]]
cpp11::strings GDAL7_group_get_mdarray_names(SEXP xp) {
    GDALGroupH h = group(xp);

    gdal7::ErrorScope err;
    cpp11::strings out = owned_names(GDALGroupGetMDArrayNames(h, nullptr));
    err.flush();
    return out;
}

[[cpp11::register]]
SEXP GDAL7_group_open_mdarray(SEXP xp, std::string name) {
    GDALGroupH h = group(xp);

    gdal7::ErrorScope err;
    GDALMDArrayH arr = GDALGroupOpenMDArray(h, name.c_str(), nullptr);
    if (!arr) {
        // A name that is not there is answered with NULL, as documented. What
        // GDAL said about it becomes an R warning rather than stderr noise.
        err.flush();
        return R_NilValue;
    }

    SEXP out = PROTECT(gdal7::wrap(arr, gdal7::Kind::MDArray, xp));
    err.flush();
    UNPROTECT(1);
    return out;
}

// ============================================================================
// Group navigation - subgroups
// ============================================================================

[[cpp11::register]]
cpp11::strings GDAL7_group_get_group_names(SEXP xp) {
    GDALGroupH h = group(xp);

    gdal7::ErrorScope err;
    cpp11::strings out = owned_names(GDALGroupGetGroupNames(h, nullptr));
    err.flush();
    return out;
}

[[cpp11::register]]
SEXP GDAL7_group_open_group(SEXP xp, std::string name) {
    GDALGroupH h = group(xp);

    gdal7::ErrorScope err;
    GDALGroupH grp = GDALGroupOpenGroup(h, name.c_str(), nullptr);
    if (!grp) {
        err.flush();
        return R_NilValue;
    }

    SEXP out = PROTECT(gdal7::wrap(grp, gdal7::Kind::Group, xp));
    err.flush();
    UNPROTECT(1);
    return out;
}

// ============================================================================
// Group release
// ============================================================================

[[cpp11::register]]
void GDAL7_group_release(SEXP xp) {
    gdal7::close(xp, gdal7::Kind::Group);
}

// ============================================================================
// MDArray info methods
// ============================================================================

[[cpp11::register]]
cpp11::strings GDAL7_mdarray_get_name(SEXP xp) {
    return gdal7::chr(GDALMDArrayGetName(mdarray(xp)));
}

[[cpp11::register]]
cpp11::strings GDAL7_mdarray_get_full_name(SEXP xp) {
    return gdal7::chr(GDALMDArrayGetFullName(mdarray(xp)));
}

[[cpp11::register]]
int GDAL7_mdarray_get_dimension_count(SEXP xp) {
    return static_cast<int>(GDALMDArrayGetDimensionCount(mdarray(xp)));
}

[[cpp11::register]]
cpp11::list GDAL7_mdarray_get_dimensions(SEXP xp) {
    GDALMDArrayH h = mdarray(xp);

    size_t count = 0;
    GDALDimensionH* dims = GDALMDArrayGetDimensions(h, &count);

    cpp11::writable::strings names(static_cast<R_xlen_t>(count));
    cpp11::writable::doubles sizes(static_cast<R_xlen_t>(count));

    for (size_t i = 0; i < count; i++) {
        names[i] = cpp11::r_string(GDALDimensionGetName(dims[i]));
        sizes[i] = static_cast<double>(GDALDimensionGetSize(dims[i]));
    }

    GDALReleaseDimensions(dims, count);

    // Built empty and pushed into: a list sized `count` up front would have
    // left `count` NULLs in front of the two columns.
    cpp11::writable::list result;
    result.push_back(cpp11::named_arg("name") = names);
    result.push_back(cpp11::named_arg("size") = sizes);
    return result;
}

[[cpp11::register]]
cpp11::strings GDAL7_mdarray_get_data_type_name(SEXP xp) {
    GDALExtendedDataTypeH dt = GDALMDArrayGetDataType(mdarray(xp));
    if (dt == nullptr) {
        return gdal7::chr(nullptr);
    }

    // GDALExtendedDataTypeGetName() only names a type the format gave a name
    // to, which for a plain numeric array is the empty string. The useful
    // answer there is the ordinary GDAL data type underneath.
    const char* name = GDALExtendedDataTypeGetName(dt);
    if ((name == nullptr || *name == '\0') &&
        GDALExtendedDataTypeGetClass(dt) == GEDTC_NUMERIC) {
        name = GDALGetDataTypeName(GDALExtendedDataTypeGetNumericDataType(dt));
    }

    cpp11::strings out = gdal7::chr(name);
    GDALExtendedDataTypeRelease(dt);
    return out;
}

[[cpp11::register]]
cpp11::strings GDAL7_mdarray_get_unit(SEXP xp) {
    return gdal7::chr(GDALMDArrayGetUnit(mdarray(xp)));
}

[[cpp11::register]]
SEXP GDAL7_mdarray_get_nodata_value(SEXP xp) {
    int hasNoData = 0;
    double nodata = GDALMDArrayGetNoDataValueAsDouble(mdarray(xp), &hasNoData);

    if (!hasNoData) {
        return R_NilValue;
    }
    return cpp11::as_sexp(nodata);
}

[[cpp11::register]]
void GDAL7_mdarray_release(SEXP xp) {
    gdal7::close(xp, gdal7::Kind::MDArray);
}
