// src/GDAL7_rasterio.cpp
// Manual file - NOT generated by orchestrate.R
// Geotransforms, overviews and windowed reads.

#include <algorithm>
#include <cmath>
#include <string>
#include <vector>

#include "gdal7.h"

namespace {

inline GDALDatasetH dataset(SEXP xp) {
    return gdal7::get<GDALDatasetH>(xp, gdal7::Kind::Dataset);
}

inline GDALRasterBandH band(SEXP xp) {
    return gdal7::get<GDALRasterBandH>(xp, gdal7::Kind::Band);
}

// A geotransform is always the same six numbers, so it is worth insisting on
// that rather than letting a short vector reach GDAL.
void copy_geotransform(cpp11::doubles gt, double out[6]) {
    if (gt.size() != 6) {
        cpp11::stop("A geotransform is 6 numbers, got %d", static_cast<int>(gt.size()));
    }
    for (int i = 0; i < 6; i++) {
        out[i] = gt[i];
    }
}

GDALRIOResampleAlg resample_from_name(const std::string& name) {
    if (EQUAL(name.c_str(), "nearest")) return GRIORA_NearestNeighbour;
    if (EQUAL(name.c_str(), "bilinear")) return GRIORA_Bilinear;
    if (EQUAL(name.c_str(), "cubic")) return GRIORA_Cubic;
    if (EQUAL(name.c_str(), "cubicspline")) return GRIORA_CubicSpline;
    if (EQUAL(name.c_str(), "lanczos")) return GRIORA_Lanczos;
    if (EQUAL(name.c_str(), "average")) return GRIORA_Average;
    if (EQUAL(name.c_str(), "mode")) return GRIORA_Mode;
    if (EQUAL(name.c_str(), "gauss")) return GRIORA_Gauss;
    if (EQUAL(name.c_str(), "rms")) return GRIORA_RMS;

    cpp11::stop("Unknown resampling algorithm '%s'. One of: nearest, bilinear, "
                "cubic, cubicspline, lanczos, average, mode, gauss, rms",
                name.c_str());
}

}  // namespace

// ============================================================================
// Geotransform
// ============================================================================

[[cpp11::register]]
SEXP GDAL7_dataset_get_geotransform(SEXP xp) {
    GDALDatasetH h = dataset(xp);

    double gt[6];
    gdal7::ErrorScope err;
    if (GDALGetGeoTransform(h, gt) != CE_None) {
        // GDAL fills the identity and reports failure when a dataset carries no
        // geotransform. NULL says that plainly; the identity would not.
        err.flush();
        return R_NilValue;
    }
    err.flush();

    cpp11::writable::doubles out(6);
    for (int i = 0; i < 6; i++) {
        out[i] = gt[i];
    }
    out.names() = {"origin_x", "pixel_width", "row_rotation",
                   "origin_y", "column_rotation", "pixel_height"};
    return out;
}

[[cpp11::register]]
void GDAL7_dataset_set_geotransform(SEXP xp, cpp11::doubles gt) {
    GDALDatasetH h = dataset(xp);

    double values[6];
    copy_geotransform(gt, values);

    gdal7::ErrorScope err;
    if (GDALSetGeoTransform(h, values) != CE_None) {
        err.stop("Could not set the geotransform");
    }
    err.flush();
}

// Pixel/line to georeferenced, for whole vectors at a time rather than one
// point per call.
[[cpp11::register]]
cpp11::list GDAL7_apply_geotransform(cpp11::doubles gt, cpp11::doubles pixel,
                                     cpp11::doubles line) {
    double values[6];
    copy_geotransform(gt, values);

    if (pixel.size() != line.size()) {
        cpp11::stop("`pixel` and `line` must be the same length");
    }

    const R_xlen_t n = pixel.size();
    cpp11::writable::doubles x(n);
    cpp11::writable::doubles y(n);

    for (R_xlen_t i = 0; i < n; i++) {
        double gx = NA_REAL;
        double gy = NA_REAL;
        if (!ISNA(pixel[i]) && !ISNA(line[i])) {
            GDALApplyGeoTransform(values, pixel[i], line[i], &gx, &gy);
        }
        x[i] = gx;
        y[i] = gy;
    }

    cpp11::writable::list out;
    out.push_back(cpp11::named_arg("x") = x);
    out.push_back(cpp11::named_arg("y") = y);
    return out;
}

[[cpp11::register]]
SEXP GDAL7_inv_geotransform(cpp11::doubles gt) {
    double values[6];
    copy_geotransform(gt, values);

    double inverse[6];
    if (!GDALInvGeoTransform(values, inverse)) {
        // A geotransform with a zero determinant cannot be inverted, which is
        // an answer rather than an error.
        return R_NilValue;
    }

    cpp11::writable::doubles out(6);
    for (int i = 0; i < 6; i++) {
        out[i] = inverse[i];
    }
    return out;
}

// ============================================================================
// Overviews
// ============================================================================

[[cpp11::register]]
int GDAL7_band_get_overview_count(SEXP xp) {
    return GDALGetOverviewCount(band(xp));
}

[[cpp11::register]]
SEXP GDAL7_band_get_overview(SEXP xp, int index) {
    GDALRasterBandH h = band(xp);

    const int count = GDALGetOverviewCount(h);
    if (index < 0 || index >= count) {
        cpp11::stop("Overview %d is out of range; this band has %d", index, count);
    }

    GDALRasterBandH ov = GDALGetOverview(h, index);
    if (!ov) {
        cpp11::stop("Could not open overview %d", index);
    }

    // An overview belongs to the same dataset as the band it came from, and
    // passing the band as the parent carries that dataset's record across.
    return gdal7::wrap(ov, gdal7::Kind::Band, xp);
}

// The size of each overview level, which is what decides which level a read at
// a given output size will actually touch.
[[cpp11::register]]
cpp11::list GDAL7_band_get_overview_sizes(SEXP xp) {
    GDALRasterBandH h = band(xp);

    const int count = GDALGetOverviewCount(h);
    cpp11::writable::integers xs(count);
    cpp11::writable::integers ys(count);

    for (int i = 0; i < count; i++) {
        GDALRasterBandH ov = GDALGetOverview(h, i);
        xs[i] = ov ? GDALGetRasterBandXSize(ov) : NA_INTEGER;
        ys[i] = ov ? GDALGetRasterBandYSize(ov) : NA_INTEGER;
    }

    cpp11::writable::list out;
    out.push_back(cpp11::named_arg("xsize") = xs);
    out.push_back(cpp11::named_arg("ysize") = ys);
    return out;
}

// ============================================================================
// Windowed reads
// ============================================================================

// Read a window of a band at a chosen output size.
//
// This is GDALRasterIOEx rather than plain RasterIO: the window may be
// fractional, the output size is independent of it, and the resampling is
// chosen by the caller. Those three together are what let a huge raster over
// /vsicurl/ be read at a useful size without fetching all of it, because GDAL
// picks an overview level to satisfy the output size.
[[cpp11::register]]
cpp11::doubles GDAL7_band_read(SEXP xp, cpp11::doubles window,
                               cpp11::integers out_size, std::string resample) {
    GDALRasterBandH h = band(xp);

    if (window.size() != 4) {
        cpp11::stop("`window` is 4 numbers: xoff, yoff, xsize, ysize");
    }
    if (out_size.size() != 2) {
        cpp11::stop("`out_size` is 2 numbers: the output width and height");
    }

    const double dfXOff = window[0];
    const double dfYOff = window[1];
    const double dfXSize = window[2];
    const double dfYSize = window[3];

    if (!(dfXSize > 0) || !(dfYSize > 0)) {
        cpp11::stop("The window must have a positive width and height");
    }

    const int nXOut = out_size[0];
    const int nYOut = out_size[1];
    if (nXOut <= 0 || nYOut <= 0) {
        cpp11::stop("`out_size` must be positive");
    }

    GDALRasterIOExtraArg extra;
    INIT_RASTERIO_EXTRA_ARG(extra);
    extra.eResampleAlg = resample_from_name(resample);

    // The integer window GDAL is given has to cover the floating point one,
    // which is what the floating point fields then refine.
    const int nXOff = static_cast<int>(std::floor(dfXOff));
    const int nYOff = static_cast<int>(std::floor(dfYOff));
    const int nXSize = static_cast<int>(std::ceil(dfXOff + dfXSize)) - nXOff;
    const int nYSize = static_cast<int>(std::ceil(dfYOff + dfYSize)) - nYOff;

    extra.bFloatingPointWindowValidity = TRUE;
    extra.dfXOff = dfXOff;
    extra.dfYOff = dfYOff;
    extra.dfXSize = dfXSize;
    extra.dfYSize = dfYSize;

    // Values come back as double whatever the band holds, so one return type
    // covers every band type. Int64 beyond 2^53 is the one case that loses
    // precision.
    cpp11::writable::doubles out(static_cast<R_xlen_t>(nXOut) * nYOut);

    gdal7::ErrorScope err;
    const CPLErr status = GDALRasterIOEx(
        h, GF_Read, nXOff, nYOff, nXSize, nYSize,
        REAL(out), nXOut, nYOut, GDT_Float64, 0, 0, &extra);

    if (status != CE_None) {
        err.stop("Could not read the raster window");
    }
    err.flush();

    return out;
}

// Read the same window from several bands in one call. Band by band this is
// one round trip each and, over a network, one set of range requests each;
// GDAL issues them together when it is asked for the bands at once.
[[cpp11::register]]
cpp11::list GDAL7_dataset_read(SEXP xp, cpp11::integers bands, cpp11::doubles window,
                               cpp11::integers out_size, std::string resample) {
    GDALDatasetH h = dataset(xp);

    if (bands.size() < 1) {
        cpp11::stop("At least one band is needed");
    }
    if (window.size() != 4) {
        cpp11::stop("`window` is 4 numbers: xoff, yoff, xsize, ysize");
    }
    if (out_size.size() != 2) {
        cpp11::stop("`out_size` is 2 numbers: the output width and height");
    }

    const double dfXOff = window[0];
    const double dfYOff = window[1];
    const double dfXSize = window[2];
    const double dfYSize = window[3];

    if (!(dfXSize > 0) || !(dfYSize > 0)) {
        cpp11::stop("The window must have a positive width and height");
    }

    const int nXOut = out_size[0];
    const int nYOut = out_size[1];
    if (nXOut <= 0 || nYOut <= 0) {
        cpp11::stop("`out_size` must be positive");
    }

    const int band_count = GDALGetRasterCount(h);
    std::vector<int> band_list(static_cast<size_t>(bands.size()));
    for (R_xlen_t i = 0; i < bands.size(); i++) {
        const int b = bands[i];
        if (b < 1 || b > band_count) {
            cpp11::stop("Band %d is out of range; this dataset has %d", b, band_count);
        }
        band_list[static_cast<size_t>(i)] = b;
    }

    GDALRasterIOExtraArg extra;
    INIT_RASTERIO_EXTRA_ARG(extra);
    extra.eResampleAlg = resample_from_name(resample);

    const int nXOff = static_cast<int>(std::floor(dfXOff));
    const int nYOff = static_cast<int>(std::floor(dfYOff));
    const int nXSize = static_cast<int>(std::ceil(dfXOff + dfXSize)) - nXOff;
    const int nYSize = static_cast<int>(std::ceil(dfYOff + dfYSize)) - nYOff;

    extra.bFloatingPointWindowValidity = TRUE;
    extra.dfXOff = dfXOff;
    extra.dfYOff = dfYOff;
    extra.dfXSize = dfXSize;
    extra.dfYSize = dfYSize;

    // One buffer, band sequential, split into a vector per band afterwards.
    const size_t per_band = static_cast<size_t>(nXOut) * static_cast<size_t>(nYOut);
    std::vector<double> buffer(per_band * band_list.size());

    gdal7::ErrorScope err;
    const CPLErr status = GDALDatasetRasterIOEx(
        h, GF_Read, nXOff, nYOff, nXSize, nYSize,
        buffer.data(), nXOut, nYOut, GDT_Float64,
        static_cast<int>(band_list.size()), band_list.data(), 0, 0, 0, &extra);

    if (status != CE_None) {
        err.stop("Could not read the raster window");
    }
    err.flush();

    cpp11::writable::list out(static_cast<R_xlen_t>(band_list.size()));
    cpp11::writable::strings names(static_cast<R_xlen_t>(band_list.size()));
    for (size_t i = 0; i < band_list.size(); i++) {
        cpp11::writable::doubles values(static_cast<R_xlen_t>(per_band));
        std::copy(buffer.begin() + static_cast<std::ptrdiff_t>(i * per_band),
                  buffer.begin() + static_cast<std::ptrdiff_t>((i + 1) * per_band),
                  REAL(values));
        out[static_cast<R_xlen_t>(i)] = values;
        names[static_cast<R_xlen_t>(i)] =
            cpp11::r_string(std::to_string(band_list[i]));
    }
    out.names() = names;
    return out;
}
