// src/GDAL7_summary.cpp
// Manual file - NOT generated by orchestrate.R
// One call for a whole dataset summary, and the enum tables that make the
// integer codes elsewhere in the package readable.

#include "gdal7.h"

namespace {

// A scalar double, or NA when GDAL says the value is not set.
double optional_double(int has_value, double value) {
    return has_value ? value : NA_REAL;
}

}  // namespace

// ============================================================================
// Enum tables
// ============================================================================

// GDT_* as a named integer vector, so a code from get_data_type() can be
// looked up rather than memorised. Built from GDAL itself, so a build with
// newer types reports them.
[[cpp11::register]]
cpp11::integers GDAL7_data_types() {
    cpp11::writable::integers values;
    cpp11::writable::strings names;

    for (int i = 0; i < GDT_TypeCount; i++) {
        const char* name = GDALGetDataTypeName(static_cast<GDALDataType>(i));
        values.push_back(i);
        names.push_back(name ? cpp11::r_string(name) : cpp11::r_string("Unknown"));
    }

    values.names() = names;
    return values;
}

// GCI_* as a named integer vector, the same way.
[[cpp11::register]]
cpp11::integers GDAL7_color_interpretations() {
    cpp11::writable::integers values;
    cpp11::writable::strings names;

    for (int i = 0; i <= GCI_Max; i++) {
        const char* name =
            GDALGetColorInterpretationName(static_cast<GDALColorInterp>(i));
        values.push_back(i);
        names.push_back(name ? cpp11::r_string(name) : cpp11::r_string("Undefined"));
    }

    values.names() = names;
    return values;
}

// ============================================================================
// Batched dataset summary
// ============================================================================

// Everything gdalinfo prints that does not need a scan of the pixels, in one
// call. Reached one accessor at a time this is seven .Call round trips per
// band plus a handful for the dataset, which over /vsicurl/ is the difference
// between usable and not.
[[cpp11::register]]
cpp11::list GDAL7_dataset_summary(SEXP xp) {
    GDALDatasetH h = gdal7::get<GDALDatasetH>(xp, gdal7::Kind::Dataset);

    gdal7::ErrorScope err;

    cpp11::writable::list out;

    GDALDriverH drv = GDALGetDatasetDriver(h);
    out.push_back(cpp11::named_arg("driver") =
                      gdal7::chr(drv ? GDALGetDriverShortName(drv) : nullptr));
    out.push_back(cpp11::named_arg("driver_long") =
                      gdal7::chr(drv ? GDALGetDriverLongName(drv) : nullptr));

    cpp11::writable::integers size(2);
    size[0] = GDALGetRasterXSize(h);
    size[1] = GDALGetRasterYSize(h);
    size.names() = {"xsize", "ysize"};
    out.push_back(cpp11::named_arg("size") = size);

    const int band_count = GDALGetRasterCount(h);
    out.push_back(cpp11::named_arg("bands") = cpp11::as_sexp(band_count));

    out.push_back(cpp11::named_arg("projection") =
                      gdal7::chr(GDALGetProjectionRef(h)));

    double gt[6];
    if (GDALGetGeoTransform(h, gt) == CE_None) {
        cpp11::writable::doubles geotransform(6);
        for (int i = 0; i < 6; i++) {
            geotransform[i] = gt[i];
        }
        out.push_back(cpp11::named_arg("geotransform") = geotransform);
    } else {
        out.push_back(cpp11::named_arg("geotransform") = R_NilValue);
    }

    char** files = GDALGetFileList(h);
    out.push_back(cpp11::named_arg("files") = gdal7::from_csl(files));
    CSLDestroy(files);

    out.push_back(cpp11::named_arg("metadata") =
                      gdal7::named_from_csl(GDALGetMetadata(h, "")));

    // One vector per column, which the R side turns into a data frame.
    cpp11::writable::integers b_index(band_count);
    cpp11::writable::strings b_type(band_count);
    cpp11::writable::integers b_block_x(band_count);
    cpp11::writable::integers b_block_y(band_count);
    cpp11::writable::doubles b_nodata(band_count);
    cpp11::writable::doubles b_scale(band_count);
    cpp11::writable::doubles b_offset(band_count);
    cpp11::writable::strings b_color(band_count);
    cpp11::writable::strings b_unit(band_count);
    cpp11::writable::integers b_overviews(band_count);

    for (int i = 0; i < band_count; i++) {
        GDALRasterBandH b = GDALGetRasterBand(h, i + 1);
        b_index[i] = i + 1;

        if (!b) {
            b_type[i] = NA_STRING;
            b_block_x[i] = NA_INTEGER;
            b_block_y[i] = NA_INTEGER;
            b_nodata[i] = NA_REAL;
            b_scale[i] = NA_REAL;
            b_offset[i] = NA_REAL;
            b_color[i] = NA_STRING;
            b_unit[i] = NA_STRING;
            b_overviews[i] = NA_INTEGER;
            continue;
        }

        b_type[i] = cpp11::r_string(GDALGetDataTypeName(GDALGetRasterDataType(b)));

        int block_x = 0;
        int block_y = 0;
        GDALGetBlockSize(b, &block_x, &block_y);
        b_block_x[i] = block_x;
        b_block_y[i] = block_y;

        int has_value = 0;
        const double nodata = GDALGetRasterNoDataValue(b, &has_value);
        b_nodata[i] = optional_double(has_value, nodata);

        const double scale = GDALGetRasterScale(b, &has_value);
        b_scale[i] = optional_double(has_value, scale);

        const double offset = GDALGetRasterOffset(b, &has_value);
        b_offset[i] = optional_double(has_value, offset);

        b_color[i] = cpp11::r_string(
            GDALGetColorInterpretationName(GDALGetRasterColorInterpretation(b)));

        const char* unit = GDALGetRasterUnitType(b);
        if (unit == nullptr) {
            b_unit[i] = NA_STRING;
        } else {
            b_unit[i] = cpp11::r_string(unit);
        }

        b_overviews[i] = GDALGetOverviewCount(b);
    }

    cpp11::writable::list bands;
    bands.push_back(cpp11::named_arg("band") = b_index);
    bands.push_back(cpp11::named_arg("type") = b_type);
    bands.push_back(cpp11::named_arg("block_x") = b_block_x);
    bands.push_back(cpp11::named_arg("block_y") = b_block_y);
    bands.push_back(cpp11::named_arg("nodata") = b_nodata);
    bands.push_back(cpp11::named_arg("scale") = b_scale);
    bands.push_back(cpp11::named_arg("offset") = b_offset);
    bands.push_back(cpp11::named_arg("color") = b_color);
    bands.push_back(cpp11::named_arg("unit") = b_unit);
    bands.push_back(cpp11::named_arg("overviews") = b_overviews);

    // Named apart from the "bands" count above: two elements of the same name
    // would leave `$bands` reaching whichever came first.
    out.push_back(cpp11::named_arg("band_info") = bands);

    err.flush();
    return out;
}
