# Generated by cpp11: do not edit by hand

GDAL7_capabilities <- function() {
  .Call(`_GDAL7_GDAL7_capabilities`)
}

GDAL7_gdal_version <- function() {
  .Call(`_GDAL7_GDAL7_gdal_version`)
}

GDAL7_integer_constants <- function() {
  .Call(`_GDAL7_GDAL7_integer_constants`)
}

GDAL7_string_constants <- function() {
  .Call(`_GDAL7_GDAL7_string_constants`)
}

GDAL7_dataset_raster_xsize <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_raster_xsize`, xp)
}

GDAL7_dataset_raster_ysize <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_raster_ysize`, xp)
}

GDAL7_dataset_raster_count <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_raster_count`, xp)
}

GDAL7_dataset_mark_suppress_on_close <- function(xp) {
  invisible(.Call(`_GDAL7_GDAL7_dataset_mark_suppress_on_close`, xp))
}

GDAL7_dataset_get_close_reports_progress <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_close_reports_progress`, xp)
}

GDAL7_dataset_is_thread_safe <- function(xp, nScopeFlags) {
  .Call(`_GDAL7_GDAL7_dataset_is_thread_safe`, xp, nScopeFlags)
}

GDAL7_dataset_get_thread_safe_dataset <- function(xp, nScopeFlags) {
  .Call(`_GDAL7_GDAL7_dataset_get_thread_safe_dataset`, xp, nScopeFlags)
}

GDAL7_dataset_get_projection <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_projection`, xp)
}

GDAL7_dataset_get_projection_ref <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_projection_ref`, xp)
}

GDAL7_dataset_set_projection <- function(xp, prj) {
  .Call(`_GDAL7_GDAL7_dataset_set_projection`, xp, prj)
}

GDAL7_dataset_get_gcpcount <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_gcpcount`, xp)
}

GDAL7_dataset_get_gcpprojection <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_gcpprojection`, xp)
}

GDAL7_dataset_flush_cache <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_flush_cache`, xp)
}

GDAL7_dataset_add_band <- function(xp, datatype, options) {
  .Call(`_GDAL7_GDAL7_dataset_add_band`, xp, datatype, options)
}

GDAL7_dataset_create_mask_band <- function(xp, nFlags) {
  .Call(`_GDAL7_GDAL7_dataset_create_mask_band`, xp, nFlags)
}

GDAL7_dataset_get_file_list <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_file_list`, xp)
}

GDAL7_dataset_reset_reading <- function(xp) {
  invisible(.Call(`_GDAL7_GDAL7_dataset_reset_reading`, xp))
}

GDAL7_dataset_get_layer_count <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_layer_count`, xp)
}

GDAL7_dataset_abort_sql <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_abort_sql`, xp)
}

GDAL7_dataset_start_transaction <- function(xp, force) {
  .Call(`_GDAL7_GDAL7_dataset_start_transaction`, xp, force)
}

GDAL7_dataset_commit_transaction <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_commit_transaction`, xp)
}

GDAL7_dataset_rollback_transaction <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_rollback_transaction`, xp)
}

GDAL7_dataset_clear_statistics <- function(xp) {
  invisible(.Call(`_GDAL7_GDAL7_dataset_clear_statistics`, xp))
}

GDAL7_dataset_get_field_domain_names <- function(xp, options) {
  .Call(`_GDAL7_GDAL7_dataset_get_field_domain_names`, xp, options)
}

GDAL7_dataset_delete_field_domain <- function(xp, name) {
  .Call(`_GDAL7_GDAL7_dataset_delete_field_domain`, xp, name)
}

GDAL7_dataset_get_relationship_names <- function(xp, options) {
  .Call(`_GDAL7_GDAL7_dataset_get_relationship_names`, xp, options)
}

GDAL7_dataset_delete_relationship <- function(xp, name) {
  .Call(`_GDAL7_GDAL7_dataset_delete_relationship`, xp, name)
}

GDAL7_dataset_as_mdarray <- function(xp, options) {
  .Call(`_GDAL7_GDAL7_dataset_as_mdarray`, xp, options)
}

GDAL7_driver_get_short_name <- function(xp) {
  .Call(`_GDAL7_GDAL7_driver_get_short_name`, xp)
}

GDAL7_driver_get_long_name <- function(xp) {
  .Call(`_GDAL7_GDAL7_driver_get_long_name`, xp)
}

GDAL7_driver_get_help_topic <- function(xp) {
  .Call(`_GDAL7_GDAL7_driver_get_help_topic`, xp)
}

GDAL7_driver_has_open_option <- function(xp, option_name) {
  .Call(`_GDAL7_GDAL7_driver_has_open_option`, xp, option_name)
}

GDAL7_dataset_get_driver_ptr <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_driver_ptr`, xp)
}

GDAL7_get_driver_count <- function() {
  .Call(`_GDAL7_GDAL7_get_driver_count`)
}

GDAL7_get_driver_by_name <- function(name) {
  .Call(`_GDAL7_GDAL7_get_driver_by_name`, name)
}

GDAL7_get_driver <- function(index) {
  .Call(`_GDAL7_GDAL7_get_driver`, index)
}

GDAL7_driver_test_capability <- function(xp, capability) {
  .Call(`_GDAL7_GDAL7_driver_test_capability`, xp, capability)
}

GDAL7_driver_get_creation_options <- function(xp) {
  .Call(`_GDAL7_GDAL7_driver_get_creation_options`, xp)
}

GDAL7_driver_get_metadata_item <- function(xp, name, domain) {
  .Call(`_GDAL7_GDAL7_driver_get_metadata_item`, xp, name, domain)
}

GDAL7_dataset_get_band <- function(xp, nBand) {
  .Call(`_GDAL7_GDAL7_dataset_get_band`, xp, nBand)
}

GDAL7_band_get_xsize <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_xsize`, xp)
}

GDAL7_band_get_ysize <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_ysize`, xp)
}

GDAL7_band_get_band_number <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_band_number`, xp)
}

GDAL7_band_get_data_type <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_data_type`, xp)
}

GDAL7_band_get_data_type_name <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_data_type_name`, xp)
}

GDAL7_band_get_block_size <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_block_size`, xp)
}

GDAL7_band_get_nodata_value <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_nodata_value`, xp)
}

GDAL7_band_get_description <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_description`, xp)
}

GDAL7_band_get_color_interpretation <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_color_interpretation`, xp)
}

GDAL7_band_get_color_interpretation_name <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_color_interpretation_name`, xp)
}

GDAL7_band_get_scale <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_scale`, xp)
}

GDAL7_band_get_offset <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_offset`, xp)
}

GDAL7_band_get_unit_type <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_unit_type`, xp)
}

GDAL7_majorobject_get_description <- function(xp) {
  .Call(`_GDAL7_GDAL7_majorobject_get_description`, xp)
}

GDAL7_majorobject_set_description <- function(xp, pszNewDesc) {
  invisible(.Call(`_GDAL7_GDAL7_majorobject_set_description`, xp, pszNewDesc))
}

GDAL7_majorobject_get_metadata_domain_list <- function(xp) {
  .Call(`_GDAL7_GDAL7_majorobject_get_metadata_domain_list`, xp)
}

GDAL7_majorobject_get_metadata_dict <- function(xp, pszDomain) {
  .Call(`_GDAL7_GDAL7_majorobject_get_metadata_dict`, xp, pszDomain)
}

GDAL7_majorobject_get_metadata_list <- function(xp, pszDomain) {
  .Call(`_GDAL7_GDAL7_majorobject_get_metadata_list`, xp, pszDomain)
}

GDAL7_majorobject_set_metadata <- function(xp, papszMetadata, pszDomain) {
  .Call(`_GDAL7_GDAL7_majorobject_set_metadata`, xp, papszMetadata, pszDomain)
}

GDAL7_majorobject_set_metadata_2 <- function(xp, pszMetadataString, pszDomain) {
  .Call(`_GDAL7_GDAL7_majorobject_set_metadata_2`, xp, pszMetadataString, pszDomain)
}

GDAL7_majorobject_get_metadata_item <- function(xp, pszName, pszDomain) {
  .Call(`_GDAL7_GDAL7_majorobject_get_metadata_item`, xp, pszName, pszDomain)
}

GDAL7_majorobject_set_metadata_item <- function(xp, pszName, pszValue, pszDomain) {
  .Call(`_GDAL7_GDAL7_majorobject_set_metadata_item`, xp, pszName, pszValue, pszDomain)
}

GDAL7_dataset_get_root_group <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_root_group`, xp)
}

GDAL7_group_get_name <- function(xp) {
  .Call(`_GDAL7_GDAL7_group_get_name`, xp)
}

GDAL7_group_get_full_name <- function(xp) {
  .Call(`_GDAL7_GDAL7_group_get_full_name`, xp)
}

GDAL7_group_get_mdarray_names <- function(xp) {
  .Call(`_GDAL7_GDAL7_group_get_mdarray_names`, xp)
}

GDAL7_group_open_mdarray <- function(xp, name) {
  .Call(`_GDAL7_GDAL7_group_open_mdarray`, xp, name)
}

GDAL7_group_get_group_names <- function(xp) {
  .Call(`_GDAL7_GDAL7_group_get_group_names`, xp)
}

GDAL7_group_open_group <- function(xp, name) {
  .Call(`_GDAL7_GDAL7_group_open_group`, xp, name)
}

GDAL7_group_release <- function(xp) {
  invisible(.Call(`_GDAL7_GDAL7_group_release`, xp))
}

GDAL7_mdarray_get_name <- function(xp) {
  .Call(`_GDAL7_GDAL7_mdarray_get_name`, xp)
}

GDAL7_mdarray_get_full_name <- function(xp) {
  .Call(`_GDAL7_GDAL7_mdarray_get_full_name`, xp)
}

GDAL7_mdarray_get_dimension_count <- function(xp) {
  .Call(`_GDAL7_GDAL7_mdarray_get_dimension_count`, xp)
}

GDAL7_mdarray_get_dimensions <- function(xp) {
  .Call(`_GDAL7_GDAL7_mdarray_get_dimensions`, xp)
}

GDAL7_mdarray_get_data_type_name <- function(xp) {
  .Call(`_GDAL7_GDAL7_mdarray_get_data_type_name`, xp)
}

GDAL7_mdarray_get_unit <- function(xp) {
  .Call(`_GDAL7_GDAL7_mdarray_get_unit`, xp)
}

GDAL7_mdarray_get_nodata_value <- function(xp) {
  .Call(`_GDAL7_GDAL7_mdarray_get_nodata_value`, xp)
}

GDAL7_mdarray_release <- function(xp) {
  invisible(.Call(`_GDAL7_GDAL7_mdarray_release`, xp))
}

GDAL7_init <- function() {
  invisible(.Call(`_GDAL7_GDAL7_init`))
}

GDAL7_gdal_open <- function(path, update, multidim) {
  .Call(`_GDAL7_GDAL7_gdal_open`, path, update, multidim)
}

GDAL7_close <- function(xp) {
  invisible(.Call(`_GDAL7_GDAL7_close`, xp))
}

GDAL7_emit_gdal_message <- function(level, message) {
  invisible(.Call(`_GDAL7_GDAL7_emit_gdal_message`, level, message))
}

GDAL7_dataset_get_geotransform <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_geotransform`, xp)
}

GDAL7_dataset_set_geotransform <- function(xp, gt) {
  invisible(.Call(`_GDAL7_GDAL7_dataset_set_geotransform`, xp, gt))
}

GDAL7_apply_geotransform <- function(gt, pixel, line) {
  .Call(`_GDAL7_GDAL7_apply_geotransform`, gt, pixel, line)
}

GDAL7_inv_geotransform <- function(gt) {
  .Call(`_GDAL7_GDAL7_inv_geotransform`, gt)
}

GDAL7_band_get_overview_count <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_overview_count`, xp)
}

GDAL7_band_get_overview <- function(xp, index) {
  .Call(`_GDAL7_GDAL7_band_get_overview`, xp, index)
}

GDAL7_band_get_overview_sizes <- function(xp) {
  .Call(`_GDAL7_GDAL7_band_get_overview_sizes`, xp)
}

GDAL7_band_read <- function(xp, window, out_size, resample) {
  .Call(`_GDAL7_GDAL7_band_read`, xp, window, out_size, resample)
}

GDAL7_dataset_read <- function(xp, bands, window, out_size, resample) {
  .Call(`_GDAL7_GDAL7_dataset_read`, xp, bands, window, out_size, resample)
}

GDAL7_data_types <- function() {
  .Call(`_GDAL7_GDAL7_data_types`)
}

GDAL7_color_interpretations <- function() {
  .Call(`_GDAL7_GDAL7_color_interpretations`)
}

GDAL7_dataset_summary <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_summary`, xp)
}
