# Generated by cpp11: do not edit by hand

GDAL7_dataset_get_driver <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_driver`, xp)
}

GDAL7_dataset_get_raster_band <- function(xp, nBand) {
  .Call(`_GDAL7_GDAL7_dataset_get_raster_band`, xp, nBand)
}

GDAL7_dataset_get_projection <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_projection`, xp)
}

GDAL7_dataset_get_projection_ref <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_projection_ref`, xp)
}

GDAL7_dataset_get_spatial_ref <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_spatial_ref`, xp)
}

GDAL7_dataset_get_gcpcount <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_gcpcount`, xp)
}

GDAL7_dataset_get_gcpprojection <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_gcpprojection`, xp)
}

GDAL7_dataset_flush_cache <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_flush_cache`, xp)
}

GDAL7_dataset_get_file_list <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_file_list`, xp)
}

GDAL7_dataset_get_layer_count <- function(xp) {
  .Call(`_GDAL7_GDAL7_dataset_get_layer_count`, xp)
}

GDAL7_majorobject_get_description <- function(xp) {
  .Call(`_GDAL7_GDAL7_majorobject_get_description`, xp)
}

GDAL7_majorobject_set_description <- function(xp, pszNewDesc) {
  invisible(.Call(`_GDAL7_GDAL7_majorobject_set_description`, xp, pszNewDesc))
}

GDAL7_majorobject_get_metadata_domain_list <- function(xp) {
  .Call(`_GDAL7_GDAL7_majorobject_get_metadata_domain_list`, xp)
}

GDAL7_majorobject_get_metadata_dict <- function(xp, pszDomain) {
  .Call(`_GDAL7_GDAL7_majorobject_get_metadata_dict`, xp, pszDomain)
}

GDAL7_majorobject_get_metadata_list <- function(xp, pszDomain) {
  .Call(`_GDAL7_GDAL7_majorobject_get_metadata_list`, xp, pszDomain)
}

GDAL7_majorobject_set_metadata <- function(xp, papszMetadata, pszDomain) {
  .Call(`_GDAL7_GDAL7_majorobject_set_metadata`, xp, papszMetadata, pszDomain)
}

GDAL7_majorobject_set_metadata_2 <- function(xp, pszMetadataString, pszDomain) {
  .Call(`_GDAL7_GDAL7_majorobject_set_metadata_2`, xp, pszMetadataString, pszDomain)
}

GDAL7_majorobject_get_metadata_item <- function(xp, pszName, pszDomain) {
  .Call(`_GDAL7_GDAL7_majorobject_get_metadata_item`, xp, pszName, pszDomain)
}

GDAL7_majorobject_set_metadata_item <- function(xp, pszName, pszValue, pszDomain) {
  .Call(`_GDAL7_GDAL7_majorobject_set_metadata_item`, xp, pszName, pszValue, pszDomain)
}
