# R/create.R
# Manual file - NOT generated by orchestrate.R
# Making datasets: what a driver accepts, creating one, and copying one.

# ============================================================================
# What a driver accepts
# ============================================================================

# GDAL takes options as KEY=VALUE strings. A named character vector or list is
# what an R caller would rather write, so both are accepted and converted here.
as_gdal_options <- function(options) {
  if (is.null(options) || length(options) == 0L) {
    return(character(0))
  }
  names <- names(options)

  if (is.list(options)) {
    options <- vapply(options, function(value) {
      if (is.logical(value)) {
        if (isTRUE(value)) "YES" else "NO"
      } else {
        as.character(value)
      }
    }, character(1), USE.NAMES = FALSE)
  } else if (is.logical(options)) {
    # GDAL writes its own booleans this way, so TRUE from R should arrive as
    # the driver expects rather than as "TRUE".
    options <- ifelse(options, "YES", "NO")
  }
  # as.character() drops names, so they were taken above.
  options <- unname(as.character(options))

  if (is.null(names)) {
    # Already KEY=VALUE, which is what GDAL's own documentation shows.
    if (!all(grepl("=", options, fixed = TRUE))) {
      stop("Options must be named, or already written as \"KEY=VALUE\"",
           call. = FALSE)
    }
    return(options)
  }
  if (any(!nzchar(names))) {
    stop("Every option needs a name", call. = FALSE)
  }
  paste0(names, "=", options)
}

#' What a driver will accept
#'
#' Each driver describes its own creation and open options, in an XML document
#' GDAL also validates against, so this is read out of GDAL rather than written
#' down here. `type` is GDAL's own vocabulary: `"int"`, `"float"`, `"string"`,
#' `"boolean"`, `"string-select"` for one of a fixed set.
#'
#' @param x A GDALDriver, or a driver's short name such as `"GTiff"`.
#' @param which `"creation"` for the options [gdal_create()] and
#'   [gdal_create_copy()] take, or `"open"` for the ones [gdal_open()] does.
#' @return A data frame with one row per option: `name`, `type`,
#'   `description`, `default`, `min`, `max`, `required`, `scope`, and
#'   `choices`, a list column holding the allowed values of the options that
#'   have a fixed set and nothing for the rest.
#' @export
#' @examples
#' options <- driver_options("GTiff")
#' options[options$name %in% c("COMPRESS", "TILED", "BLOCKXSIZE"),
#'          c("name", "type", "default")]
#'
#' # What COMPRESS will take on this build.
#' options$choices[[which(options$name == "COMPRESS")]]
driver_options <- function(x, which = c("creation", "open")) {
  which <- match.arg(which)
  x <- as_driver(x)

  out <- GDAL7_driver_option_list(x@.ptr, which)
  choices <- out$choices
  out$choices <- NULL
  out <- as.data.frame(out, stringsAsFactors = FALSE)
  out$choices <- choices
  out
}

#' Check creation options against a driver
#'
#' GDAL's own check of a set of options against the driver's option list, which
#' is what [gdal_create()] and [gdal_create_copy()] run before creating
#' anything. Use it to ask the question without the answer being an error.
#'
#' @param x A GDALDriver, or a driver's short name.
#' @param options Creation options, as a named character vector or list, or
#'   already written as `"KEY=VALUE"` strings.
#' @return TRUE or FALSE.
#' @export
#' @examples
#' validate_creation_options("GTiff", c(COMPRESS = "DEFLATE"))
#' validate_creation_options("GTiff", c(COMPRES = "DEFLATE"))
validate_creation_options <- function(x, options) {
  x <- as_driver(x)
  GDAL7_driver_validate_creation_options(x@.ptr, as_gdal_options(options))
}

as_driver <- function(x) {
  if (inherits(x, "GDAL7::GDALDriver")) {
    return(x)
  }
  if (!is.character(x) || length(x) != 1L || is.na(x)) {
    stop("`x` must be a GDALDriver or a single driver name", call. = FALSE)
  }
  driver <- gdal_get_driver_by_name(x)
  if (is.null(driver)) {
    stop("This GDAL has no driver called '", x,
         "'. gdal_drivers() lists the ones it has", call. = FALSE)
  }
  driver
}

# ============================================================================
# Creating
# ============================================================================

#' Create a new raster dataset
#'
#' An empty raster of a given size and type, open for writing. Fill it with
#' [write_raster()], give it a position with [set_geotransform()] and a
#' coordinate reference system with [set_crs()], and close it with
#' [gdal_close()], which is what finishes the file.
#'
#' Creation options are checked against the driver's own option list before
#' anything is created, so a misspelled option is an error rather than a file
#' that quietly lacks what was asked for. [driver_options()] is that list.
#'
#' Not every driver can do this: many can only copy an existing dataset, which
#' is [gdal_create_copy()]. `gdal_drivers()` reports which is which.
#'
#' @param dsn Where to create it. Any VSI path works, so `"/vsimem/x.tif"`
#'   creates it in memory.
#' @param xsize,ysize The size in pixels.
#' @param bands How many bands. May be 0 for a dataset that carries only
#'   metadata.
#' @param type A GDAL data type name, such as `"Byte"`, `"Int16"` or
#'   `"Float32"`. [gdal_data_types()] lists them.
#' @param driver The driver's short name.
#' @param options Creation options, as a named character vector or list, or
#'   already written as `"KEY=VALUE"` strings.
#' @return A GDALDataset, open for writing.
#' @export
#' @examples
#' path <- tempfile(fileext = ".tif")
#' ds <- gdal_create(path, 10, 10, bands = 1, type = "Float32",
#'                   options = c(COMPRESS = "DEFLATE"))
#'
#' set_geotransform(ds, c(0, 1, 0, 10, 0, -1))
#' set_crs(ds, "EPSG:4326")
#' write_raster(ds, list(as.double(seq_len(100))))
#'
#' gdal_close(ds)
#' gdal_info(path)$band_info
#' unlink(path)
gdal_create <- function(dsn, xsize, ysize, bands = 1L, type = "Float64",
                        driver = "GTiff", options = NULL) {
  ptr <- GDAL7_create(driver, dsn, as.integer(xsize), as.integer(ysize),
                      as.integer(bands), type, as_gdal_options(options))
  GDALDataset(.ptr = ptr)
}

#' Copy a dataset, in another format or with other options
#'
#' The driver reads the whole of `x` and writes it out its own way. This is how
#' formats that cannot be built pixel by pixel are made, the Cloud Optimized
#' GeoTIFF among them, and it carries across everything the target format can
#' hold: bands, type, geotransform, coordinate reference system, nodata and
#' metadata.
#'
#' The file is complete once the returned dataset is closed.
#'
#' @param x A GDALDataset, or a DSN string to open and close again.
#' @param dsn Where to write it. Any VSI path works.
#' @param driver The driver's short name.
#' @param options Creation options, as for [gdal_create()].
#' @param strict Whether the copy must be exact. FALSE, the default, lets the
#'   driver approximate what it cannot represent, which is what makes a copy
#'   into a narrower format possible at all.
#' @param progress Whether to draw a progress bar. Interactive sessions do by
#'   default. Ctrl-C stops the copy.
#' @return A GDALDataset, open.
#' @export
#' @examples
#' path <- tempfile(fileext = ".tif")
#' out <- gdal_create_copy(
#'   system.file("extdata/test.tif", package = "GDAL7"), path,
#'   driver = "COG", options = c(COMPRESS = "DEFLATE"), progress = FALSE
#' )
#' gdal_close(out)
#'
#' # The GTiff driver reports the layout it found, which is how to tell that
#' # what was written really is a COG.
#' ds <- gdal_open(path)
#' get_metadata_item(ds, "LAYOUT", "IMAGE_STRUCTURE")
#' gdal_close(ds)
#' unlink(path)
gdal_create_copy <- function(x, dsn, driver = "GTiff", options = NULL,
                             strict = FALSE, progress = interactive()) {
  if (is.character(x)) {
    x <- gdal_open(x)
    on.exit(gdal_close(x), add = TRUE)
  }
  ptr <- GDAL7_create_copy(driver, dsn, x@.ptr, isTRUE(strict),
                           as_gdal_options(options), isTRUE(progress))
  GDALDataset(.ptr = ptr)
}

#' Delete a dataset
#'
#' Through the driver rather than the file system, so the sidecar files a
#' format keeps beside its main one go too: a `.aux.xml`, a shapefile's `.dbf`
#' and `.shx`, a world file.
#'
#' @param dsn The dataset to delete.
#' @param driver The driver's short name.
#' @return Nothing, invisibly.
#' @export
gdal_delete <- function(dsn, driver = "GTiff") {
  GDAL7_driver_delete(driver, dsn)
  invisible(NULL)
}

# ============================================================================
# Thread-safe datasets
# ============================================================================

#' A view of a dataset that several threads may read at once
#'
#' GDAL 3.10 can hand out a thread-safe view of an open dataset. Reads through
#' the view may run on several threads at once, which is what lets GDAL
#' parallelise internally; the dataset it came from is unchanged and must stay
#' open for as long as the view is used, which GDAL7 enforces.
#'
#' Only raster access is supported, which is GDAL's own limit rather than one
#' this package adds.
#'
#' @param x A GDALDataset.
#' @param ... Arguments passed on to methods.
#' @return `get_thread_safe_dataset()` returns a GDALDataset.
#'   `is_thread_safe()` returns TRUE or FALSE.
#' @export
#' @examples
#' ds <- gdal_open(system.file("extdata/test.tif", package = "GDAL7"))
#' is_thread_safe(ds)
#'
#' safe <- get_thread_safe_dataset(ds)
#' is_thread_safe(safe)
#' identical(read_raster(safe, out_size = c(4, 4)),
#'           read_raster(ds, out_size = c(4, 4)))
#'
#' gdal_close(safe)
#' gdal_close(ds)
get_thread_safe_dataset <- S7::new_generic("get_thread_safe_dataset", "x")

S7::method(get_thread_safe_dataset, GDALDataset) <- function(x, ...) {
  GDALDataset(.ptr = GDAL7_dataset_get_thread_safe_dataset(x@.ptr))
}

#' @rdname get_thread_safe_dataset
#' @export
is_thread_safe <- S7::new_generic("is_thread_safe", "x")

S7::method(is_thread_safe, GDALDataset) <- function(x, ...) {
  GDAL7_dataset_is_thread_safe(x@.ptr)
}
