# R/driver.R
# Manual file - NOT generated by orchestrate.R
# Provides GDALDriver class and driver utility functions

# ============================================================================
# GDALDriver S7 class
# ============================================================================

#' GDALDriver class
#'
#' Represents a GDAL format driver (e.g., GTiff, GPKG, etc.)
#'
#' @export
GDALDriver <- S7::new_class(
    "GDALDriver",
    parent = GDALMajorObject,
    properties = list(
        .ptr = S7::class_any
    )
)

# ============================================================================
# Override get_driver to return proper GDALDriver class
# ============================================================================

S7::method(get_driver, GDALDataset) <- function(x) {
    ptr <- GDAL7_dataset_get_driver_ptr(x@.ptr)
    if (is.null(ptr)) {
        return(NULL)
    }
    GDALDriver(.ptr = ptr)
}

# ============================================================================
# Driver info methods
# ============================================================================

#' Get driver short name
#'
#' @param x A GDALDriver object
#' @return Character driver short name (e.g., "GTiff", "GPKG")
#' @export
get_short_name <- S7::new_generic("get_short_name", "x")

S7::method(get_short_name, GDALDriver) <- function(x) {
    GDAL7_driver_get_short_name(x@.ptr)
}

#' Get driver long name
#'
#' @param x A GDALDriver object
#' @return Character driver long name (e.g., "GeoTIFF", "GeoPackage")
#' @export
get_long_name <- S7::new_generic("get_long_name", "x")

S7::method(get_long_name, GDALDriver) <- function(x) {
    GDAL7_driver_get_long_name(x@.ptr)
}

#' Get driver help topic URL
#'
#' @param x A GDALDriver object
#' @return Character help topic URL
#' @export
get_help_topic <- S7::new_generic("get_help_topic", "x")

S7::method(get_help_topic, GDALDriver) <- function(x) {
    GDAL7_driver_get_help_topic(x@.ptr)
}

# ============================================================================
# Driver capability methods
# ============================================================================

#' Check if driver has an open option
#'
#' @param x A GDALDriver object
#' @param option_name Name of the open option to check
#' @return Logical TRUE if driver supports the option
#' @export
has_open_option <- S7::new_generic("has_open_option", "x")

S7::method(has_open_option, GDALDriver) <- function(x, option_name) {
    GDAL7_driver_has_open_option(x@.ptr, option_name)
}

#' Test driver capability
#'
#' Check if driver has a specific capability (DCAP_* metadata).
#' Common capabilities include:
#' - DCAP_RASTER: Can handle raster data
#' - DCAP_VECTOR: Can handle vector data
#' - DCAP_CREATE: Can create new datasets
#' - DCAP_CREATECOPY: Can create datasets via CreateCopy
#' - DCAP_VIRTUALIO: Supports /vsimem/ and other virtual filesystems
#'
#' @param x A GDALDriver object
#' @param capability Capability name (e.g., "DCAP_RASTER")
#' @return Logical TRUE if driver has the capability
#' @export
test_capability <- S7::new_generic("test_capability", "x")

S7::method(test_capability, GDALDriver) <- function(x, capability) {
    GDAL7_driver_test_capability(x@.ptr, capability)
}

#' Get driver creation options XML
#'
#' Returns the XML describing creation options for this driver.
#'
#' @param x A GDALDriver object
#' @return Character XML string describing creation options
#' @export
get_creation_options <- S7::new_generic("get_creation_options", "x")

S7::method(get_creation_options, GDALDriver) <- function(x) {
    GDAL7_driver_get_creation_options(x@.ptr)
}

# ============================================================================
# Top-level driver functions
# ============================================================================

#' Get the number of registered GDAL drivers
#'
#' @return Integer number of drivers
#' @export
gdal_get_driver_count <- function() {
    GDAL7_get_driver_count()
}

#' Get a driver by name
#'
#' @param name Driver short name (e.g., "GTiff", "GPKG", "GeoJSON")
#' @return A GDALDriver object, or NULL if not found
#' @export
gdal_get_driver_by_name <- function(name) {
    ptr <- GDAL7_get_driver_by_name(name)
    if (is.null(ptr)) {
        return(NULL)
    }
    GDALDriver(.ptr = ptr)
}

#' Get a driver by index
#'
#' @param index Driver index (0-based)
#' @return A GDALDriver object, or NULL if invalid index
#' @export
gdal_get_driver <- function(index) {
    ptr <- GDAL7_get_driver(as.integer(index))
    if (is.null(ptr)) {
        return(NULL)
    }
    GDALDriver(.ptr = ptr)
}

#' List all registered GDAL drivers
#'
#' @param capabilities Optional character vector of required capabilities
#'   (e.g., c("DCAP_RASTER", "DCAP_CREATE"))
#' @return Data frame with driver information
#' @export
gdal_drivers <- function(capabilities = NULL) {
    n <- gdal_get_driver_count()
    
    short_name <- character(n)
    long_name <- character(n)
    is_raster <- logical(n)
    is_vector <- logical(n)
    can_create <- logical(n)
    can_copy <- logical(n)
    can_vsi <- logical(n)
    
    for (i in seq_len(n)) {
        drv <- gdal_get_driver(i - 1L)
        if (!is.null(drv)) {
            short_name[i] <- get_short_name(drv)
            long_name[i] <- get_long_name(drv)
            is_raster[i] <- test_capability(drv, "DCAP_RASTER")
            is_vector[i] <- test_capability(drv, "DCAP_VECTOR")
            can_create[i] <- test_capability(drv, "DCAP_CREATE")
            can_copy[i] <- test_capability(drv, "DCAP_CREATECOPY")
            can_vsi[i] <- test_capability(drv, "DCAP_VIRTUALIO")
        }
    }
    
    result <- data.frame(
        short_name = short_name,
        long_name = long_name,
        raster = is_raster,
        vector = is_vector,
        create = can_create,
        copy = can_copy,
        vsi = can_vsi,
        stringsAsFactors = FALSE
    )
    
    # Filter by capabilities if requested
    if (!is.null(capabilities)) {
        for (cap in capabilities) {
            if (cap == "DCAP_RASTER") {
                result <- result[result$raster, ]
            } else if (cap == "DCAP_VECTOR") {
                result <- result[result$vector, ]
            } else if (cap == "DCAP_CREATE") {
                result <- result[result$create, ]
            } else if (cap == "DCAP_CREATECOPY") {
                result <- result[result$copy, ]
            } else if (cap == "DCAP_VIRTUALIO") {
                result <- result[result$vsi, ]
            }
        }
    }
    
    result
}

# ============================================================================
# Print method for GDALDriver
# ============================================================================

S7::method(print, GDALDriver) <- function(x, ...) {
    cat("<GDALDriver>\n")
    cat("  Short name: ", get_short_name(x), "\n", sep = "")
    cat("  Long name:  ", get_long_name(x), "\n", sep = "")
    
    help <- get_help_topic(x)
    if (nchar(help) > 0) {
        cat("  Help:       ", help, "\n", sep = "")
    }
    
    caps <- character()
    if (test_capability(x, "DCAP_RASTER")) caps <- c(caps, "raster")
    if (test_capability(x, "DCAP_VECTOR")) caps <- c(caps, "vector")
    if (test_capability(x, "DCAP_CREATE")) caps <- c(caps, "create")
    if (test_capability(x, "DCAP_CREATECOPY")) caps <- c(caps, "copy")
    if (test_capability(x, "DCAP_VIRTUALIO")) caps <- c(caps, "vsi")
    
    if (length(caps) > 0) {
        cat("  Capabilities: ", paste(caps, collapse = ", "), "\n", sep = "")
    }
    
    invisible(x)
}
