# R/driver.R
# Manual file - NOT generated by orchestrate.R
# Provides GDALDriver class and driver utility functions

# ============================================================================
# GDALDriver S7 class
# ============================================================================

#' GDALDriver class
#'
#' Represents a GDAL format driver (e.g., GTiff, GPKG, etc.)
#'
#' @param .ptr Internal. External pointer to the underlying GDAL object.
#' @export
GDALDriver <- S7::new_class(
    "GDALDriver",
    parent = GDALMajorObject,
    properties = list(
        .ptr = S7::class_any
    )
)

# ============================================================================
# Dataset accessor for the owning driver
# ============================================================================

#' Get the driver that opened a dataset
#'
#' @param x A GDALDataset object
#' @param ... Arguments passed on to methods.
#' @return A GDALDriver object, or NULL
#' @export
get_driver <- S7::new_generic("get_driver", "x")

S7::method(get_driver, GDALDataset) <- function(x) {
    ptr <- GDAL7_dataset_get_driver_ptr(x@.ptr)
    if (is.null(ptr)) {
        return(NULL)
    }
    GDALDriver(.ptr = ptr)
}

# ============================================================================
# Driver info methods
# ============================================================================

#' Get driver short name
#'
#' @param x A GDALDriver object
#' @param ... Arguments passed on to methods.
#' @return Character driver short name (e.g., "GTiff", "GPKG")
#' @export
get_short_name <- S7::new_generic("get_short_name", "x")

S7::method(get_short_name, GDALDriver) <- function(x) {
    GDAL7_driver_get_short_name(x@.ptr)
}

#' Get driver long name
#'
#' @param x A GDALDriver object
#' @param ... Arguments passed on to methods.
#' @return Character driver long name (e.g., "GeoTIFF", "GeoPackage")
#' @export
get_long_name <- S7::new_generic("get_long_name", "x")

S7::method(get_long_name, GDALDriver) <- function(x) {
    GDAL7_driver_get_long_name(x@.ptr)
}

#' Get driver help topic URL
#'
#' @param x A GDALDriver object
#' @param ... Arguments passed on to methods.
#' @return Character help topic URL
#' @export
get_help_topic <- S7::new_generic("get_help_topic", "x")

S7::method(get_help_topic, GDALDriver) <- function(x) {
    GDAL7_driver_get_help_topic(x@.ptr)
}

# ============================================================================
# Driver capability methods
# ============================================================================

#' Check if driver has an open option
#'
#' @param x A GDALDriver object
#' @param option_name Name of the open option to check
#' @return Logical TRUE if driver supports the option
#' @export
has_open_option <- S7::new_generic("has_open_option", "x", function(x, option_name) S7::S7_dispatch())

S7::method(has_open_option, GDALDriver) <- function(x, option_name) {
    GDAL7_driver_has_open_option(x@.ptr, option_name)
}

#' Test driver capability
#'
#' Check if driver has a specific capability (DCAP_* metadata).
#' Common capabilities include:
#' - DCAP_RASTER: Can handle raster data
#' - DCAP_VECTOR: Can handle vector data
#' - DCAP_CREATE: Can create new datasets
#' - DCAP_CREATECOPY: Can create datasets via CreateCopy
#' - DCAP_VIRTUALIO: Supports /vsimem/ and other virtual filesystems
#'
#' @param x A GDALDriver object
#' @param capability Capability name (e.g., "DCAP_RASTER")
#' @return Logical TRUE if driver has the capability
#' @export
test_capability <- S7::new_generic("test_capability", "x", function(x, capability) S7::S7_dispatch())

S7::method(test_capability, GDALDriver) <- function(x, capability) {
    GDAL7_driver_test_capability(x@.ptr, capability)
}

# ============================================================================
# Top-level driver functions
# ============================================================================

#' Get the number of registered GDAL drivers
#'
#' @return Integer number of drivers
#' @export
gdal_get_driver_count <- function() {
    GDAL7_get_driver_count()
}

#' Get a driver by name
#'
#' @param name Driver short name (e.g., "GTiff", "GPKG", "GeoJSON")
#' @return A GDALDriver object, or NULL if not found
#' @export
gdal_get_driver_by_name <- function(name) {
    ptr <- GDAL7_get_driver_by_name(name)
    if (is.null(ptr)) {
        return(NULL)
    }
    GDALDriver(.ptr = ptr)
}

#' Get a driver by index
#'
#' @param index Driver index (0-based)
#' @return A GDALDriver object, or NULL if invalid index
#' @export
gdal_get_driver <- function(index) {
    ptr <- GDAL7_get_driver(as.integer(index))
    if (is.null(ptr)) {
        return(NULL)
    }
    GDALDriver(.ptr = ptr)
}

#' Every driver this GDAL has
#'
#' The whole table in one call rather than one call per property per driver,
#' which on a typical build is the difference between one round trip and about
#' fourteen hundred.
#'
#' @param capabilities Optional character vector of capabilities every returned
#'   driver must have, named as GDAL names them: `"DCAP_RASTER"`,
#'   `"DCAP_VECTOR"`, `"DCAP_MULTIDIM_RASTER"`, `"DCAP_CREATE"`,
#'   `"DCAP_CREATECOPY"`, `"DCAP_VIRTUALIO"`.
#' @return A data frame with one row per driver: `short_name`, `long_name`,
#'   `raster`, `vector`, `multidim`, `create`, `copy`, `vsi` and `extensions`.
#' @export
#' @examples
#' drivers <- gdal_drivers()
#' nrow(drivers)
#'
#' # The formats that can be written from nothing, rather than only copied.
#' head(gdal_drivers("DCAP_CREATE")$short_name, 12)
gdal_drivers <- function(capabilities = NULL) {
  result <- as.data.frame(GDAL7_driver_table(), stringsAsFactors = FALSE)

  if (is.null(capabilities)) {
    return(result)
  }

  columns <- c(DCAP_RASTER = "raster", DCAP_VECTOR = "vector",
               DCAP_MULTIDIM_RASTER = "multidim", DCAP_CREATE = "create",
               DCAP_CREATECOPY = "copy", DCAP_VIRTUALIO = "vsi")
  unknown <- setdiff(capabilities, names(columns))
  if (length(unknown) > 0) {
    stop("Cannot filter on ", paste(unknown, collapse = ", "),
         ". One of: ", paste(names(columns), collapse = ", "), call. = FALSE)
  }

  for (capability in capabilities) {
    result <- result[result[[columns[[capability]]]], , drop = FALSE]
  }
  rownames(result) <- NULL
  result
}

# ============================================================================
# Print method for GDALDriver
# ============================================================================

#' @export
S7::method(print, GDALDriver) <- function(x, ...) {
    cat("<GDALDriver>\n")
    cat("  Short name: ", get_short_name(x), "\n", sep = "")
    cat("  Long name:  ", get_long_name(x), "\n", sep = "")
    
    help <- get_help_topic(x)
    if (nchar(help) > 0) {
        cat("  Help:       ", help, "\n", sep = "")
    }
    
    caps <- character()
    if (test_capability(x, "DCAP_RASTER")) caps <- c(caps, "raster")
    if (test_capability(x, "DCAP_VECTOR")) caps <- c(caps, "vector")
    if (test_capability(x, "DCAP_CREATE")) caps <- c(caps, "create")
    if (test_capability(x, "DCAP_CREATECOPY")) caps <- c(caps, "copy")
    if (test_capability(x, "DCAP_VIRTUALIO")) caps <- c(caps, "vsi")
    
    if (length(caps) > 0) {
        cat("  Capabilities: ", paste(caps, collapse = ", "), "\n", sep = "")
    }
    
    invisible(x)
}
