# R/gdal-open.R
# Manual file - NOT generated by orchestrate.R
# Provides gdal_open() constructor for GDALDataset

#' Open a GDAL dataset
#'
#' @param path Path to the dataset (file, URL, or connection string)
#' @param update Logical. If TRUE, open for update (read/write). Default FALSE.
#' @param multidim Logical. If TRUE, open in multidimensional mode (for NetCDF, 
#'   Zarr, HDF5, etc.). Use get_root_group() to access the multidimensional structure.
#'   Default FALSE.
#' @param options Character vector of `KEY=VALUE` open options, or `NULL` for
#'   none. These are the driver's own, and are how a source is told what its
#'   own metadata does not say: a CSV's `X_POSSIBLE_NAMES=lon`, a raster's
#'   `OVERVIEW_LEVEL=2`. [driver_options()] lists what a driver accepts and
#'   [has_open_option()] asks about one by name. An option a driver does not
#'   recognise is a warning from GDAL, not an error.
#' @param drivers Character vector of driver short names to try, or `NULL` to
#'   let every driver try, which is the default. Naming the driver skips the
#'   probing and stops a second driver claiming a file the first should have
#'   had. `character(0)` is not the same as `NULL`: it would allow no driver
#'   at all, so it is rejected.
#' @return A GDALDataset object
#' @export
#' @examples
#' ds <- gdal_open(system.file("extdata/test.tif", package = "GDAL7"))
#' ds@raster_count
#' gdal_close(ds)
#'
#' # Naming the driver, and reading the first overview instead of full size.
#' ds <- gdal_open(system.file("extdata/overviews.tif", package = "GDAL7"),
#'                 options = "OVERVIEW_LEVEL=0", drivers = "GTiff")
#' c(ds@raster_xsize, ds@raster_ysize)
#' gdal_close(ds)
#' \dontrun{
#' # Multidimensional mode
#' ds <- gdal_open("/path/to/data.zarr", multidim = TRUE)
#' grp <- get_root_group(ds)
#' grp@mdarray_names
#' gdal_close(ds)
#' }
gdal_open <- function(path, update = FALSE, multidim = FALSE,
                      options = NULL, drivers = NULL) {
  ptr <- GDAL7_gdal_open(
    gdal_dsn(path), update, multidim,
    gdal_open_strings(options, "options"),
    gdal_open_strings(drivers, "drivers")
  )
  GDALDataset(.ptr = ptr)
}

# NULL means "no list" and is what both arguments default to. An empty
# character vector is a different thing and a mistake worth naming: as an
# allowed-driver list it would let nothing open, and it is almost always
# something like drivers[0] rather than a deliberate choice.
gdal_open_strings <- function(x, what) {
  if (is.null(x)) {
    return(character())
  }
  if (!is.character(x) || anyNA(x)) {
    stop("`", what, "` must be a character vector with no missing values",
         call. = FALSE)
  }
  if (length(x) == 0L) {
    stop("`", what, "` is empty; use NULL to place no restriction",
         call. = FALSE)
  }
  x
}

# GDAL accepts connection strings as well as file paths: "WMTS:https://...",
# 'ZARR:"/vsizip/x.zip/y"', 'NETCDF:"file.nc":var', "/vsicurl/https://...".
# normalizePath() rewrites separators to backslashes on Windows, which corrupts
# every one of those, so only resolve something that really is a file on disk.
gdal_dsn <- function(path) {
  if (!is.character(path) || length(path) != 1L || is.na(path)) {
    stop("`path` must be a single, non-missing string", call. = FALSE)
  }
  if (file.exists(path)) {
    normalizePath(path, winslash = "/", mustWork = FALSE)
  } else {
    path
  }
}

#' Close a GDAL dataset
#'
#' @param x A GDALDataset object
#' @export
gdal_close <- function(x) {
  stopifnot(inherits(x, "GDAL7::GDALDataset") || inherits(x, "GDAL7::GDALMajorObject"))
  GDAL7_close(x@.ptr)
  invisible(NULL)
}
