# R/gdal-open.R
# Manual file - NOT generated by orchestrate.R
# Provides gdal_open() constructor for GDALDataset

#' Open a GDAL dataset
#'
#' @param path Path to the dataset (file, URL, or connection string)
#' @param update Logical. If TRUE, open for update (read/write). Default FALSE.
#' @param multidim Logical. If TRUE, open in multidimensional mode (for NetCDF, 
#'   Zarr, HDF5, etc.). Use get_root_group() to access the multidimensional structure.
#'   Default FALSE.
#' @return A GDALDataset object
#' @export
#' @examples
#' \dontrun{
#' # Classic raster mode
#' ds <- gdal_open("/path/to/raster.tif")
#' get_projection(ds)
#' gdal_close(ds)
#' 
#' # Multidimensional mode
#' ds <- gdal_open("/path/to/data.zarr", multidim = TRUE)
#' grp <- get_root_group(ds)
#' get_mdarray_names(grp)
#' gdal_close(ds)
#' }
gdal_open <- function(path, update = FALSE, multidim = FALSE) {
  ptr <- GDAL7_gdal_open(gdal_dsn(path), update, multidim)
  GDALDataset(.ptr = ptr)
}

# GDAL accepts connection strings as well as file paths: "WMTS:https://...",
# 'ZARR:"/vsizip/x.zip/y"', 'NETCDF:"file.nc":var', "/vsicurl/https://...".
# normalizePath() rewrites separators to backslashes on Windows, which corrupts
# every one of those, so only resolve something that really is a file on disk.
gdal_dsn <- function(path) {
  if (!is.character(path) || length(path) != 1L || is.na(path)) {
    stop("`path` must be a single, non-missing string", call. = FALSE)
  }
  if (file.exists(path)) {
    normalizePath(path, winslash = "/", mustWork = FALSE)
  } else {
    path
  }
}

#' Close a GDAL dataset
#'
#' @param x A GDALDataset object
#' @export
gdal_close <- function(x) {
  stopifnot(inherits(x, "GDAL7::GDALDataset") || inherits(x, "GDAL7::GDALMajorObject"))
  GDAL7_close(x@.ptr)
  invisible(NULL)
}
