# R/raster-io.R
# Manual file - NOT generated by orchestrate.R
# Geotransforms, overviews, windowed reads, and the batched dataset summary.

# ============================================================================
# Geotransform
# ============================================================================

#' Get the geotransform of a dataset
#'
#' The six coefficients that map pixel and line to georeferenced coordinates,
#' in GDAL's order: origin x, pixel width, row rotation, origin y, column
#' rotation, pixel height. Note that GDAL's order interleaves the x and y
#' terms, which is not the order the names might suggest.
#'
#' @param x A GDALDataset object
#' @param ... Arguments passed on to methods.
#' @return A named numeric vector of length 6, or NULL when the dataset carries
#'   no geotransform. GDAL reports the identity in that case, which is
#'   indistinguishable from a real identity geotransform, so NULL is used here
#'   instead.
#' @export
#' @examples
#' ds <- gdal_open(system.file("extdata/test.tif", package = "GDAL7"))
#' get_geotransform(ds)
#' gdal_close(ds)
get_geotransform <- S7::new_generic("get_geotransform", "x")

S7::method(get_geotransform, GDALDataset) <- function(x, ...) {
  GDAL7_dataset_get_geotransform(x@.ptr)
}

#' Set the geotransform of a dataset
#'
#' @param x A GDALDataset object, opened for update.
#' @param geotransform A numeric vector of length 6, in GDAL's order.
#' @return `x`, invisibly.
#' @export
set_geotransform <- S7::new_generic(
  "set_geotransform", "x",
  function(x, geotransform) S7::S7_dispatch()
)

S7::method(set_geotransform, GDALDataset) <- function(x, geotransform) {
  GDAL7_dataset_set_geotransform(x@.ptr, as.double(geotransform))
  invisible(x)
}

#' Convert between pixel and georeferenced coordinates
#'
#' `apply_geotransform()` takes pixel and line positions to georeferenced ones.
#' `inv_geotransform()` returns the geotransform that goes the other way, which
#' is what to feed back to `apply_geotransform()` to turn coordinates into
#' pixel positions.
#'
#' Both are vectorised over `pixel` and `line`, so a whole set of positions is
#' one call.
#'
#' @param geotransform A numeric vector of length 6, as [get_geotransform()]
#'   returns.
#' @param pixel,line Numeric vectors of the same length. Fractional positions
#'   are meaningful: whole numbers fall on pixel corners, so the centre of the
#'   first pixel is `pixel = 0.5, line = 0.5`.
#' @return `apply_geotransform()` returns a list of `x` and `y`.
#'   `inv_geotransform()` returns a numeric vector of length 6, or NULL when
#'   the geotransform cannot be inverted.
#' @export
#' @examples
#' ds <- gdal_open(system.file("extdata/test.tif", package = "GDAL7"))
#' gt <- get_geotransform(ds)
#'
#' # The centre of the first pixel, and back again.
#' apply_geotransform(gt, 0.5, 0.5)
#' apply_geotransform(inv_geotransform(gt), -180 + 9, 90 - 9)
#'
#' gdal_close(ds)
apply_geotransform <- function(geotransform, pixel, line) {
  GDAL7_apply_geotransform(
    as.double(geotransform), as.double(pixel), as.double(line)
  )
}

#' @rdname apply_geotransform
#' @export
inv_geotransform <- function(geotransform) {
  GDAL7_inv_geotransform(as.double(geotransform))
}

# ============================================================================
# Overviews
# ============================================================================

#' Number of overviews on a band
#'
#' @param x A GDALRasterBand object
#' @param ... Arguments passed on to methods.
#' @return Integer count.
#' @export
get_overview_count <- S7::new_generic("get_overview_count", "x")

S7::method(get_overview_count, GDALRasterBand) <- function(x, ...) {
  GDAL7_band_get_overview_count(x@.ptr)
}

#' Get one overview of a band
#'
#' @param x A GDALRasterBand object
#' @param index Zero-based overview index, as GDAL numbers them.
#' @return A GDALRasterBand object for the overview, which belongs to the same
#'   dataset as `x`.
#' @export
get_overview <- S7::new_generic(
  "get_overview", "x",
  function(x, index) S7::S7_dispatch()
)

S7::method(get_overview, GDALRasterBand) <- function(x, index) {
  GDALRasterBand(.ptr = GDAL7_band_get_overview(x@.ptr, as.integer(index)))
}

#' Sizes of a band's overviews
#'
#' Which overview level a read will actually touch follows from these sizes and
#' the output size asked for, so this is the cheap way to see what a read at a
#' given size will cost.
#'
#' @param x A GDALRasterBand object
#' @param ... Arguments passed on to methods.
#' @return A data frame of `xsize` and `ysize`, one row per overview, or a
#'   zero-row data frame when the band has none.
#' @export
get_overview_sizes <- S7::new_generic("get_overview_sizes", "x")

S7::method(get_overview_sizes, GDALRasterBand) <- function(x, ...) {
  sizes <- GDAL7_band_get_overview_sizes(x@.ptr)
  data.frame(xsize = sizes$xsize, ysize = sizes$ysize)
}

# ============================================================================
# Windowed reads
# ============================================================================

#' Read a window of raster data
#'
#' Reads a window of a band, or of several bands of a dataset, at a chosen
#' output size. The window and the output size are independent, which is the
#' whole point: asking for a large window at a small output size lets GDAL
#' serve the read from an overview, so a huge raster over `/vsicurl/` costs
#' only the bytes of the overview level it picks.
#'
#' The window is in pixel coordinates and may be fractional. Whole numbers fall
#' on pixel corners, so `c(0, 0, 10, 10)` is the first ten pixels of the first
#' ten rows.
#'
#' Values come back as doubles whatever the band holds, in GDAL's order: the
#' first row of the output first, x varying fastest. That is the transpose of
#' what R's `matrix()` builds from a vector, so reshape with
#' `matrix(values, nrow = out_size[1])` and read the columns as rows, or
#' transpose it.
#'
#' @param x A GDALRasterBand, or a GDALDataset.
#' @param window Numeric of length 4: `c(xoff, yoff, xsize, ysize)` in pixels.
#'   Defaults to the whole raster.
#' @param out_size Integer of length 2: the width and height to return.
#'   Defaults to the size of the window, which is a read with no resampling.
#' @param resample One of "nearest", "bilinear", "cubic", "cubicspline",
#'   "lanczos", "average", "mode", "gauss", "rms".
#' @param bands For a dataset, which bands to read, one-based. Defaults to all
#'   of them. Reading several at once is one pass over the data rather than one
#'   per band.
#' @return For a band, a numeric vector of `out_size[1] * out_size[2]` values.
#'   For a dataset, a named list of one such vector per band.
#' @export
#' @examples
#' ds <- gdal_open(system.file("extdata/test.tif", package = "GDAL7"))
#' band <- get_raster_band(ds, 1)
#'
#' # The whole band.
#' length(read_raster(band))
#'
#' # A 4x4 window, averaged down to 2x2.
#' read_raster(band, window = c(0, 0, 4, 4), out_size = c(2, 2),
#'             resample = "average")
#'
#' # Both bands at once.
#' str(read_raster(ds, out_size = c(5, 5)))
#'
#' gdal_close(ds)
read_raster <- S7::new_generic(
  "read_raster", "x",
  function(x, window = NULL, out_size = NULL, resample = "nearest", bands = NULL) {
    S7::S7_dispatch()
  }
)

S7::method(read_raster, GDALRasterBand) <- function(x, window = NULL,
                                                    out_size = NULL,
                                                    resample = "nearest",
                                                    bands = NULL) {
  if (!is.null(bands)) {
    stop("`bands` applies to a dataset, not to a single band", call. = FALSE)
  }
  window <- resolve_window(window, get_xsize(x), get_ysize(x))
  GDAL7_band_read(x@.ptr, window, resolve_out_size(out_size, window), resample)
}

S7::method(read_raster, GDALDataset) <- function(x, window = NULL,
                                                 out_size = NULL,
                                                 resample = "nearest",
                                                 bands = NULL) {
  if (is.null(bands)) {
    bands <- seq_len(get_raster_count(x))
  }
  window <- resolve_window(window, get_raster_xsize(x), get_raster_ysize(x))
  GDAL7_dataset_read(
    x@.ptr, as.integer(bands), window,
    resolve_out_size(out_size, window), resample
  )
}

resolve_window <- function(window, xsize, ysize) {
  if (is.null(window)) {
    return(c(0, 0, as.double(xsize), as.double(ysize)))
  }
  window <- as.double(window)
  if (length(window) != 4L || anyNA(window)) {
    stop("`window` must be 4 non-missing numbers: xoff, yoff, xsize, ysize",
         call. = FALSE)
  }
  window
}

resolve_out_size <- function(out_size, window) {
  if (is.null(out_size)) {
    return(as.integer(ceiling(window[3:4])))
  }
  out_size <- as.integer(out_size)
  if (length(out_size) != 2L || anyNA(out_size)) {
    stop("`out_size` must be 2 non-missing numbers", call. = FALSE)
  }
  out_size
}

# ============================================================================
# Batched summary
# ============================================================================

#' Summarise a dataset in one call
#'
#' Everything `gdalinfo` reports that does not need a pass over the pixels,
#' fetched in a single call rather than one per property. Reached one accessor
#' at a time the same summary is seven round trips per band plus a handful for
#' the dataset, which over `/vsicurl/` is the difference between immediate and
#' sluggish.
#'
#' @param x A GDALDataset, or a DSN string to open and close again.
#' @return A list with `driver`, `driver_long`, `size`, `bands` (the count),
#'   `projection`, `geotransform`, `files`, `metadata`, and `band_info`, a data
#'   frame with one row per band.
#' @export
#' @examples
#' info <- gdal_info(system.file("extdata/test.tif", package = "GDAL7"))
#' info$size
#' info$band_info
gdal_info <- function(x) {
  if (is.character(x)) {
    ds <- gdal_open(x)
    on.exit(gdal_close(ds), add = TRUE)
  } else {
    ds <- x
  }

  info <- GDAL7_dataset_summary(ds@.ptr)
  info$band_info <- as.data.frame(info$band_info, stringsAsFactors = FALSE)
  info
}

# ============================================================================
# Enum tables
# ============================================================================

#' GDAL enum tables
#'
#' The `GDT_*` and `GCI_*` codes as named integer vectors, read out of the GDAL
#' in use rather than hard coded, so a build with types this package has never
#' heard of still reports them. These are what give meaning to the integers
#' from [get_data_type()] and [get_color_interpretation()].
#'
#' @return A named integer vector.
#' @export
#' @examples
#' gdal_data_types()
#' names(gdal_data_types())[gdal_data_types() == 3]
gdal_data_types <- function() {
  GDAL7_data_types()
}

#' @rdname gdal_data_types
#' @export
gdal_color_interpretations <- function() {
  GDAL7_color_interpretations()
}
