# R/raster-io.R
# Manual file - NOT generated by orchestrate.R
# Geotransforms, overviews, windowed reads, and the batched dataset summary.

# ============================================================================
# Geotransform
# ============================================================================

# The two halves of the dataset's geotransform property, which is declared in
# the generated class file. A geotransform is the six coefficients that map
# pixel and line to georeferenced coordinates, in GDAL's order: origin x,
# pixel width, row rotation, origin y, column rotation, pixel height. GDAL's
# order interleaves the x and y terms, which is not the order the names might
# suggest.
#
# A dataset carrying no geotransform reads as NULL. GDAL reports the identity
# in that case, which is indistinguishable from a real identity geotransform.
dataset_geotransform <- function(x) {
  GDAL7_dataset_get_geotransform(x@.ptr)
}

dataset_set_geotransform <- function(x, value) {
  GDAL7_dataset_set_geotransform(x@.ptr, as.double(value))
  invisible(x)
}

#' Convert between pixel and georeferenced coordinates
#'
#' `pixel_to_xy()` takes pixel and line positions to georeferenced ones, and
#' `xy_to_pixel()` takes them back again.
#'
#' Both are vectorised, so a whole set of positions is one call.
#'
#' @param geotransform A numeric vector of length 6, as a dataset's
#'   `geotransform` property returns.
#' @param pixel,line Numeric vectors of the same length. Fractional positions
#'   are meaningful: whole numbers fall on pixel corners, so the centre of the
#'   first pixel is `pixel = 0.5, line = 0.5`.
#' @param x,y Numeric vectors of the same length, in the dataset's coordinate
#'   reference system.
#' @return `pixel_to_xy()` a list of `x` and `y`. `xy_to_pixel()` a list of
#'   `pixel` and `line`.
#' @export
#' @examples
#' ds <- gdal_open(system.file("extdata/test.tif", package = "GDAL7"))
#' gt <- ds@geotransform
#'
#' # The centre of the first pixel, and back again.
#' pixel_to_xy(gt, 0.5, 0.5)
#' xy_to_pixel(gt, -180 + 9, 90 - 9)
#'
#' gdal_close(ds)
pixel_to_xy <- function(geotransform, pixel, line) {
  GDAL7_apply_geotransform(
    as.double(geotransform), as.double(pixel), as.double(line)
  )
}

#' @rdname pixel_to_xy
#' @export
xy_to_pixel <- function(geotransform, x, y) {
  inverse <- GDAL7_inv_geotransform(as.double(geotransform))
  if (is.null(inverse)) {
    # A geotransform with a zero determinant maps every pixel onto the same
    # place, so there is no position to give back.
    stop("this geotransform cannot be inverted", call. = FALSE)
  }
  out <- GDAL7_apply_geotransform(inverse, as.double(x), as.double(y))
  names(out) <- c("pixel", "line")
  out
}

# ============================================================================
# Overviews
# ============================================================================

# The body behind the band's overview_sizes property. It lives here, beside
# the rest of the overview code, rather than inside the class definition.
band_overview_sizes <- function(x) {
  sizes <- GDAL7_band_get_overview_sizes(x@.ptr)
  data.frame(xsize = sizes$xsize, ysize = sizes$ysize)
}

#' Get one overview of a band
#'
#' @param x A GDALRasterBand object
#' @param index Zero-based overview index, as GDAL numbers them. How many
#'   there are is `x@overview_count`, and their sizes are `x@overview_sizes`;
#'   which level a read will actually touch follows from those sizes and the
#'   output size asked for.
#' @return A GDALRasterBand object for the overview, which belongs to the same
#'   dataset as `x`.
#' @export
get_overview <- S7::new_generic(
  "get_overview", "x",
  function(x, index) S7::S7_dispatch()
)

S7::method(get_overview, GDALRasterBand) <- function(x, index) {
  GDALRasterBand(.ptr = GDAL7_band_get_overview(x@.ptr, as.integer(index)))
}

# ============================================================================
# Windowed reads
# ============================================================================

#' Read a window of raster data
#'
#' Reads a window of a band, or of several bands of a dataset, at a chosen
#' output size. The window and the output size are independent, which is the
#' whole point: asking for a large window at a small output size lets GDAL
#' serve the read from an overview, so a huge raster over `/vsicurl/` costs
#' only the bytes of the overview level it picks.
#'
#' The window is in pixel coordinates and may be fractional. Whole numbers fall
#' on pixel corners, so `c(0, 0, 10, 10)` is the first ten pixels of the first
#' ten rows.
#'
#' Values come back as doubles whatever the band holds, in GDAL's order: the
#' first row of the output first, x varying fastest. That is the transpose of
#' what R's `matrix()` builds from a vector, so reshape with
#' `matrix(values, nrow = out_size[1])` and read the columns as rows, or
#' transpose it.
#'
#' @param x A GDALRasterBand, or a GDALDataset.
#' @param window Numeric of length 4: `c(xoff, yoff, xsize, ysize)` in pixels.
#'   Defaults to the whole raster.
#' @param out_size Integer of length 2: the width and height to return.
#'   Defaults to the size of the window, which is a read with no resampling.
#' @param resample One of "nearest", "bilinear", "cubic", "cubicspline",
#'   "lanczos", "average", "mode", "gauss", "rms".
#' @param bands For a dataset, which bands to read, one-based. Defaults to all
#'   of them. Reading several at once is one pass over the data rather than one
#'   per band.
#' @param type The R type to read into: `"double"` (the default), `"integer"`
#'   or `"raw"`. `"double"` holds any band type and is eight bytes a value.
#'   `"raw"` is one byte and reads a Byte band as-is, which is what an RGB
#'   image wants. `"integer"` is four bytes and covers Byte, Int8, Int16,
#'   UInt16 and Int32. A band whose type will not fit is an error rather than
#'   a silent clamp, and for a dataset every band read has to fit.
#'
#'   Two things the narrower types cannot carry. `"raw"` has no missing value,
#'   so a nodata pixel comes back as whatever byte the file holds. `"integer"`
#'   has one, and it is `.Machine$integer.max + 1` in disguise, so an Int32
#'   band holding that exact value reads as `NA`.
#' @return For a band, a vector of `out_size[1] * out_size[2]` values, of the
#'   requested `type`. For a dataset, a named list of one such vector per band.
#' @export
#' @examples
#' ds <- gdal_open(system.file("extdata/test.tif", package = "GDAL7"))
#' band <- get_raster_band(ds, 1)
#'
#' # The whole band.
#' length(read_raster(band))
#'
#' # A 4x4 window, averaged down to 2x2.
#' read_raster(band, window = c(0, 0, 4, 4), out_size = c(2, 2),
#'             resample = "average")
#'
#' # Both bands at once.
#' str(read_raster(ds, out_size = c(5, 5)))
#'
#' # test.tif holds Int16, which fits an R integer but not a raw byte.
#' str(read_raster(band, out_size = c(4, 4), type = "integer"))
#'
#' gdal_close(ds)
#'
#' # A Byte band does fit, and as raw it is an eighth of the memory of the
#' # same read as double.
#' path <- tempfile(fileext = ".tif")
#' bytes <- gdal_create(path, 4, 4, bands = 1, type = "Byte")
#' write_raster(bytes, list(as.double(0:15)))
#' gdal_close(bytes)
#'
#' ds <- gdal_open(path)
#' str(read_raster(get_raster_band(ds, 1), type = "raw"))
#' gdal_close(ds)
#' unlink(path)
read_raster <- S7::new_generic(
  "read_raster", "x",
  function(x, window = NULL, out_size = NULL, resample = "nearest",
           bands = NULL, type = "double") {
    S7::S7_dispatch()
  }
)

S7::method(read_raster, GDALRasterBand) <- function(x, window = NULL,
                                                    out_size = NULL,
                                                    resample = "nearest",
                                                    bands = NULL,
                                                    type = "double") {
  if (!is.null(bands)) {
    stop("`bands` applies to a dataset, not to a single band", call. = FALSE)
  }
  window <- resolve_window(window, x@xsize, x@ysize)
  GDAL7_band_read(x@.ptr, window, resolve_out_size(out_size, window), resample,
                  resolve_read_type(type))
}

S7::method(read_raster, GDALDataset) <- function(x, window = NULL,
                                                 out_size = NULL,
                                                 resample = "nearest",
                                                 bands = NULL,
                                                 type = "double") {
  if (is.null(bands)) {
    bands <- seq_len(x@raster_count)
  }
  window <- resolve_window(window, x@raster_xsize, x@raster_ysize)
  GDAL7_dataset_read(
    x@.ptr, as.integer(bands), window,
    resolve_out_size(out_size, window), resample, resolve_read_type(type)
  )
}

# Checked here rather than in C++ so a typo is an R error naming the three
# choices, before any GDAL handle is touched.
resolve_read_type <- function(type) {
  if (!is.character(type) || length(type) != 1L || is.na(type)) {
    stop("`type` must be a single, non-missing string", call. = FALSE)
  }
  if (!type %in% c("double", "integer", "raw")) {
    stop("`type` is one of \"double\", \"integer\" or \"raw\"", call. = FALSE)
  }
  type
}

resolve_window <- function(window, xsize, ysize) {
  if (is.null(window)) {
    return(c(0, 0, as.double(xsize), as.double(ysize)))
  }
  window <- as.double(window)
  if (length(window) != 4L || anyNA(window)) {
    stop("`window` must be 4 non-missing numbers: xoff, yoff, xsize, ysize",
         call. = FALSE)
  }
  window
}

resolve_out_size <- function(out_size, window) {
  if (is.null(out_size)) {
    return(as.integer(ceiling(window[3:4])))
  }
  out_size <- as.integer(out_size)
  if (length(out_size) != 2L || anyNA(out_size)) {
    stop("`out_size` must be 2 non-missing numbers", call. = FALSE)
  }
  out_size
}

# ============================================================================
# Writing
# ============================================================================

#' Write a raster window
#'
#' The mirror of [read_raster()], with the same window and the same output
#' size, so values read at one size can be written back at another and GDAL
#' resamples between them.
#'
#' Values go in the order they come out: the first row first, x varying
#' fastest, which is the transpose of what `matrix()` builds from a vector.
#'
#' Whatever the band holds, values are given as doubles and GDAL converts. A
#' value the band's type cannot hold is clamped by GDAL rather than wrapped,
#' and it says so.
#'
#' The dataset has to be open for writing: one from [gdal_create()], or one
#' opened with `gdal_open(path, update = TRUE)`. Nothing is guaranteed to be on
#' disk until the dataset is closed with [gdal_close()], or [gdal_flush()] is
#' called.
#'
#' @param x A GDALRasterBand, or a GDALDataset.
#' @param values For a band, a numeric vector. For a dataset, a list of one
#'   numeric vector per band in `bands`.
#' @param window Numeric of length 4: `c(xoff, yoff, xsize, ysize)` in pixels.
#'   Defaults to the whole raster.
#' @param out_size Integer of length 2: the width and height of the block of
#'   values being given. Defaults to the size of the window, which is a write
#'   with no resampling.
#' @param resample How to resample when `out_size` differs from the window.
#'   One of "nearest", "bilinear", "cubic", "cubicspline", "lanczos",
#'   "average", "mode", "gauss", "rms".
#' @param bands For a dataset, which bands to write, one-based. Defaults to
#'   all of them. Writing several at once is one pass over the data.
#' @return `x`, invisibly.
#' @export
#' @examples
#' path <- tempfile(fileext = ".tif")
#' ds <- gdal_create(path, 4, 4, bands = 1, type = "Byte")
#'
#' write_raster(ds, list(as.double(seq_len(16))))
#' read_raster(ds)[[1]]
#'
#' gdal_close(ds)
#' unlink(path)
write_raster <- S7::new_generic(
  "write_raster", "x",
  function(x, values, window = NULL, out_size = NULL, resample = "nearest",
           bands = NULL) {
    S7::S7_dispatch()
  }
)

S7::method(write_raster, GDALRasterBand) <- function(x, values, window = NULL,
                                                     out_size = NULL,
                                                     resample = "nearest",
                                                     bands = NULL) {
  if (!is.null(bands)) {
    stop("`bands` applies to a dataset, not to a single band", call. = FALSE)
  }
  window <- resolve_window(window, x@xsize, x@ysize)
  GDAL7_band_write(x@.ptr, as.double(values), window,
                   resolve_out_size(out_size, window), resample)
  invisible(x)
}

S7::method(write_raster, GDALDataset) <- function(x, values, window = NULL,
                                                  out_size = NULL,
                                                  resample = "nearest",
                                                  bands = NULL) {
  if (is.null(bands)) {
    bands <- seq_len(x@raster_count)
  }
  if (!is.list(values)) {
    stop("For a dataset, `values` is a list of one vector per band",
         call. = FALSE)
  }
  window <- resolve_window(window, x@raster_xsize, x@raster_ysize)
  GDAL7_dataset_write(
    x@.ptr, lapply(values, as.double), as.integer(bands), window,
    resolve_out_size(out_size, window), resample
  )
  invisible(x)
}

#' Write out everything held in memory
#'
#' A dataset open for writing holds its last blocks in memory until it is
#' closed. This puts them on disk without closing it, which is what makes a
#' file readable by something else while it is still being built.
#'
#' @param x A GDALDataset.
#' @param ... Arguments passed on to methods.
#' @return `x`, invisibly.
#' @export
gdal_flush <- S7::new_generic("gdal_flush", "x")

S7::method(gdal_flush, GDALDataset) <- function(x, ...) {
  GDAL7_dataset_flush(x@.ptr)
  invisible(x)
}

# ============================================================================
# Coordinate reference systems
# ============================================================================

# The two halves of the dataset's crs property, which is declared in the
# generated class file. Reading gives WKT2, or NA when the dataset has no CRS.
# Writing accepts anything GDAL understands: "EPSG:4326", a PROJ string, a
# PROJJSON document, the contents of a .prj file, or WKT. The projection
# property next to it is GDAL's own SetProjection, which is WKT only.
dataset_crs <- function(x) {
  GDAL7_dataset_get_crs(x@.ptr)
}

dataset_set_crs <- function(x, value) {
  GDAL7_dataset_set_crs(x@.ptr, as.character(value))
  invisible(x)
}

#' A coordinate reference system as WKT
#'
#' The conversion a dataset's `crs` property does, on its own, for checking a CRS string or
#' for seeing what one says.
#'
#' WKT2 is the default because WKT1 cannot carry everything a modern CRS
#' holds: a projection WKT2 names exactly comes back out of WKT1 as
#' `PROJCS["unknown"]`. WKT1 is still what GDAL writes into a file and what
#' the `projection` property returns, so it is here for comparing against those.
#'
#' @param crs A coordinate reference system, in any form GDAL reads.
#' @param format `"WKT2"`, or `"WKT2_2015"` or `"WKT2_2019"` for a particular
#'   edition, or `"WKT1"`.
#' @param multiline Whether to lay it out over several lines, which is how to
#'   read one rather than how to store it.
#' @return A WKT string.
#' @export
#' @examples
#' substr(crs_to_wkt("EPSG:4326"), 1, 30)
#' substr(crs_to_wkt("EPSG:4326", "WKT1"), 1, 30)
#'
#' cat(crs_to_wkt("EPSG:3857", multiline = TRUE))
crs_to_wkt <- function(crs, format = c("WKT2", "WKT2_2019", "WKT2_2015", "WKT1"),
                       multiline = FALSE) {
  format <- match.arg(format)
  GDAL7_crs_to_wkt(crs, format, isTRUE(multiline))
}

#' Move a bounding box between coordinate reference systems
#'
#' The four numbers of a box, in another CRS. GDAL walks each edge of the box
#' rather than transforming its four corners, because a projected edge usually
#' bows: the box drawn through the corners alone is too small, and a window
#' picked with it clips the data it was meant to select.
#'
#' Both sides are read in x, y order whatever their authority says, so
#' `"EPSG:4326"` here means longitude then latitude.
#'
#' This is a transformation of four numbers, not a warp. It is what turns a
#' query rectangle given in one CRS into a window on a raster held in another;
#' it does not reproject any pixels.
#'
#' @param bbox Numeric of length 4: `c(xmin, ymin, xmax, ymax)`.
#' @param from,to Coordinate reference systems, as anything GDAL reads: an
#'   authority code like `"EPSG:4326"`, a PROJ string, WKT, or the contents of
#'   a `.prj` file.
#' @param densify How many points to add along each edge before taking the
#'   envelope. 21 is GDAL's own default. Zero transforms the corners only,
#'   which is faster and wrong for any box wide enough to bow.
#' @return A named numeric of length 4: `xmin`, `ymin`, `xmax`, `ymax`.
#' @export
#' @examples
#' # An Antarctic box in longlat, as polar stereographic metres.
#' transform_bounds(c(60, -70, 120, -60), "EPSG:4326", "EPSG:3031")
#'
#' # What the corners alone would have given: the same box, half as wide,
#' # because the easting of a parallel peaks in the middle of that edge.
#' transform_bounds(c(60, -70, 120, -60), "EPSG:4326", "EPSG:3031",
#'                  densify = 0)
transform_bounds <- function(bbox, from, to, densify = 21L) {
  bbox <- as.double(bbox)
  if (length(bbox) != 4L || anyNA(bbox)) {
    stop("`bbox` must be 4 non-missing numbers: xmin, ymin, xmax, ymax",
         call. = FALSE)
  }
  GDAL7_transform_bounds(bbox, from, to, as.integer(densify))
}

# ============================================================================
# Batched summary
# ============================================================================

#' Summarise a dataset in one call
#'
#' Everything `gdalinfo` reports that does not need a pass over the pixels,
#' fetched in a single call rather than one per property. Reached one accessor
#' at a time the same summary is seven round trips per band plus a handful for
#' the dataset, which over `/vsicurl/` is the difference between immediate and
#' sluggish.
#'
#' @param x A GDALDataset, or a DSN string to open and close again.
#' @return A list with `driver`, `driver_long`, `size`, `bands` (the count),
#'   `projection`, `geotransform`, `files`, `metadata`, and `band_info`, a data
#'   frame with one row per band.
#' @export
#' @examples
#' info <- gdal_info(system.file("extdata/test.tif", package = "GDAL7"))
#' info$size
#' info$band_info
gdal_info <- function(x) {
  if (is.character(x)) {
    ds <- gdal_open(x)
    on.exit(gdal_close(ds), add = TRUE)
  } else {
    ds <- x
  }

  info <- GDAL7_dataset_summary(ds@.ptr)
  info$band_info <- as.data.frame(info$band_info, stringsAsFactors = FALSE)
  info
}

# ============================================================================
# Enum tables
# ============================================================================

#' GDAL enum tables
#'
#' The `GDT_*` and `GCI_*` codes as named integer vectors, read out of the GDAL
#' in use rather than hard coded, so a build with types this package has never
#' heard of still reports them. These are what give meaning to the integers
#' from a band's `data_type` and `color_interpretation`.
#'
#' @return A named integer vector.
#' @export
#' @examples
#' gdal_data_types()
#' names(gdal_data_types())[gdal_data_types() == 3]
gdal_data_types <- function() {
  GDAL7_data_types()
}

#' @rdname gdal_data_types
#' @export
gdal_color_interpretations <- function() {
  GDAL7_color_interpretations()
}
