# R/vsi.R
# Manual file - NOT generated by orchestrate.R
# GDAL's virtual file systems, and the configuration options that steer them.

#' GDAL's virtual file systems
#'
#' Every GDAL path works here, not only files on disk. `/vsimem/` is memory,
#' `/vsizip/` and `/vsitar/` look inside archives, `/vsicurl/` and the cloud
#' prefixes reach remote storage, and they compose:
#' `/vsizip//vsicurl/https://example.org/a.zip/b.tif` is a file inside a zip
#' that is never downloaded whole.
#'
#' `vfs_list()` returns NULL rather than an error for a path that is not a
#' directory or holds nothing, since a caller cannot otherwise tell the two
#' apart. `vfs_stat()` returns NULL for a path that is not there.
#'
#' @param path A VSI path.
#' @param limit Roughly the most entries to list. -1, the default, is all of
#'   them; a limit is what makes listing a large remote prefix bearable. GDAL
#'   reads a directory in chunks and stops at the first chunk past the limit,
#'   so a listing can come back a little longer than asked for.
#' @return `vfs_list()` a character vector of names, or NULL. `vfs_stat()` a
#'   list of `size`, `is_directory` and `modified`, or NULL. `vfs_exists()`
#'   TRUE or FALSE.
#' @export
#' @examples
#' vfs_exists(system.file("extdata/test.tif", package = "GDAL7"))
#' vfs_stat(system.file("extdata/test.tif", package = "GDAL7"))$size
#'
#' # What ships with the package.
#' vfs_list(system.file("extdata", package = "GDAL7"))
vfs_list <- function(path, limit = -1L) {
  GDAL7_vsi_list(path, as.integer(limit))
}

#' @rdname vfs_list
#' @export
vfs_stat <- function(path) {
  GDAL7_vsi_stat(path)
}

#' @rdname vfs_list
#' @export
vfs_exists <- function(path) {
  GDAL7_vsi_exists(path)
}

#' Change a GDAL virtual file system
#'
#' The same operations as `unlink()`, `dir.create()` and `file.rename()`, over
#' any VSI path rather than only the local disk.
#'
#' @param path,from,to VSI paths.
#' @param mode The permission bits for a new directory, as an octal number.
#'   Meaningless on the file systems that have no permissions.
#' @return Nothing, invisibly. A failure is an error carrying GDAL's reason.
#' @export
#' @examples
#' vfs_write_file("/vsimem/hello.txt", charToRaw("hello"))
#' vfs_exists("/vsimem/hello.txt")
#' vfs_unlink("/vsimem/hello.txt")
#' vfs_exists("/vsimem/hello.txt")
vfs_unlink <- function(path) {
  GDAL7_vsi_unlink(path)
  invisible(NULL)
}

#' @rdname vfs_unlink
#' @export
vfs_mkdir <- function(path, mode = 0755L) {
  GDAL7_vsi_mkdir(path, as.integer(mode))
  invisible(NULL)
}

#' @rdname vfs_unlink
#' @export
vfs_rmdir <- function(path) {
  GDAL7_vsi_rmdir(path)
  invisible(NULL)
}

#' @rdname vfs_unlink
#' @export
vfs_rename <- function(from, to) {
  GDAL7_vsi_rename(from, to)
  invisible(NULL)
}

#' @rdname vfs_unlink
#' @export
vfs_copy <- function(from, to) {
  GDAL7_vsi_copy(from, to)
  invisible(NULL)
}

#' Read and write bytes over a GDAL virtual file system
#'
#' With `/vsimem/` these are how a dataset built in memory leaves GDAL without
#' ever reaching the disk: create it at a `/vsimem/` path, close it, and read
#' the bytes.
#'
#' @param path A VSI path.
#' @param bytes A raw vector.
#' @return `vfs_read_file()` a raw vector. `vfs_write_file()` nothing,
#'   invisibly.
#' @export
#' @examples
#' # A GeoTIFF that is never written to disk.
#' ds <- gdal_create("/vsimem/small.tif", 4, 4, bands = 1, type = "Byte")
#' write_raster(ds, list(as.double(seq_len(16))))
#' gdal_close(ds)
#'
#' bytes <- vfs_read_file("/vsimem/small.tif")
#' length(bytes)
#' rawToChar(bytes[1:2])
#'
#' vfs_unlink("/vsimem/small.tif")
vfs_read_file <- function(path) {
  GDAL7_vsi_read_file(path)
}

#' @rdname vfs_read_file
#' @export
vfs_write_file <- function(path, bytes) {
  GDAL7_vsi_write_file(path, bytes)
  invisible(NULL)
}

# ============================================================================
# Configuration options
# ============================================================================

#' GDAL's configuration options
#'
#' GDAL reads these at the moment it needs them, so setting one changes how the
#' next call behaves. They steer caching, credentials, and a good deal of
#' per-driver behaviour: `GDAL_CACHEMAX` is the block cache size,
#' `CPL_VSIL_CURL_ALLOWED_EXTENSIONS` limits what `/vsicurl/` will fetch,
#' `AWS_NO_SIGN_REQUEST` makes an S3 bucket public.
#'
#' `gdal_config()` with a value sets one; with only a name it reads one, and
#' returns NULL when it is not set, which is not the same as being set to the
#' empty string. `with_gdal_config()` sets options for one expression and puts
#' back exactly what was there, including unsetting what was unset.
#'
#' @param name The option's name.
#' @param value Its value, or NULL to unset it. A logical is written as GDAL
#'   writes them, `"YES"` or `"NO"`.
#' @param options A named character vector or list of options to set.
#' @param expr The expression to evaluate with them set.
#' @return `gdal_config()` reading returns a string or NULL, and setting
#'   returns the previous value invisibly. `gdal_config_options()` returns
#'   every option that is set, as a named character vector.
#'   `with_gdal_config()` returns what `expr` returned.
#' @export
#' @examples
#' # Read a raster with GDAL's block cache set small, then leave it as it was.
#' with_gdal_config(c(GDAL_CACHEMAX = "16"), {
#'   gdal_config("GDAL_CACHEMAX")
#' })
#'
#' gdal_config("GDAL_CACHEMAX")
gdal_config <- function(name, value) {
  previous <- GDAL7_get_config_option(name)
  if (missing(value)) {
    return(previous)
  }
  if (is.logical(value) && length(value) == 1L && !is.na(value)) {
    value <- if (value) "YES" else "NO"
  }
  GDAL7_set_config_option(name, if (is.null(value)) NULL else as.character(value))
  invisible(previous)
}

#' @rdname gdal_config
#' @export
gdal_config_options <- function() {
  GDAL7_config_options()
}

#' @rdname gdal_config
#' @export
with_gdal_config <- function(options, expr) {
  options <- as_gdal_options(options)
  names <- sub("=.*$", "", options)
  values <- sub("^[^=]*=", "", options)

  previous <- lapply(names, GDAL7_get_config_option)
  on.exit({
    for (i in seq_along(names)) {
      GDAL7_set_config_option(names[i], previous[[i]])
    }
  }, add = TRUE)

  for (i in seq_along(names)) {
    GDAL7_set_config_option(names[i], values[i])
  }
  expr
}
