# R/multidim.R
# Manual file - NOT generated by orchestrate.R
# Provides GDALGroup, GDALMDArray and multidimensional API methods

# ============================================================================
# GDALGroup S7 class
# ============================================================================

#' GDALGroup class
#'
#' Represents a group in a multidimensional dataset (NetCDF, Zarr, HDF5, etc.)
#' Groups can contain arrays (GDALMDArray) and subgroups.
#'
#' @export
GDALGroup <- S7::new_class(
  "GDALGroup",
  properties = list(
    .ptr = S7::class_any
  )
)

# ============================================================================
# GDALMDArray S7 class
# ============================================================================

#' GDALMDArray class
#'
#' Represents a multidimensional array in a GDAL dataset.
#'
#' @export
GDALMDArray <- S7::new_class(
  "GDALMDArray",
  properties = list(
    .ptr = S7::class_any
  )
)

# ============================================================================
# Dataset method to get root group
# ============================================================================

#' Get root group from a multidimensional dataset
#'
#' @param x A GDALDataset opened with multidim = TRUE
#' @return A GDALGroup object, or NULL if not a multidimensional dataset
#' @export
get_root_group <- S7::new_generic("get_root_group", "x")

S7::method(get_root_group, GDALDataset) <- function(x) {
  ptr <- GDAL7_dataset_get_root_group(x@.ptr)
  if (is.null(ptr)) {
    return(NULL)
  }
  GDALGroup(.ptr = ptr)
}

# ============================================================================
# Group info methods
# ============================================================================

#' Get group name
#'
#' @param x A GDALGroup object
#' @return Character group name
#' @export
get_name <- S7::new_generic("get_name", "x")

S7::method(get_name, GDALGroup) <- function(x) {
  GDAL7_group_get_name(x@.ptr)
}

#' Get group full name (path)
#'
#' @param x A GDALGroup object
#' @return Character full path name
#' @export
get_full_name <- S7::new_generic("get_full_name", "x")

S7::method(get_full_name, GDALGroup) <- function(x) {
  GDAL7_group_get_full_name(x@.ptr)
}

# ============================================================================
# Group navigation - arrays
# ============================================================================

#' Get names of arrays in a group
#'
#' @param x A GDALGroup object
#' @return Character vector of array names
#' @export
get_mdarray_names <- S7::new_generic("get_mdarray_names", "x")

S7::method(get_mdarray_names, GDALGroup) <- function(x) {
  GDAL7_group_get_mdarray_names(x@.ptr)
}

#' Open an array from a group
#'
#' @param x A GDALGroup object
#' @param name Array name
#' @return A GDALMDArray object, or NULL if not found
#' @export
open_mdarray <- S7::new_generic("open_mdarray", "x")

S7::method(open_mdarray, GDALGroup) <- function(x, name) {
  ptr <- GDAL7_group_open_mdarray(x@.ptr, name)
  if (is.null(ptr)) {
    return(NULL)
  }
  GDALMDArray(.ptr = ptr)
}

# ============================================================================
# Group navigation - subgroups
# ============================================================================

#' Get names of subgroups in a group
#'
#' @param x A GDALGroup object
#' @return Character vector of subgroup names
#' @export
get_group_names <- S7::new_generic("get_group_names", "x")

S7::method(get_group_names, GDALGroup) <- function(x) {
  GDAL7_group_get_group_names(x@.ptr)
}

#' Open a subgroup from a group
#'
#' @param x A GDALGroup object
#' @param name Subgroup name
#' @return A GDALGroup object, or NULL if not found
#' @export
open_group <- S7::new_generic("open_group", "x")

S7::method(open_group, GDALGroup) <- function(x, name) {
  ptr <- GDAL7_group_open_group(x@.ptr, name)
  if (is.null(ptr)) {
    return(NULL)
  }
  GDALGroup(.ptr = ptr)
}

# ============================================================================
# MDArray info methods
# ============================================================================

S7::method(get_name, GDALMDArray) <- function(x) {
  GDAL7_mdarray_get_name(x@.ptr)
}

S7::method(get_full_name, GDALMDArray) <- function(x) {
  GDAL7_mdarray_get_full_name(x@.ptr)
}

#' Get number of dimensions in an array
#'
#' @param x A GDALMDArray object
#' @return Integer dimension count
#' @export
get_dimension_count <- S7::new_generic("get_dimension_count", "x")

S7::method(get_dimension_count, GDALMDArray) <- function(x) {
  GDAL7_mdarray_get_dimension_count(x@.ptr)
}

#' Get dimensions of an array
#'
#' @param x A GDALMDArray object
#' @return Data frame with dimension names and sizes
#' @export
get_dimensions <- S7::new_generic("get_dimensions", "x")

S7::method(get_dimensions, GDALMDArray) <- function(x) {
  result <- GDAL7_mdarray_get_dimensions(x@.ptr)
  data.frame(
    name = result$name,
    size = result$size,
    stringsAsFactors = FALSE
  )
}

S7::method(get_data_type_name, GDALMDArray) <- function(x) {
  GDAL7_mdarray_get_data_type_name(x@.ptr)
}

S7::method(get_unit_type, GDALMDArray) <- function(x) {
  GDAL7_mdarray_get_unit(x@.ptr)
}

S7::method(get_nodata_value, GDALMDArray) <- function(x) {
  GDAL7_mdarray_get_nodata_value(x@.ptr)
}

# ============================================================================
# Print methods
# ============================================================================

S7::method(print, GDALGroup) <- function(x, ...) {
  cat("<GDALGroup>\n")
  cat("  Name: ", get_name(x), "\n", sep = "")

  full <- get_full_name(x)
  if (nchar(full) > 0 && full != get_name(x)) {
    cat("  Path: ", full, "\n", sep = "")
  }

  groups <- get_group_names(x)
  if (length(groups) > 0) {
    cat("  Subgroups (", length(groups), "): ",
        paste(head(groups, 5), collapse = ", "),
        if (length(groups) > 5) ", ..." else "", "\n", sep = "")
  }

  arrays <- get_mdarray_names(x)
  if (length(arrays) > 0) {
    cat("  Arrays (", length(arrays), "): ",
        paste(head(arrays, 5), collapse = ", "),
        if (length(arrays) > 5) ", ..." else "", "\n", sep = "")
  }

  invisible(x)
}

S7::method(print, GDALMDArray) <- function(x, ...) {
  cat("<GDALMDArray>\n")
  cat("  Name: ", get_name(x), "\n", sep = "")
  cat("  Type: ", get_data_type_name(x), "\n", sep = "")

  dims <- get_dimensions(x)
  if (nrow(dims) > 0) {
    dim_str <- paste(dims$name, dims$size, sep = "=", collapse = ", ")
    cat("  Dimensions: ", dim_str, "\n", sep = "")
  }

  unit <- get_unit_type(x)
  if (nchar(unit) > 0) {
    cat("  Unit: ", unit, "\n", sep = "")
  }

  nodata <- get_nodata_value(x)
  if (!is.null(nodata)) {
    cat("  NoData: ", nodata, "\n", sep = "")
  }

  invisible(x)
}
