# R/zz-altarr.R
# Manual file - NOT generated by orchestrate.R
# A GDAL array or band as a lazy R array, through the altarr package.

#' A GDAL array or band as a lazy R array
#'
#' Returns an ordinary double array: a `dim`, no class, and nothing read yet.
#' Base R indexing, `sum()`, `mean()` and the rest pull values from GDAL as
#' they need them, a batch of chunks at a time, and keep recent chunks in a
#' cache. The object is made by the altarr package (`hypertidy/altarr`),
#' which has to be installed; see `altarr::altarr_contract` for what base R
#' reads lazily and what it materialises.
#'
#' The chunks are the source's own: a multidimensional array's `block_size`,
#' or a band's `block_size`. A dimension the format does not chunk along is
#' given a chunk of its full length if it is one of the two fastest varying
#' (the first two in R's order), and 1 otherwise, so a contiguous netCDF
#' variable reads a whole grid per time step. `chunk` overrides that, in R's
#' dimension order.
#'
#' Each batch of chunks altarr asks for is one GDAL read. The bounding slice
#' of the batch is first given to [advise_read()], so a Zarr array decodes
#' every chunk in it on GDAL's threads at once, then read in one call and cut
#' into chunks in R. A batch spread so thinly that its bounding slice holds
#' more than `density` times as many chunks as were asked for (points
#' scattered over a large array, say) is read chunk by chunk instead, so a
#' few scattered chunks never cost the whole slice between them.
#'
#' Dimensions are in the order [read_mdarray()] gives, the reverse of GDAL's,
#' with the names on `dimnames`: a `(time, lat, lon)` array becomes
#' `[lon, lat, time]`. A band is `[x, y]`, the first row of the raster first,
#' in the order [read_raster()] gives.
#'
#' @section Arguments:
#' \describe{
#'   \item{`chunk`}{The chunk shape, in R's dimension order. Defaults to the
#'     source's own, as above.}
#'   \item{`nodata_as_na`}{Whether the source's nodata value reads as `NA`.
#'     TRUE by default, as for [read_mdarray()].}
#'   \item{`density`}{How sparse a batch may be and still be read as one
#'     slice. Default 4.}
#'   \item{`array`, `options`}{For a path: the array's name or its full path
#'     from the root, as for [open_mdarray()], and open options as for
#'     [gdal_open()].}
#' }
#'
#' @section Saving:
#' Given a path, the array keeps the path, the array's name and the options,
#' and opens the dataset on its first read, and again on the first read in
#' a new session. So `saveRDS()` writes a recipe of a few kilobytes and
#' `readRDS()` gives back a working array anywhere the path still opens.
#' Given an open [GDALMDArray] or [GDALRasterBand], the array reads from that
#' handle and works only while it is open and only in this session.
#'
#' As altarr's contract says, the source must not change underneath: values
#' are re-read after they leave the cache, and a recipe re-reads its source.
#'
#' @param x A [GDALMDArray], a [GDALRasterBand], or the path of a
#'   multidimensional source.
#' @param ... See the Arguments section.
#' @return A lazy double array.
#' @export
#' @examples
#' if (requireNamespace("altarr", quietly = TRUE)) {
#'   path <- system.file("extdata/multidim.zarr", package = "GDAL7")
#'   x <- as_altarr(path, array = "temperature")
#'   dim(x)
#'   x[2, 3, ]
#'   sum(x)
#'   altarr::altarr_stats(x)[["fetch_calls"]]
#' }
as_altarr <- S7::new_generic("as_altarr", "x")

S7::method(as_altarr, GDALMDArray) <- function(x, ..., chunk = NULL,
                                               nodata_as_na = TRUE,
                                               density = 4) {
  open_array <- function() x
  mdarray_altarr(open_array, x, chunk, nodata_as_na, density)
}

S7::method(as_altarr, S7::class_character) <- function(x, ..., array,
                                                       options = NULL,
                                                       chunk = NULL,
                                                       nodata_as_na = TRUE,
                                                       density = 4) {
  if (length(x) != 1L || is.na(x)) {
    stop("`x` must be a single path", call. = FALSE)
  }
  if (missing(array) || !is.character(array) || length(array) != 1L ||
      is.na(array)) {
    stop("`array` must name one array in the source", call. = FALSE)
  }
  open_array <- reopening_array(x, array, options)
  mdarray_altarr(open_array, open_array(), chunk, nodata_as_na, density)
}

S7::method(as_altarr, GDALRasterBand) <- function(x, ..., chunk = NULL,
                                                  nodata_as_na = TRUE,
                                                  density = 4) {
  need_altarr()
  dims <- c(x@xsize, x@ysize)
  if (is.null(chunk)) {
    chunk <- as.double(x@block_size)
  }
  chunk <- altarr_chunk(chunk, dims)
  nodata <- if (isTRUE(nodata_as_na)) x@nodata_value else NULL

  read_box <- function(lo, count) {
    window <- c(lo, count)
    advise_read(x, window = window)
    values <- read_raster(x, window = window)
    if (!is.null(nodata) && !is.na(nodata)) {
      values[!is.na(values) & values == nodata] <- NA_real_
    }
    values
  }
  altarr::altarr(dims, chunk, chunk_fetch(read_box, dims, chunk, density),
                 dimnames = list(x = NULL, y = NULL), type = "double")
}

# The array version of the above, given a function that hands back an open
# array: the same one every time for a handle, or one that reopens when the
# handle has not survived into this session.
mdarray_altarr <- function(open_array, arr, chunk, nodata_as_na, density) {
  need_altarr()
  gdal_dims <- arr@dimensions
  if (nrow(gdal_dims) < 1L) {
    stop("A lazy array needs at least one dimension", call. = FALSE)
  }
  dims <- rev(gdal_dims$size)
  if (is.null(chunk)) {
    chunk <- rev(arr@block_size)
  }
  chunk <- altarr_chunk(chunk, dims)
  nodata_as_na <- isTRUE(nodata_as_na)

  read_box <- function(lo, count) {
    a <- open_array()
    start <- rev(lo) + 1
    advise_read(a, start = start, count = rev(count))
    read_mdarray(a, start = start, count = rev(count),
                 nodata_as_na = nodata_as_na)
  }
  dimnames <- vector("list", length(dims))
  names(dimnames) <- rev(gdal_dims$name)
  altarr::altarr(dims, chunk, chunk_fetch(read_box, dims, chunk, density),
                 dimnames = dimnames, type = "double")
}

# altarr's fetch contract: an integer matrix of 0-based chunk coordinates in,
# one column-major vector per row out, clipped at the array's edge.
# `read_box(lo, count)` reads the slice starting at 0-based `lo` with `count`
# values along each dimension, both in R's order, and returns its values in
# R's order. Built in a small function so that a saved recipe carries these
# few values and nothing from the caller.
chunk_fetch <- function(read_box, dims, chunk, density) {
  force(read_box)
  force(dims)
  force(chunk)
  force(density)
  function(chunks) {
    chunks <- matrix(as.double(chunks), ncol = length(dims))
    n <- nrow(chunks)
    first <- chunks * rep(chunk, each = n)
    extent <- first
    extent[] <- pmin(rep(chunk, each = n), rep(dims, each = n) - first)

    box_chunks <- prod(apply(chunks, 2, max) - apply(chunks, 2, min) + 1)
    if (n == 1L || box_chunks > density * n) {
      return(lapply(seq_len(n), function(r) {
        as.vector(read_box(first[r, ], extent[r, ]))
      }))
    }

    lo <- apply(first, 2, min)
    hi <- apply(first + extent, 2, max)
    box <- read_box(lo, hi - lo)
    dim(box) <- hi - lo
    lapply(seq_len(n), function(r) {
      index <- lapply(seq_along(dims), function(k) {
        first[r, k] - lo[k] + seq_len(extent[r, k])
      })
      as.vector(do.call(`[`, c(list(box), index, list(drop = FALSE))))
    })
  }
}

# The chunk shape altarr is given: the source's own, with a dimension the
# format does not chunk along given its full length for the two fastest
# dimensions and 1 for the rest.
altarr_chunk <- function(chunk, dims) {
  chunk <- as.double(chunk)
  if (length(chunk) == 1L) {
    chunk <- rep(chunk, length(dims))
  }
  if (length(chunk) != length(dims) || anyNA(chunk) || any(chunk < 0)) {
    stop("`chunk` needs one non-negative value per dimension: ",
         length(dims), call. = FALSE)
  }
  unchunked <- chunk == 0
  fastest <- seq_along(dims) <= 2L
  chunk[unchunked & fastest] <- dims[unchunked & fastest]
  chunk[unchunked & !fastest] <- 1
  if (any(chunk > .Machine$integer.max)) {
    stop("A chunk longer than an R integer is not supported", call. = FALSE)
  }
  pmin(chunk, dims)
}

# An array opened from a path on first use, and again in a new session. The
# handle lives in an environment the recipe carries; the session stamp says
# whether it was opened in this session, since an external pointer read back
# from disk points at nothing.
reopening_array <- function(path, array, options) {
  force(path)
  force(array)
  force(options)
  state <- new.env(parent = emptyenv())
  function() {
    if (!identical(state$session, gdal7_session_stamp())) {
      ds <- gdal_open(path, multidim = TRUE, options = options)
      root <- get_root_group(ds)
      if (is.null(root)) {
        stop("`", path, "` did not open as a multidimensional source",
             call. = FALSE)
      }
      arr <- open_mdarray(root, array)
      if (is.null(arr)) {
        stop("No array called `", array, "` in `", path, "`", call. = FALSE)
      }
      state$array <- arr
      state$session <- gdal7_session_stamp()
    }
    state$array
  }
}

# One value per R session, made on first use.
gdal7_session <- new.env(parent = emptyenv())

gdal7_session_stamp <- function() {
  if (is.null(gdal7_session$stamp)) {
    gdal7_session$stamp <- paste(Sys.getpid(), format(Sys.time(), "%OS6"),
                                 sample.int(.Machine$integer.max, 1L))
  }
  gdal7_session$stamp
}

need_altarr <- function() {
  if (!requireNamespace("altarr", quietly = TRUE)) {
    stop("The altarr package is needed for a lazy array: ",
         "remotes::install_github(\"hypertidy/altarr\")", call. = FALSE)
  }
}
